### ISSUE TITLE
Update the lock icon

### ISSUE THREAD

**Issue by DrDinosaur** [byt3bl33d3r/MITMf#100]
The current lock looks ancient. Update it to something like Chrome's:
http://gyazo.com/66f17b2151cbb71fc82e12278afec835

**Comment by byt3bl33d3r** [comment]
@DrDinosaur agreed, will do!

**Comment by thezakman** [comment]
I did this for you @byt3bl33d3r 
https://github.com/thezakman/MITMf/blob/master/lock.ico

**Comment by byt3bl33d3r** [comment]
@DrDinosaur @thezakman  'tis been updated in 0.9.8, thanks

**Comment by thezakman** [comment]
You are welcome, the tool is turning out great. 
A really nice work @byt3bl33d3r!
