### ISSUE TITLE
Can't run setup on OS X (Python 2.7.9)

### ISSUE THREAD

**Issue by SonOfLysander** [byt3bl33d3r/MITMf#102]
I can't find anywhere that explicitly states on the main page that 2.7 is the required python, but this issue seems to indicate it is: https://github.com/byt3bl33d3r/MITMf/issues/33

Anyways, I can confirm that the virtualenvironment I'm using has python 2.7.9 as the working python
```
$ python --version
Python 3.4.3
$ python setup.sh
  File "setup.sh", line 3
    git submodule init && git submodule update --recursive
                ^
SyntaxError: invalid syntax
```
This is on a fresh git-clone with no modifications (`git status` shows clean), so I'm not sure what I'm doing incorrectly if anything.

**Comment by SonOfLysander** [comment]
I'm an idiot. I should have slept or something. That's a shellscript. I'm closing the issue. It needs to run with bash.

**Comment by byt3bl33d3r** [comment]
@SonOfLysander don't worry bro, happens to everybody xD
