### ISSUE TITLE
ImportError: cannot import name LOG

### ISSUE THREAD

**Issue by FreelancePentester** [byt3bl33d3r/MITMf#103]
Traceback (most recent call last):
  File "mitmf.py", line 180, in <module>
    from core.protocols.smb.SMBserver import SMBserver
  File "/opt/mitmf/core/protocols/smb/SMBserver.py", line 5, in <module>
    from impacket import version, smbserver, LOG
ImportError: cannot import name LOG

**Comment by asolino** [comment]
LOG is defined in https://github.com/CoreSecurity/impacket/blob/master/impacket/__init__.py

check you have the latest impacket version installed (https://pypi.python.org/pypi/impacket/0.9.13)

**Comment by byt3bl33d3r** [comment]
@asolino beat me to it ;)

**Comment by FreelancePentester** [comment]
@asolino thanks you!

**Comment by rhertzog** [comment]
It would be nice if this could be actually documented in the requirements.txt file... we have been bitten by this in Kali too.

**Comment by dpoulimenos** [comment]
[*] MITMf v0.9.7 online... initializing plugins
|_ JSKeylogger v0.2
|_ Spoof v0.6
|_ FilePwn v0.3
|  |_ BDFProxy v0.3.2 online
|  |_ Connected to Metasploit v4.11.4-2015090201
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
Traceback (most recent call last):
  File "./mitmf.py", line 180, in <module>
    from core.protocols.smb.SMBserver import SMBserver
  File "/usr/share/mitmf/core/protocols/smb/SMBserver.py", line 5, in <module>
    from impacket import version, smbserver, LOG
ImportError: cannot import name LOG


This is my error so just tell me how to fix it i saw in earlier comments and i use google and still no answer to my questions.You said to update impacket but how to update it ? Im using kali sana :dancer:

**Comment by xmcp** [comment]
@dpoulimenos 
`pip install impacket --upgrade`
