### ISSUE TITLE
Port MITMf's base proxy to mitmproxy

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/MITMf#105]
I've been contemplating this for a couple of days already.. 
The benefits of using mitmproxy over the original proxy implemented with Twisted are pretty convincing:
- MITMf's code base would be halved
- The way the framework hooks and loads the plugins would be a lot less 'hacky'
- SSL/TLS support out of the box
- Plugins would benefit from mitmproxy's API
- Less dependencies
- mitmproxy is actively developed (which means HTTP/2 support in the future)

Would probably have to re-write most of the plugins, but it would be worth it IMHO.

Before even considering starting to do this, the following requirements have to be met:
- [ ] Implement the original SSLstrip attack using libmproxy
- [x] re-write the hooking 'engine' accordingly
- [x] add a switch to disable/enable SSL/TLS interception
- [x] resolve the transparent & regular proxy problem
- [ ] lots of testing

The only downside is that the whole framework would be extremely reliant on an external project

**Comment by byt3bl33d3r** [comment]
Another downside: would have to deal with mitmproxy's transparent vs regular mode, currently you can either connect directly to MITMf's proxy or forward packets to it at the Network layer (e.g. iptables). In mitmproxy you have to choose between the two... 
The simplest way to deal with this would be to setup transparent mode on port 10000 and regular mode on port 100010, but that's kinda sucky :/.
Still have to go through the docs a little bit more

**Comment by secretsquirrel** [comment]
I take pull requests. :P

**Comment by byt3bl33d3r** [comment]
@secretsquirrel lol, I'll be sure to send a couple your way ;)

**Comment by vapor99** [comment]
I think its a great idea

**Comment by byt3bl33d3r** [comment]
@vapor99 thanks, I'm more and more convinced that this is the best way to go.. Currently development is at a stand still cause I have my finals to take care of, next week I'll probably start taking a serious jab at doing this.

**Comment by byt3bl33d3r** [comment]
Started porting it over yesterday

**Comment by vapor99** [comment]
Awesome!  I'll help test.

**Comment by byt3bl33d3r** [comment]
@vapor99 sure thing! thanks! will let you know!

**Comment by byt3bl33d3r** [comment]
initial implementation in e686e101031b8ee5f49040da51d193ada9c00e48

**Comment by theoneandonly-vector** [comment]
Hmm, sounds interesting.

**Comment by byt3bl33d3r** [comment]
I'm closing this for now, unfortunately mitmproxy is currently lacking a lot of things that are essential to making MITMf work.

**Comment by mw3demo** [comment]
Hey @byt3bl33d3r

Congrats on landing your new job, hope all is good in the US! :+1: Out of curiosity, what is mitmproxy missing in its current state? Any further planned updates for MITMf?
