### ISSUE TITLE
Inject HTML/JS file

### ISSUE THREAD

**Issue by DrDinosaur** [byt3bl33d3r/MITMf#110]
The --html-payload or some other new option should be able to read in a file with the HTML you want.

**Comment by DrDinosaur** [comment]
Actually, it's not that big of a deal, but could be helpful.

**Comment by byt3bl33d3r** [comment]
@DrDinosaur originally there was an option for this but I removed it, I think the reasoning behind it at the time was that injecting via ```--js-url``` or ```--html-url``` covers 99% of the use cases ... 
That being said I could add it back if an option like this would be useful

**Comment by rotatingJazz** [comment]
+1.

Also, I'll take the chance to say: Great work @byt3bl33d3r :+1: :+1: :+1:

**Comment by byt3bl33d3r** [comment]
This has been implemented in fb0e8a37626b9dcbb424a7de5ef94eb8e67908f8, will close the issue when merged to master

**Comment by byt3bl33d3r** [comment]
implemented in 0.9.8
