### ISSUE TITLE
Ignore a specific target (or range of targets)

### ISSUE THREAD

**Issue by auraltension** [byt3bl33d3r/MITMf#112]
It'd be great to have an inverse match on a target.  For example I keep trying my home network, but one host is generating a lot of network traffic so it'd be good to ignore just that one.

I thought of possibly putting something into `core/protocols/arp/ARPpoisoner.py` which would allow one to prepend **!** to a target (or target range) to have these hosts not end up in `targetList`, but I'm not sure this would be the best place to do this.  It also wouldn't do anything if --targets was populated only with the inverse, one would have to specify say something like `--targets 192.168.0.1-192.168.0.254,!192.168.1.100` which is not ideal.

Incidentally, while going down this train of thought I was wondering if it would be beneficial to pull out the `getTargetRange` present functionality in favour of using [netaddr](http://pythonhosted.org/netaddr/) which is already a dependency for Responder, and would allow for [nmap style targets](http://nmap.org/book/man-target-specification.html).  There is an example implementation [here](https://pythonhosted.org/netaddr/_modules/netaddr/ip/nmap.html).

If you provide your thoughts I'd be happy to poke around and submit a PR.

**Comment by byt3bl33d3r** [comment]
@auraltension originally I wanted to implement the ```getTargetRange``` function using netaddr, I forget the reasoning behind not doing so... in any case I'll probably get to that today since I finally have some spare time.

The inverse match idea is def a awesome idea!  will look into that today as well!

**Comment by auraltension** [comment]
Awesome :)

**Comment by rotatingJazz** [comment]
Ettercap does reverse matching and it is very useful. It is limited by the fact that you can only have one ip to match for it, which tends to be heir pulling when you'd like to match all dynamically except for 2 specific ones :dancers: So +1 on @auraltension 's nmap style targets :+1:

**Comment by byt3bl33d3r** [comment]
@auraltension as of commit e3aa8ba617ed3644b443030990298405a2dae225 ```getTargetRange``` uses netaddr, haven't fully tested it yet so I might have broken some stuff.

@rotatingJazz cool, I'll get right on it one I finish fixing some bugs ;)

**Comment by byt3bl33d3r** [comment]
this has been implemented in 0.9.8
