### ISSUE TITLE
Browsersniper plugin error

### ISSUE THREAD

**Issue by konlyk** [byt3bl33d3r/MITMf#115]
When i try to use the --browsersniper plugin I get this error :

[Msfrpc] Error connecting to Metasploit: ('Connection aborted.', error(111, 'Connection refused'))

I have the latest kali linux installed and the command i am running is : ' python mitmf.py -i eth0 --hsts --browsersniper --spoof --arp --gateway 192.168.13.155 --target 192.168.13.186 '

**Comment by byt3bl33d3r** [comment]
@konlyk did you start Metasploit's rpc server?

**Comment by konlyk** [comment]
@byt3bl33d3r  Yes, i did.

**Comment by byt3bl33d3r** [comment]
@konlyk what command did you use?

**Comment by konlyk** [comment]
@byt3bl33d3r to start the Metasploit's rpc server?

**Comment by byt3bl33d3r** [comment]
@konlyk yep

**Comment by konlyk** [comment]
@byt3bl33d3r  In the menu of kali linux , there is an option to ' start metasploit community/pro '. The command that this button executes is ' sh -c "/opt/metasploit/scripts/start.sh;${SHELL:-bash}" '

**Comment by byt3bl33d3r** [comment]
@konlyk starting metasploit and it's rpc server are two diffrent things, I suggest you read the Metasploit docs

**Comment by konlyk** [comment]
@byt3bl33d3r  I am sorry, i thought it was the same.
