### ISSUE TITLE
ImportError: cannot import name STATUS_SMB_BAD_TID

### ISSUE THREAD

**Issue by shimmy2101** [byt3bl33d3r/MITMf#116]
Already updated everything I could , requirements installed with no error. Thank you in advance.

root@sh:~/MITMf# python mitmf.py --spoof --arp --interface wlan0 --gateway 192.168.0.1 --target 192.168.0.104 --smbtrap
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
|_ SMBTrap v1.0
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
Traceback (most recent call last):
  File "mitmf.py", line 186, in <module>
    from core.servers.smb.SMBserver import SMBserver
  File "/root/MITMf/core/servers/smb/SMBserver.py", line 8, in <module>
    from core.servers.smb.KarmaSMB import KarmaSMBServer
  File "/root/MITMf/core/servers/smb/KarmaSMB.py", line 65, in <module>
    from impacket.smbserver import SRVSServer, decodeSMBString, findFirst2, STATUS_SMB_BAD_TID, encodeSMBString, \
ImportError: cannot import name STATUS_SMB_BAD_TID
root@sh:~/MITMf#

**Comment by byt3bl33d3r** [comment]
@shimmy2101 I'm guessing you resolved this?

**Comment by shimmy2101** [comment]
yep my mistake))Thank you

**Comment by JimWas** [comment]
How did you fix it? I'm getting the same error regardless of using the smbtrap plugin

**Comment by byt3bl33d3r** [comment]
@JimWas update your impacket installation

**Comment by JimWas** [comment]
Worked perfectly, thanks. FYI for anyone else, I pulled impacket from https://github.com/coresecurity/impacket and it works.
