### ISSUE TITLE
NameError while arp spoofing

### ISSUE THREAD

**Issue by softwarerat** [byt3bl33d3r/MITMf#117]
Hello,

I am getting this error while I try to do arpspoof a client. Since it doesn't seem to be a library/3rd party error, it seems to be a bug. 

[*] MITMf v0.9.7 online... initializing plugins
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
Traceback (most recent call last):
  File "mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/opt/MITMf/plugins/SSLstrip+.py", line 41, in initialize
    if IpTables.getInstance().dns is False:
NameError: global name 'IpTables' is not defined

**Comment by shimmy2101** [comment]
Same problem,

root@sh:~/MITMf# python mitmf.py --spoof --arp --interface wlan0 --gateway 192.168.0.1 --target 192.168.0.103 --hsts

   ▄▄▄▄███▄▄▄▄    ▄█      ███       ▄▄▄▄███▄▄▄▄      ▄████████ 
 ▄██▀▀▀███▀▀▀██▄ ███  ▀█████████▄ ▄██▀▀▀███▀▀▀██▄   ███    ███ 
 ███   ███   ███ ███▌    ▀███▀▀██ ███   ███   ███   ███    █▀  
 ███   ███   ███ ███▌     ███   ▀ ███   ███   ███  ▄███▄▄▄     
 ███   ███   ███ ███▌     ███     ███   ███   ███ ▀▀███▀▀▀     
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
  ▀█   ███   █▀  █▀      ▄████▀    ▀█   ███   █▀    ███        

[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
Traceback (most recent call last):
  File "mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/root/MITMf/plugins/SSLstrip+.py", line 41, in initialize
    if IpTables.getInstance().dns is False:
NameError: global name 'IpTables' is not defined


Without "--hsts" I have no error but I can't see no packets only this :



2015-06-08 14:30:06 [SMBserver] Config file parsed
2015-06-08 14:30:06 [SMBserver] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
2015-06-08 14:30:06 [SMBserver] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
2015-06-08 14:30:06 [SMBserver] Config file parsed
2015-06-08 14:30:06 [SMBserver] Config file parsed

**Comment by byt3bl33d3r** [comment]
@softwarerat @shimmy2101 my bad! should be fixed now .. thanks

**Comment by softwarerat** [comment]
Sorry but this time I am getting this error;

[*] MITMf v0.9.7 online... initializing plugins
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
Traceback (most recent call last):
  File "mitmf.py", line 186, in <module>
    from core.servers.smb.SMBserver import SMBserver
  File "/opt/MITMf/core/servers/smb/SMBserver.py", line 7, in <module>
    from impacket import version, smbserver, LOG
ImportError: cannot import name LOG

**Comment by byt3bl33d3r** [comment]
@softwarerat you have to update your version of impacket

**Comment by softwarerat** [comment]
Thank you!

**Comment by niallmerrigan** [comment]
I tried the update but it still threw the same error as above.

**Comment by byt3bl33d3r** [comment]
@niallmerrigan did you update using pip?

**Comment by niallmerrigan** [comment]
DOh!!! I just get a wget.. my bad..

**Comment by byt3bl33d3r** [comment]
@niallmerrigan ok, if it continues to cause an error , try cloning the latest version of impacket from github and installing manually
