### ISSUE TITLE
Solve the dependency issue

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/MITMf#119]
Too many of them!! plus MITMf relies on bleeding edge versions !!

**Comment by asolino** [comment]
IMHO, I'd say you should have a stable version that depends on stable dependencies (e.g. impacket-0.9.13). That will always be behind in terms of features,  but guarantees that stuff works.
Then you have a development version with the latest and greatest but people should know things could break. (e.g. impacket-0.9.14-dev).

Another approach is you to have the dependencies repos inside MITMf (if license permits it) and you merge the dependencies changes if needed.

Hope this helps!

**Comment by byt3bl33d3r** [comment]
@asolino thanks for the input! I'm thinking of going with second option actually because I really don't want to manage two version :P , plus I don't mind libs to be a little bleeding edge. I will probably run into licensing issues but will probably be able to sort things out

**Comment by byt3bl33d3r** [comment]
I'm going to merge the ```mitmflib``` branch soon, this should solve two problems:
- Packaging the framework on Kali linux
- Allow me to use bleeding edge deps, without making everyone upgrade their installed libraries

**Comment by byt3bl33d3r** [comment]
Done in 2cde231b5557ca2251634fa2d77adcc0be289013
