### ISSUE TITLE
pip not available in latest rpi2 kali repo

### ISSUE THREAD

**Issue by jaredmcqueen** [byt3bl33d3r/MITMf#127]
specifically kali 1.1.1 on the new raspberry pi 2.

https://www.offensive-security.com/kali-linux-vmware-arm-image-download/

pip isn't available even after an apt-get update && apt-get dist-upgrade

a solution would be:

apt-get install curl
curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python2.7

(from here http://stackoverflow.com/questions/5585875/what-is-the-official-preferred-way-to-install-pip-and-virtualenv-systemwide)

or just use python 2.7.9 which ships with pip.

**Comment by jaredmcqueen** [comment]
ok finally got a successful install on a raspberry pi 2.

you need:

apt-get install python-dev libnl-dev gcc

and then run other_setup.py

**Comment by byt3bl33d3r** [comment]
@jaredmcqueen hey, ```pip``` and ```easy_install``` should be provided by the ```python-setuptools``` package (depending on your distro it could also be named ```python2-setuptools```)
this is the preferred way for it to be installed especially on kali
