### ISSUE TITLE
Can't Start MITMf

### ISSUE THREAD

**Issue by SoulBItz** [byt3bl33d3r/MITMf#129]
root@Kali:~/Desktop/MITMf-master# python mitmf.py 
Traceback (most recent call last):
  File "mitmf.py", line 32, in <module>
    from plugins import *
  File "/root/Desktop/MITMf-master/plugins/FilePwn.py", line 68, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory

**Comment by jakuta-tech** [comment]
Did you run the kali_setup.sh script ?

**Comment by byt3bl33d3r** [comment]
@SoulBItz you didn't run the ```kali_setup.sh```` script, like @jakuta-tech said

**Comment by th0m1** [comment]
hello what's the command line to run setup.sh

**Comment by ShadeLotus** [comment]
similar problem here on nethunter CM11 -- beef xss is running, cannot find mitmf.py -- kali_setup.sh command not found.
