### ISSUE TITLE
python packages error issue

### ISSUE THREAD

**Issue by crrufat** [byt3bl33d3r/MITMf#131]
Hello, 

I'm working on Kali Linux distro and tried to install MITMf. Firstly cloned it and then ran kali_setup.sh but got following error. 

root@kali:/MITMf# ./kali_setup.sh
Submodule 'libs/bdfactory' () registered for path 'libs/bdfactory'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-capstone
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pefile
E: Unable to locate package python-pypcap
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): mitmflib in /usr/local/lib/python2.7/dist-packages

Then tried to update requirements.txt and after that got the same error. Can u help me with this issue.

**Comment by byt3bl33d3r** [comment]
@crrufat hi, the fact that your system is unable to locate some of the packages means that your kali system is old or hasn't been updated in a while, I suggest you run ```apt-get update && apt-get dist-upgrade``` or download a fresh VM and try again
