### ISSUE TITLE
I can't run MITMf: ImportError: No module named twisted.web

### ISSUE THREAD

**Issue by Guanrenfu** [byt3bl33d3r/MITMf#132]
I'm using Arch Linux, and I've run the "./other_setup.sh" and "sudo pip install --upgrade -r requirements.txt".

But when I run "python2 mitmf.py", I got this error:
>Traceback (most recent call last):
>  File "mitmf.py", line 27, in <module>
>    from twisted.web import http
>ImportError: No module named twisted.web

What is this module? and how can I install it?

**Comment by bandwagonz** [comment]
Pip install twisted 

should do the trick (my syntax is probably off)

**Comment by Guanrenfu** [comment]
@bandwagonz Well, I think I've already install this:
>Requirement already up-to-date: twisted in /usr/lib/python3.4/site-packages
>Requirement already up-to-date: zope.interface>=4.0.2 in /usr/lib/python3.4/site-packages (from twisted)
>Requirement already up-to-date: setuptools in /usr/lib/python3.4/site-packages (from zope.interface>=4.0.2->twisted)

**Comment by byt3bl33d3r** [comment]
@Guanrenfu you're running Arch so you need to install the dependencies using ```pip2``` instead of ```pip```, the latter is for Python 3 ```sudo pip2 install --upgrade -r requirements.txt```
