### ISSUE TITLE
Unable To Sniff Anything Other Than ARP Messages.

### ISSUE THREAD

**Issue by bandwagonz** [byt3bl33d3r/MITMf#135]
This time I'm on a fresh Kali 1.1.0a install. Got a new laptop and the first thing I installed was mitmf after a dist upgrade. 

For some reason mitmf isn't able to capture anything except ARP messages from my desktop and phone looking for the gateway.

I can post the debug logs when I get home but it doesn't show much aside from the gateway spoofing messages. 

Any suggestions on how I can deep dive in to this further would be appreciated.

**Comment by byt3bl33d3r** [comment]
@bandwagonz hi, 
The debug logs would help a lot thanks, also if you can paste the full command string you used would great

**Comment by byt3bl33d3r** [comment]
also a packet capture would help a lot

**Comment by bandwagonz** [comment]
This is the command string I used:
./mitmf.py -i wlan0 --spoof --arp --gateway 192.168.0.2 --hsts 

WIm not at home  right now, but tonight I'll send over the log, and cap. 

Thanks for your help.

**Comment by bandwagonz** [comment]
I just reinstalled Kali once again because i was having some other issues as well. Most likely this was because of a bad install. I'll try using MITMf again in a few days and report back if i'm still having issues.

**Comment by byt3bl33d3r** [comment]
@bandwagonz cool, will be dropping 0.9.8 in a couple of days which should bring a huge performance boost

**Comment by byt3bl33d3r** [comment]
and bug fixes

**Comment by bandwagonz** [comment]
@byt3bl33d3r sweet! Just posting back to let you know that the issue was on my side. Sorry for the false alarm.
