### ISSUE TITLE
Refactor the framework's Responder code

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/MITMf#137]
https://github.com/jrmdev/Responder

**Comment by byt3bl33d3r** [comment]
i'm very bad at typing apparently

**Comment by mw3demo** [comment]
Looks like his changes were merged upstream into master on July 6th:

https://github.com/SpiderLabs/Responder/commit/3c00567fa6a6628eaeb9fda556082fa8f9ae8bcc

**Comment by byt3bl33d3r** [comment]
@mw3demo yep, they were merged to master earlier today \o/

**Comment by byt3bl33d3r** [comment]
done in 772ef9ab3959a85001533ff7af4ef3dbdb50565b
