### ISSUE TITLE
./setup don't work for me  . pleasssse help !! 

### ISSUE THREAD

**Issue by th0m1** [byt3bl33d3r/MITMf#138]
when i enter ./setup nothing happens and i checked inside  the file : 
#!/usr/bin/env bash

git submodule init && git submodule update --recursive

i tried the command inside setup.sh but nothing happens  , one thing is i don't have /usr/bin/env bash in the folder 
./setup.sh don't work and how i can make it work ? 

1 )Clone this repository  = extract to desktop 
2) Run the ```setup.sh``` script   i entered  " chmod +x setup.sh" then "./setup.sh"
3) Run the command ```pip install --upgrade -r requirements.txt``` to install all Python dependencies . I entered command " pip install --upgrade -r requirements.txt "
what else should i do ??? sorry i am beginner

i get this :root@kali:~/Desktop/MITMf-master# chmod +x setup.sh
root@kali:~/Desktop/MITMf-master# ./setup.sh
root@kali:~/Desktop/MITMf-master# pip install --upgrade -r requirements.txt
Downloading/unpacking git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-thmQS7-build
  Running setup.py egg_info for package from git+git://github.com/kti/python-netfilterqueue

**Comment by byt3bl33d3r** [comment]
Hi,
As I already explained to you via email, everything you need to do is in the installation section of the readme,  don't understand what the problem is, you've done everything you need to do to get MITMf up and running.

**Comment by th0m1** [comment]
the issssu is i get this even i installed 
root@kali:~/Desktop/MITMf-master# python mitmf.py -i eth0
Traceback (most recent call last):
  File "mitmf.py", line 37, in <module>
    from plugins import *
  File "/root/Desktop/MITMf-master/plugins/filepwn.py", line 70, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory

**Comment by byt3bl33d3r** [comment]
@th0m1 do you have the ```git``` utility installed?

**Comment by th0m1** [comment]
no and how i must install it ? i don't what it is ?

**Comment by byt3bl33d3r** [comment]
@th0m1 yeah... no offense, I think you should learn a little bit more before using this tool

**Comment by byt3bl33d3r** [comment]
@th0m1 just fyi, ```apt-get install git```

**Comment by th0m1** [comment]
the console said no update available i think everythings are allready up to date . In addition i tried git clone https://github.com/git/git . 

root@kali:~# apt-get install git
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
git est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.

**Comment by byt3bl33d3r** [comment]
@th0m1 can you paste the output of ```ls libs``` and ```ls libs/bdfactory```

**Comment by th0m1** [comment]
root@kali:~/Desktop/MITMf-master# ls libs
bdfactory  __init__.py  __init__.pyc
root@kali:~/Desktop/MITMf-master# ls libs/bdfactory
root@kali:~/Desktop/MITMf-master#

**Comment by byt3bl33d3r** [comment]
@th0m1 did you clone the repo or download the zip file?

**Comment by th0m1** [comment]
i download the zip file

**Comment by byt3bl33d3r** [comment]
you need to clone the repo (as the readme says) for the setup.sh script to work
```git clone https://github.com/byt3bl33d3r/MITMf```

**Comment by th0m1** [comment]
thanks the ./setup seems worked 
root@kali:~# git clone https://github.com/byt3bl33d3r/MITMf
Cloning into 'MITMf'...
remote: Counting objects: 2619, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 2619 (delta 0), reused 0 (delta 0), pack-reused 2616
Receiving objects: 100% (2619/2619), 1.11 MiB | 500 KiB/s, done.
Resolving deltas: 100% (1725/1725), done.

**Comment by Wr3tched** [comment]
Where is the setup.sh?

**Comment by ritiek** [comment]
@Wr3tched It got removed in 5b7967f02d6d2788ddfc5e1590bd8ed1373d5a11.
