### ISSUE TITLE
No module named pkg_resources

### ISSUE THREAD

**Issue by Zaratros** [byt3bl33d3r/MITMf#140]
Hi! I'm having some difficulties in installing the new versions. Here's what I get:

root@kali:~/MITMf# pip install --upgrade -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources'

root@kali:~/MITMf# ./mitmf.py
Traceback (most recent call last):
  File "./mitmf.py", line 37, in <module>
    from plugins import *
  File "/root/MITMf/plugins/responder.py", line 20, in <module>
    import flask
  File "/usr/local/lib/python2.7/dist-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ImportError: No module named werkzeug.exceptions

**Comment by byt3bl33d3r** [comment]
@Zaratros this seems to be a problem only with Kali,  the ```setuptools``` package seems to have been deleted somehow try running ```apt-get install --reinstall python-setuptools``` , if that doesn't work try
```wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python```

**Comment by byt3bl33d3r** [comment]
and then re-run ``` pip install --upgrade -r requirements.txt``` to install the deps
