### ISSUE TITLE
arpspoof ignore setting doesnt work

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#148]
normally the arp table on a client (192.168.178.241) before the attacker (192.168.178.200) spoofs looks 
like this
```
192.168.178.1         c0-25-06-78-ca-30     dynamisch
192.168.178.200       00-24-1d-04-25-0a     dynamisch
```
but after i did
```
./mitmf.py -i eth0 --spoof --arp --dns --gateway 192.168.178.1 --ignore 192.168.178.241
```
it looks like this
```
192.168.178.1         00-24-1d-04-25-0a     dynamisch
192.168.178.200       00-24-1d-04-25-0a     dynamisch
```
so the ignore setting doesnt work

**Comment by byt3bl33d3r** [comment]
@WiredLife https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug

**Comment by byt3bl33d3r** [comment]
Closing because of lack of information supplied
