### ISSUE TITLE
ImportError: No module named watchdog.observers gets thrown on certain systems

### ISSUE THREAD

**Issue by liadush** [byt3bl33d3r/MITMf#153]
Hi, 
Iam trying to install MITMf in OS X and running in some issues:

1) at the command "pip install --upgrade" , error message :"'libnfnetlink/linux_nfnetlink.h' file not found"
didn't find any of those to download for OS X

2) when i typed the command "python mitmf.py" getting :"ImportError: No module named watchdog.observers"
while i did install this library.

pip freeze:
watchdog==0.8.3

What went wrong? 

Regards,

**Comment by byt3bl33d3r** [comment]
@liadush I'm looking into this , don't really know whats up with the watchdog library, seems to throw that error on some systems

**Comment by bandwagonz** [comment]
I was getting the same errors after pulling the latest changes. Running 'pip install -r requirements.txt --upgrade' fixed this for me.

**Comment by liadush** [comment]
Hi , Thanks for your answers!

@byt3bl33d3r  thanks for you comment. 

@bandwagonz when iam running 'pip install -r requirements.txt --upgrade' jam getting this error:
"libnfnetlink/linux_nfnetlink.h' file not found"
and when i try to install it manually i am getting error : "only for linux"

Regards,

**Comment by byt3bl33d3r** [comment]
@liadush sorry , just re-read your original post.. OSX isn't supported due to the use of some linux only python libraries

**Comment by gtcdevop** [comment]
Is there a way to port this library "libnfnetlink/linux_nfnetlink.h" to macos??
