### ISSUE TITLE
Import Error not fixed by instructions

### ISSUE THREAD

**Issue by oneTimePad** [byt3bl33d3r/MITMf#154]
I followed the installation instructions exactly, yet recieved the following import error:

Traceback (most recent call last):
  File "mitmf.py", line 30, in <module>
    import core.responder.settings as settings
  File "/opt/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/opt/MITMf/core/configwatcher.py", line 21, in <module>
    from mitmflib.watchdog.observers import Observer
ImportError: No module named mitmflib.watchdog.observers

This error makes sense since I cannot find mitmflib.

**Comment by byt3bl33d3r** [comment]
@oneTimePad then you didn't install mitmflib!  ```pip install --upgrade -r requirements.txt```

**Comment by oneTimePad** [comment]
I am saying that I did that. `pip install --upgrade -r requirements.txt`

**Comment by byt3bl33d3r** [comment]
@oneTimePad what OS are you running?

**Comment by oneTimePad** [comment]
@byt3bl33d3r I ran it on Ubuntu 15.04 (which resulted in some errors when running pip install -r requirements.txt), and then on Kali(Debian) which the requirements installed ran correctly. Both resulted in the same import error above.

**Comment by byt3bl33d3r** [comment]
@oneTimePad can you please paste the errors you encountered ?

**Comment by byt3bl33d3r** [comment]
@oneTimePad also what Kali version are you using?

**Comment by oneTimePad** [comment]
***Here is the output from the install on Ubuntu 15.04, where the errors are around:***

''Downloading characteristic-14.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity->mitmflib->-r requirements.txt (line 2))
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=0.8->cryptography->mitmflib->-r requirements.txt (line 2))
Collecting MarkupSafe (from Jinja2>=2.4->Flask->mitmflib->-r requirements.txt (line 2))
Building wheels for collected packages: cryptography, cffi
  Running setup.py bdist_wheel for cryptography
  Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-MQbyVE/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp6XLdm2pip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-MQbyVE/cryptography/setup.py", line 342, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 268, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 836, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1081, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1093, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 629, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 659, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 842, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1058, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py bdist_wheel for cffi
  Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-MQbyVE/cffi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpWEffCJpip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/c
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
  c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cffi
Failed to build cryptography cffi
Installing collected packages: cffi, cryptography, pyopenssl, Pillow, netaddr, requests, capstone, pypcap, itsdangerous, Werkzeug, MarkupSafe, Jinja2, Flask, zope.interface, Twisted, characteristic, pyasn1-modules, service-identity, scapy, beautifulsoup4, mitmflib, NetfilterQueue
  Running setup.py install for cffi
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-MQbyVE/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cwOASA-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    running build_ext
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-MQbyVE/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cwOASA-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-MQbyVE/cffi''




_________________________________________________________________________

***I am running Kali 1.1 (MITMF via APT works but it doesn't have sslstrip+, so I believe it is older). The pip install --upgrade -r requirments.txt outputs this in kali (there actually were errors):***

Downloading/unpacking git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-w341Bg-build
  Running setup.py egg_info for package from git+git://github.com/kti/python-netfilterqueue
    
Downloading/unpacking mitmflib (from -r requirements.txt (line 2))
  Running setup.py egg_info for package mitmflib
    
Downloading/unpacking pycrypto>=2.6 from https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf5161a0d5d7eda (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package pycrypto
    
Downloading/unpacking pyasn1>=0.1.7 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package pyasn1
    
Downloading/unpacking cryptography from https://pypi.python.org/packages/source/c/cryptography/cryptography-0.9.3.tar.gz#md5=70af3fbce7683b31d173eba225f18650 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking Pillow (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package Pillow
    
Downloading/unpacking netaddr from https://pypi.python.org/packages/source/n/netaddr/netaddr-0.7.15.tar.gz#md5=bd024c8f82f71fd1d90553da64735f14 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package netaddr
    
    warning: no previously-included files matching '*.svn*' found anywhere in distribution
    warning: no previously-included files matching '*.git*' found anywhere in distribution
Downloading/unpacking scapy from https://pypi.python.org/packages/source/s/scapy/scapy-2.3.1.zip#md5=1527f09562d9c1bafa5e619c7782d5a0 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package scapy
    
Downloading/unpacking Twisted from https://pypi.python.org/packages/source/T/Twisted/Twisted-15.3.0.tar.bz2#md5=b58e83da2f00b3352afad74d0c5c4599 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package Twisted
    
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 245, in _get_queued_page
    page = self._get_page(location, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 335, in _get_page
    return HTMLPage.get_page(link, req, cache=self.cache)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 452, in get_page
    resp = urlopen(url)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 85, in __call__
    response = urllib2.urlopen(self.get_request(url))
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

Downloading/unpacking pefile from http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package pefile
    
Downloading/unpacking ipy from https://pypi.python.org/packages/source/I/IPy/IPy-0.83.tar.gz#md5=7b8c6eb4111b15aea31b67108e769712 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package ipy
    
Downloading/unpacking pyopenssl from https://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-0.15.1.tar.gz#md5=f447644afcbd5f0a1f47350fec63a4c6 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package pyopenssl
    
    warning: no files found matching 'OpenSSL/RATIONALE'
    warning: no previously-included files found matching 'leakcheck'
    warning: no previously-included files matching '*.py' found under directory 'leakcheck'
    warning: no previously-included files matching '*.pem' found under directory 'leakcheck'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
Downloading/unpacking service-identity (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package service-identity
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extra_requires'
      warnings.warn(msg)
    
Downloading/unpacking configobj from https://pypi.python.org/packages/source/c/configobj/configobj-5.0.6.tar.gz#md5=e472a3a1c2a67bb0ec9b5d54c13a47d6 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package configobj
    
Requirement already up-to-date: Flask in /usr/lib/python2.7/dist-packages (from mitmflib->-r requirements.txt (line 2))
Downloading/unpacking dnspython from https://pypi.python.org/packages/source/d/dnspython/dnspython-1.12.0.zip#md5=bcfab8f4f4a2280f875e646502b23e66 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package dnspython
    
Downloading/unpacking beautifulsoup4 from https://pypi.python.org/packages/source/b/beautifulsoup4/beautifulsoup4-4.4.0.tar.gz#md5=63d1f33e6524f408cb6efbc5da1ae8a5 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package beautifulsoup4
    
Downloading/unpacking capstone from https://pypi.python.org/packages/source/c/capstone/capstone-3.0.4.tar.gz#md5=3437fa632c89531a7d800a3f8c04fbe3 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package capstone
    
Downloading/unpacking msgpack-python from https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.6.tar.gz#md5=8b317669314cf1bc881716cccdaccb30 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package msgpack-python
    
Downloading/unpacking requests from https://pypi.python.org/packages/source/r/requests/requests-2.7.0.tar.gz#md5=29b173fd5fa572ec0764d1fd7b527260 (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package requests
    
Downloading/unpacking pypcap (from mitmflib->-r requirements.txt (line 2))
  Running setup.py egg_info for package pypcap
    pcap.h not found
    Complete output from command python setup.py egg_info:
    pcap.h not found

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /opt/MITMf/build/pypcap

**Comment by nguyenhuutuananh** [comment]
i got same error with Kali linux 2.0 SANA! :(
