### ISSUE TITLE
mitmf on kali sana  

### ISSUE THREAD

**Issue by th0m1** [byt3bl33d3r/MITMf#158]
i am using kali sana and i get error 

root@kali:~/MITMf# python mitmf.py -i wlan0 --spoof --dns --arp --hsts --gateway 192.168.1.1 --target 192.168.1.44

███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.8 - 'The Dark Side'
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
net.ipv4.ip_forward = 1
|  |_ DNS spoofing enabled
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

^C

Exception in thread NetCreds:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/MITMf/core/netcreds.py", line 49, in sniffer
    sniff(iface=interface, prn=pkt_parser, filter="not host {}".format(ip), store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 575, in sniff
    sel = select([s],[],[],remain)
error: (4, 'Interrupted system call')

net.ipv4.ip_forward = 0

**Comment by byt3bl33d3r** [comment]
@th0m1 thanks!
