### ISSUE TITLE
ImportError: No module named setuptools_ext

### ISSUE THREAD

**Issue by jakuta-tech** [byt3bl33d3r/MITMf#163]
In v0.9.8 doing a git pull resulted in the following error

    Installing collected packages: cryptography, NetfilterQueue, watchdog, cffi, Werkzeug, Jinja2, pycparser, MarkupSafe
    Found existing installation: cryptography 0.9.3
    Uninstalling cryptography:
    Successfully uninstalled cryptography
    Running setup.py install for cryptography
    
    Installed /usr/share/MITMf/build/cryptography/.eggs/cffi-1.1.2-py2.7-linux-i686.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/share/MITMf/build/cryptography/setup.py", line 307, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 272, in __init__
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 327, in finalize_options
      File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 2355, in load
    
      File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 2361, in resolve
    
    ImportError: No module named setuptools_ext
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/usr/share/MITMf/build/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-61Vy9O-record/install-record.txt: Installed /usr/share/MITMf/build/cryptography/.eggs/cffi-1.1.2-py2.7-linux-i686.egg  Traceback (most recent call last):   File "<string>", line 1, in <module>
<....snip....>

Removing cryptography from the requirements file and manually installing doesn't fix the problem as stated in another issue.

The problem seems to be in cffi not installing properly or the order of installation.

Upgrading cffi manually first
    `pip install --upgrade cffi`
Then doing
    `pip install --upgrade -r requirements.txt`

Successfully installed cryptography NetfilterQueue watchdog Werkzeug Jinja2 MarkupSafe
Cleaning up...

**Comment by byt3bl33d3r** [comment]
@jakuta-tech I'm guessing you resolved this?

**Comment by byt3bl33d3r** [comment]
@jakuta-tech if not use try the new install instructions https://github.com/byt3bl33d3r/MITMf/wiki/Installation
it should fix this error

**Comment by jakuta-tech** [comment]
Yep resolved with pip install --upgrade cffi. thnx

**Comment by vapor99** [comment]
Works great!  Thx

**Comment by ivkremer** [comment]
@jakuta-tech thanks a million.
Needed that while installing `cryptography` pip package on mac.
