### ISSUE TITLE
mitmf error with filepwn option

### ISSUE THREAD

**Issue by FreelancePentester** [byt3bl33d3r/MITMf#164]
[*] MITMf v0.9.8 - 'The Dark Side'
|_ Spoof v0.6
net.ipv4.ip_forward = 1
|  |_ ARP spoofing enabled
|_ FilePwn v0.3
|  |_ BDFProxy v0.3.2 online
[Msfrpc] Error connecting to Metasploit: 'MsfRPC: Authentication failed'
net.ipv4.ip_forward = 0

**Comment by HAMIDx9** [comment]
Hi, 

Obviously you should start `msfrpcd` and set an appropriate password via '-P' argument.
Please look at config/mitm.conf, you can see that `mitmf` are using password=abc123 and port=55552, so you can use your own.

**Comment by FreelancePentester** [comment]
Thanks you, but i met an other error.

 mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'

**Comment by HAMIDx9** [comment]
Please make sure you have `python-magic` installed. You can check installed packages by executing `pip freeze`.
If you didn't install all requirements, take a look at requirements.txt.

- Hamid

**Comment by byt3bl33d3r** [comment]
@FreelancePentester https://github.com/byt3bl33d3r/MITMf/wiki/Installation
