### ISSUE TITLE
Kali 2.0 Virtualenv new install fails

### ISSUE THREAD

**Issue by spythedude** [byt3bl33d3r/MITMf#168]
Hi byt3bl33d3r,

Just installed Kali 2.0 64 bit - tried to install using the new instructions and this is all I get when running the below..

(MITMf)root@tuxb0x:~/MITMf# pip install install -r requirements.txt
Collecting install
  Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install

**Comment by byt3bl33d3r** [comment]
@spythedude my bad, made a mistake editing the wiki, the correct command is ```pip install -r requirements.txt```
