### ISSUE TITLE
Install fail on kali linux 2.0 

### ISSUE THREAD

**Issue by mrnghe** [byt3bl33d3r/MITMf#170]
please help me fix it   

Failed building wheel for lxml
Failed to build lxml
Installing collected packages: lxml, pefile, ipy, ua-parser, user-agents, pyopenssl, characteristic, pyasn1-modules, service-identity, configobj, itsdangerous, Werkzeug, MarkupSafe, Jinja2, Flask, dnspython, beautifulsoup4, capstone, python-magic, msgpack-python, requests, pypcap, chardet, NetfilterQueue
  Running setup.py install for lxml
    Complete output from command /root/.virtualenvs/MITMf/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-rlRRV3/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p9kzFV-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/MITMf/include/site/python2.7/lxml:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.4.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
    running build_ext
    building 'lxml.etree' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-rlRRV3/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:239:0:
    /tmp/pip-build-rlRRV3/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/.virtualenvs/MITMf/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-rlRRV3/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p9kzFV-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/MITMf/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-rlRRV3/lxml

**Comment by HAMIDx9** [comment]
Hi,
You should install libxml2 and libxlt1 development packages.

```apt-get install libxml2-dev libxslt1-dev```

**Comment by byt3bl33d3r** [comment]
@HAMIDx9 thanks
