### ISSUE TITLE
failed with error code 1 in /tmp/pip-build-0pMajD/pypcap

### ISSUE THREAD

**Issue by abigliazzi** [byt3bl33d3r/MITMf#171]
Estaba terminando la instalacion y aparece el siguiente error ! 

(MITMf)root@kali:~/MITMf# pip install -r requirements.txt
Collecting git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-eWigK0-build
Collecting pyinotify (from -r requirements.txt (line 2))
  Downloading pyinotify-0.9.6.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 192kB/s 
Collecting pycrypto (from -r requirements.txt (line 3))
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 1.7MB/s 
Collecting pyasn1 (from -r requirements.txt (line 4))
  Downloading pyasn1-0.1.8.tar.gz (75kB)
    100% |████████████████████████████████| 77kB 246kB/s 
Collecting cryptography (from -r requirements.txt (line 5))
  Downloading cryptography-1.0.tar.gz (331kB)
    100% |████████████████████████████████| 331kB 196kB/s 
Collecting Pillow (from -r requirements.txt (line 6))
  Downloading Pillow-2.9.0.tar.gz (9.3MB)
    100% |████████████████████████████████| 9.3MB 69kB/s 
Collecting netaddr (from -r requirements.txt (line 7))
  Downloading netaddr-0.7.15-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 304kB/s 
Collecting scapy (from -r requirements.txt (line 8))
  Downloading scapy-2.3.1.zip (1.1MB)
    100% |████████████████████████████████| 1.1MB 389kB/s 
Collecting dnslib (from -r requirements.txt (line 9))
  Downloading dnslib-0.9.4.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 777kB/s 
Collecting Twisted (from -r requirements.txt (line 10))
  Downloading Twisted-15.3.0.tar.bz2 (4.4MB)
    100% |████████████████████████████████| 4.4MB 139kB/s 
Collecting lxml (from -r requirements.txt (line 11))
  Downloading lxml-3.4.4.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 173kB/s 
Collecting pefile (from -r requirements.txt (line 12))
  Downloading pefile-1.2.10-114.tar.gz (49kB)
    100% |████████████████████████████████| 49kB 542kB/s 
Collecting ipy (from -r requirements.txt (line 13))
  Downloading IPy-0.83.tar.gz
Collecting user-agents (from -r requirements.txt (line 14))
  Downloading user-agents-0.3.2.tar.gz
Collecting pyopenssl (from -r requirements.txt (line 15))
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
    100% |████████████████████████████████| 106kB 1.3MB/s 
Collecting service-identity (from -r requirements.txt (line 16))
  Downloading service_identity-14.0.0-py2.py3-none-any.whl
Collecting configobj (from -r requirements.txt (line 17))
  Downloading configobj-5.0.6.tar.gz
Collecting Flask (from -r requirements.txt (line 18))
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 544kB 419kB/s 
Collecting dnspython (from -r requirements.txt (line 19))
  Downloading dnspython-1.12.0.zip (230kB)
    100% |████████████████████████████████| 233kB 398kB/s 
Collecting beautifulsoup4 (from -r requirements.txt (line 20))
  Downloading beautifulsoup4-4.4.0-py2-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 573kB/s 
Collecting capstone (from -r requirements.txt (line 21))
  Downloading capstone-3.0.4.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 168kB/s 
Collecting python-magic (from -r requirements.txt (line 22))
  Downloading python-magic-0.4.6.tar.gz
Collecting msgpack-python (from -r requirements.txt (line 23))
  Downloading msgpack-python-0.4.6.tar.gz (116kB)
    100% |████████████████████████████████| 118kB 432kB/s 
Collecting requests (from -r requirements.txt (line 24))
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 399kB/s 
Collecting pypcap (from -r requirements.txt (line 25))
  Downloading pypcap-1.1.3.tar.gz (44kB)
    100% |████████████████████████████████| 45kB 754kB/s 
    Complete output from command python setup.py egg_info:
    pcap.h not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0pMajD/pypcap
(MITMf)root@kali:~/MITMf# python mitmf.py -i wlan0 --spoof --arp --hsts --gateway 192.168.0.1
Traceback (most recent call last):
  File "mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/root/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/root/MITMf/core/configwatcher.py", line 20, in <module>
    import pyinotify
ImportError: No module named pyinotify
(MITMf)root@kali:~/MITMf# 

Ayuda por favor ! 

Desde ya muchas gracias

**Comment by HAMIDx9** [comment]
Hi, 
As you can see, pip command showed some error. (to be more specific you should install pcap library).
Try to fix all the dependency, and then try to run pip, so you can run MITMf.

**Comment by byt3bl33d3r** [comment]
@abigliazzi you didn't install the ```libpcap0.8-dev``` package, please follow the installation instructions here https://github.com/byt3bl33d3r/MITMf/wiki/Installation

**Comment by neelshah16** [comment]
Try

`easy_install -U setuptools`
