### ISSUE TITLE
basic_tests

### ISSUE THREAD

**Issue by DevilDendy** [byt3bl33d3r/MITMf#174]
Hi I wanted to know if I have done some installation error or
if it does not work basic_test
I have a problem when I try to perform the test
the program gives me the following error
EEE.E
======================================================================
ERROR: test_DNSChef (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 18, in test_DNSChef
    from core.logger import logger
ImportError: No module named core.logger

======================================================================
ERROR: test_NetCreds (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 24, in test_NetCreds
    from core.logger import logger
ImportError: No module named core.logger

======================================================================
ERROR: test_SSLStrip_Proxy (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 37, in test_SSLStrip_Proxy
    from core.sslstrip.CookieCleaner import CookieCleaner
ImportError: No module named core.sslstrip.CookieCleaner

======================================================================
ERROR: test_logger (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 12, in test_logger
    from core.logger import logger
ImportError: No module named core.logger

----------------------------------------------------------------------
Ran 5 tests in 0.125s

FAILED (errors=4)
 I am using kali sana (64-bit) and I followed step by step the installation wiki using mkvirtualenv to install the missing libraries version mitmf is the last downloaded today
thanks in advance for any response

**Comment by byt3bl33d3r** [comment]
@DevilDendy I really don't understand what you're trying to do here :/ , if you want to run mitmf you should be running mitmf.py and not the tests.

**Comment by anouar1er** [comment]
same problem :( are u resolve that ?

**Comment by kishorpatel819** [comment]
it is not sniffing any data not working keylogger. not getting passowrds. not able inject url,image .not able to deface.getting.when i opened basictests it gives 4 error. what to do. how can i fix it.
if you found any solution please email me kishorpatelmotoe@gmail.com.



ERROR: test_DNSChef (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 18, in test_DNSChef
    from core.logger import logger
ImportError: No module named core.logger

======================================================================
ERROR: test_NetCreds (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 24, in test_NetCreds
    from core.logger import logger
ImportError: No module named core.logger

======================================================================
ERROR: test_SSLStrip_Proxy (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 37, in test_SSLStrip_Proxy
    from core.sslstrip.CookieCleaner import CookieCleaner
ImportError: No module named core.sslstrip.CookieCleaner

======================================================================
ERROR: test_logger (__main__.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basic_tests.py", line 12, in test_logger
    from core.logger import logger
ImportError: No module named core.logger

----------------------------------------------------------------------
Ran 5 tests in 0.417s
