### ISSUE TITLE
new installation doesnt work

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#175]
did a clean install after reading new wiki entry and get this
(MITMf)root@NAS2:~/MITMf# python mitmf.py --help
Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/MITMf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
  File "/root/MITMf/libs/bdfactory/pebin.py", line 49, in <module>
    from intel.intelCore import intelCore
  File "/root/MITMf/libs/bdfactory/intel/intelCore.py", line 38, in <module>
    from capstone import *
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

**Comment by byt3bl33d3r** [comment]
as the error says, you don't have capstone installed

**Comment by WiredLife** [comment]
How can it be? I made it according to instructions in wiki

**Comment by byt3bl33d3r** [comment]
I've updated the install instructions with the required library

**Comment by WiredLife** [comment]
can you please add some info how to use and update after installation?
is this right that i must do a "mkvirtualenv MITMf -p /usr/bin/python2.7" everytime before i "cd MITMf" and use it?
when i do "cd MITMf" without it, there will be errors after starting

to update do "git pull" in MITMf folder?

**Comment by byt3bl33d3r** [comment]
@WiredLife please read the virtualenvwrapper documentation here https://virtualenvwrapper.readthedocs.org/en/latest/

**Comment by leomatias** [comment]
hi, I got the same error as WiredLife, capstone is installed and it is listed in the requirements.txt file, could you please help me? I tried to install it on 3 different Linux versions, including Ubuntu and Kali

**Comment by xaumet** [comment]
# This works for me  on Ubuntu 15.10
 
#  Look for the error
 uncommnet line 201 `print "Trying to load:", _lib_file` on `~/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/__init__.py `

## run 
 python mitmf.py --help 

## look for that lines
Trying to load: ~/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/capstone.dll
Trying to load: ~/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/libcapstone.so.3
**Trying to load: ~/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/libcapstone.so**
Trying to load: ~/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/libcapstone.dylib

## copy libcapstone.so
cp ~/.virtualenvs/MITMf/lib/python2.7/site-packages/capstone/libcapstone.so ~/.virtualenvs/MITMf/**local**/lib/python2.7/site-packages/capstone/
