### ISSUE TITLE
Edit your .bashrc or .zshrc file to source the virtualenvwrapper.sh script:

### ISSUE THREAD

**Issue by camcam444** [byt3bl33d3r/MITMf#176]
Do you edit the .bashrc file in root?
root@System:~# gedit .bashrc 

Also I am wondering if I did anything wrong because when im using 
root@System:~#./MITMf -i eth0 --spoof --arp --hsts --gateway --target
I am getting this 
[*] MITMf v0.9.8 - 'The Dark Side'
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online

 * Running on http://127.0.0.1:9999/

|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online
▪️

Then when I go to type on the targeted pc I get no post data on the terminal in linux.
Only thing that happens is the target pc loads a little slower and the bar under |_ SMB server online stops blinking...
Am im doing something wrong?
I am using Kali linux 2.0

**Comment by byt3bl33d3r** [comment]
@camcam444 https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug

**Comment by byt3bl33d3r** [comment]
I'll re-open the issue once you supply the information

**Comment by camcam444** [comment]
I just went to link what information am I leaveing out?

**Comment by nethunter2** [comment]
Explicitly state your gateway and target IP number
