### ISSUE TITLE
Not being able to install MITMf on Kali 2.0

### ISSUE THREAD

**Issue by destinformore** [byt3bl33d3r/MITMf#177]
Hi, I just can't set up MITMf and get it working no matter what i do. I have followed every step on installations page and also followed some stuff other guys posted and got answers to... but still nothing. I always get some errors and when i get mad enough i make fresh installation of kali on VMware and try it again... I also tried virtualenvs, but like said im noob and im not sure if im setting all this right.

Would it be possible to make step by step installation guide with all steps and comand lines needed to set everything right, so every noob could follow it (including how to preinstall all requirements)?

I made so many attempts and new kali installations on VMware that im going crazzy already over this. Can you help me out with this please?

**Comment by byt3bl33d3r** [comment]
https://github.com/byt3bl33d3r/MITMf/wiki/Installation

**Comment by destinformore** [comment]
like said above, i did follow that, but it doesnt work in kali 2.0...

**Comment by byt3bl33d3r** [comment]
@destinformore can you please paste the errors you're encountering ? FWIW just tried installing MITMf on a fresh kali 2.0 vm and worked perfectly

**Comment by byt3bl33d3r** [comment]
@destinformore also see https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug

**Comment by destinformore** [comment]
when i run this line for example:  python mitmf.py -i wlan0 --spoof --arp --hsts --gateway 192.168.1.1 --target 192.168.1.148

this is what i get:

Traceback (most recent call last):
  File "mitmf.py", line 95, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/root/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 37, in <module>
    from ServerConnection import ServerConnection
  File "/root/MITMf/core/sslstrip/ServerConnection.py", line 28, in <module>
    from user_agents import parse
  File "/usr/local/lib/python2.7/dist-packages/user_agents/__init__.py", line 3, in <module>
    from .parsers import parse
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 4, in <module>
    from ua_parser import user_agent_parser
ImportError: No module named ua_parser


I didnt report bug because i have seen many other people having similar issues and i also tried following your answers there but it didnt help...

**Comment by byt3bl33d3r** [comment]
did you run ```pip install -r requirements.txt``` ?

**Comment by byt3bl33d3r** [comment]
@destinformore also make sure you're in the virtualenv by running ```workon MITMf```

**Comment by byt3bl33d3r** [comment]
before running the pip command

**Comment by destinformore** [comment]
well all this just gets messy and i have to install kali 2.0 again...  :(

that is why i mentioned it would be nice if all steps including setting up virtualenv would be set into one place so noobs like me dont have to spend a week or two trying to get this working.

Let say you have just installed clean kali 2.0 and now you want to install MITMf on it... What exactley would be full procedure to get this working?

I know this might be a lot to ask for, but im sure many guys would be more then glad to see it done that way and avoiding all this fuss.

Thank you.

**Comment by byt3bl33d3r** [comment]
@destinformore the full procedure to get it working is in the installation guide that i linked earlier (https://github.com/byt3bl33d3r/MITMf/wiki/Installation), If you follow those instructions step by step it will work

**Comment by destinformore** [comment]
this is the part i dont quite understand:

Edit your .bashrc or .zshrc file to source the virtualenvwrapper.sh script:
source /usr/bin/virtualenvwrapper.sh
The location of this script may vary depending on your Linux distro

Restart your terminal or run:
source /usr/bin/virtualenvwrapper.sh
Create your virtualenv:
mkvirtualenv MITMf -p /usr/bin/python2.7

I dont know how to edit or where it is, and it wont even install on some installs...

this is what i get:
root@kali:~# locate virtualenvwrapper.sh
root@kali:~# pip install virtualenvwrapper.sh
Downloading/unpacking virtualenvwrapper.sh
  Could not find any downloads that satisfy the requirement virtualenvwrapper.sh
Cleaning up...
No distributions at all found for virtualenvwrapper.sh
Storing debug log for failure in /root/.pip/pip.log

**Comment by destinformore** [comment]
also after installing pip install virtualenvwrapper i get path to where it should be... but as you can see there is no virtualenvwrapper.sh file there.

root@kali:~# pip install virtualenvwrapper
Requirement already satisfied (use --upgrade to upgrade): virtualenvwrapper in /usr/local/lib/python2.7/dist-packages
Cleaning up...
root@kali:~# 

root@kali:/usr/local/lib/python2.7/dist-packages# ls
clonevirtualenv.py           six.py
clonevirtualenv.pyc          six.pyc
easy-install.pth             stevedore
magic.py                     stevedore-1.7.0.dist-info
magic.pyc                    ua_parser
NetfilterQueue-0.6.egg-info  ua_parser-0.3.6.egg-info
netfilterqueue.so            user_agents
pbr                          user_agents-0.3.2.egg-info
pbr-1.6.0.dist-info          virtualenv-13.1.2.dist-info
pcap.so                      virtualenv_clone-0.2.6.egg-info
pyasn1                       virtualenv.py
pyasn1-0.1.8.egg-info        virtualenv.pyc
pyinotify-0.9.6.egg-info     virtualenv_support
pyinotify.py                 virtualenvwrapper
pyinotify.pyc                virtualenvwrapper-4.7.0.dist-info
pypcap-1.1.3.egg-info        virtualenvwrapper-4.7.0-py3.3-nspkg.pth
python_magic-0.4.6.egg-info  XSSer
six-1.9.0.dist-info          xsser-1.6.egg-info
root@kali:/usr/local/lib/python2.7/dist-packages#

**Comment by byt3bl33d3r** [comment]
@destinformore you're lacking some basic understanding of the python packaging system and virtualenvs, i suggest you google and read up on the docs, https://github.com/byt3bl33d3r/MITMf/wiki#some-assumptions

**Comment by destinformore** [comment]
yes you are right regarding that, as i stated above im complete noob to this and that is why i asked for help... 
I didnt have troubles installing any other tool i tried so far, but this one is just something i didnt manage to install and that is why i was hoping for more details.

thanks anyway

**Comment by destinformore** [comment]
also one more thing... when i open .bashrc ... does it matter where i put line "source /usr/bin/virtualenvwrapper.sh" in? Can I just add it to the end?

**Comment by destinformore** [comment]
hi again...
I have followed this: https://github.com/topikachu/python-ev3/blob/master/README.md and it looks like i have managed to get it installed without getting errors.

Now when im about to run MITMf i have to type "workon MITMf" first and i get into this mode "(MITMf)root@kali:~/MITMf#" then when i inuput command: python mitmf.py -i wlan0 --spoof --arp --hsts --gateway 192.168.1.1 --target 192.168.1.148 application starts but when i do my stuff on target machine nothing happens... MITMf doesnt give any output.

So what did i miss now?

**Comment by brunoaduarte** [comment]
I had the same problems installing the latest version of MITMf on Kali Linux v2.0.
The steps on installation instructions are confusing as they look like a default step-by-step.
Here's the correct virtualenv installation procedure for Kali 2 (taken from the python-ev3 installation instructions above):
    apt-get install virtualenv virtualenvwrapper python-setuptools python-smbus python-pil
    source /etc/bash_completion.d/virtualenvwrapper
    mkvirtualenv MITMf -p /usr/bin/python2.7
    git clone https://github.com/byt3bl33d3r/MITMf
    cd MITMf && git submodule init && git submodule update --recursive
    pip install -r requirements.txt
    python mitmf.py --help

**Comment by sudofly** [comment]
virtualenvwrapper.sh can be found in **/usr/local/bin/virtualenvwrapper.sh** on kali 2.0

**Comment by latinphoenix7** [comment]
Yes, I also found it in /usr/local/bin/virtualenvwrapper.sh  ;)

**Comment by honeyfairy** [comment]
Yes, this works:
`apt-get install virtualenv virtualenvwrapper python-setuptools python-smbus python-pil
source /etc/bash_completion.d/virtualenvwrapper
mkvirtualenv MITMf -p /usr/bin/python2.7
git clone https://github.com/byt3bl33d3r/MITMf
cd MITMf && git submodule init && git submodule update --recursive
pip install -r requirements.txt
python mitmf.py `--help``

**Comment by horllste** [comment]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wGon_D/pypcap/

what could cause tthis?

**Comment by Alexxx3030** [comment]
HELP!!!
I get the following errors when I try to install MITMF

root@kali:~/MITMf# python mitmf.py --help
Traceback (most recent call last):
  File "mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/root/MITMf/core/responder/settings.py", line 20, in <module>
    import utils
  File "/root/MITMf/core/responder/utils.py", line 24, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

**Comment by minstarmin** [comment]
Sorry byt3, but the installation guide is incredibly unreliable. If you're on Kali, simply use `apt-get install mitmf` and it should work like a charm.

**Comment by nethunter2** [comment]
No it wont

**Comment by nethunter2** [comment]
Truth is mitmf after installation requires additional package s
