### ISSUE TITLE
MITMf ARP spoofer is using broadcast when scapy can't find mac address to read destination

### ISSUE THREAD

**Issue by HAMIDx9** [byt3bl33d3r/MITMf#178]
Hi, 

Obviously this is not the MITMf issue, but i think it's better to fix the issue to have a more stable release.

As you know `scapy` on using layer 3 to send ARP request may not be able to find the mac address to reach the destination as following Warning says:
- Mac address to reach destination not found. Using broadcast.

We saw this issue as reported by other users but in an inappropriate form. So i prepared a bug report in detail so @byt3bl33d3r will decide.

these two lines 217-218 in core/poisoners/ARP.py (https://github.com/byt3bl33d3r/MITMf/blob/master/core/poisoners/ARP.py#L217) are responsible to send spoofed ARP to victim and gateway which in some cases scapy will not be able to recognize dest mac address and using broadcast in spoofing process. So besides of targets, other network devices will be spoofed and sniffed which we don't like when using specified targets.

using layer 2 to sending these requests successfully changed the situation and fixed the procedure.

Of course i think this should be an optimization property.

f8:1a:67:1a:AA:AA is my MITMf device, following arp table check is the device which is not the target (192.168.1.110).

```
$ ifconfig wlan0 | grep 'inet addr:'
          inet addr:192.168.1.104  Bcast:192.168.1.255  Mask:255.255.255.0

$ arp 192.168.1.1
Address                  HWtype  HWaddress           Flags Mask            Iface
192.168.1.1              ether   f8:1a:67:1a:AA:AA   C                     wlan0
```

sample `tcpdump` output before my commits (192.168.1.104):
```
$ sudo tcpdump -ennqti wlan0 arp -vvv
...
f8:1a:67:1a:AA:AA > ff:ff:ff:ff:ff:ff, ARP, length 42: Ethernet (len 6), IPv4 (len 4), Reply 192.168.1.1 is-at f8:1a:67:1a:AA:AA, length 28
```

Reporting bug procedure::
Full command string: `python -u mitmf.py -i wlan1 --spoof --arp --target 192.168.1.110 --gateway 192.168.1.1 --capturefiles`

Full pip freeze output:
```
Warning: cannot find svn location for distribute==0.6.24dev-r0
Flask==0.10.1
IPy==0.83
Jinja2==2.8
M2Crypto==0.21.1
MarkupSafe==0.23
NetfilterQueue==0.6
Pillow==2.9.0
PyYAML==3.11
Twisted==15.3.0
Werkzeug==0.10.4
argh==0.26.1
argparse==1.2.1
beautifulsoup4==4.4.0
capstone==3.0.4
cffi==1.1.2
characteristic==14.3.0
chardet==2.3.0
configobj==5.0.6
cryptography==1.0
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
dnslib==0.9.4
dnspython==1.12.0
enum34==1.0.4
gevent==0.13.6
greenlet==0.3.1
idna==2.0
ipaddress==1.0.14
itsdangerous==0.24
lxml==3.4.4
msgpack-python==0.4.6
netaddr==0.7.15
netifaces==0.10.4
pathtools==0.1.2
pbkdf2==1.3
pefile==1.2.10-139
psutil==2.1.1
pyOpenSSL==0.15.1
pyasn1==0.1.8
pyasn1-modules==0.0.7
pycparser==2.14
pycrypto==2.6.1
pypcap==1.1.3
requests==2.7.0
scapy==2.3.1
scapy-http==1.6
service-identity==14.0.0
six==1.9.0
ua-parser==0.3.6
urwid==1.0.1
user-agents==0.3.2
watchdog==0.8.3
wifi==0.3.4
wsgiref==0.1.2
zope.interface==4.1.2
```

OS: Ubuntu 15.04, Kali 1.1.1-rpi

If any further logs needed please let me know.

Thank you,
HAMIDx9

**Comment by HAMIDx9** [comment]
@byt3bl33d3r, if you prefer i can send a pr.

**Comment by byt3bl33d3r** [comment]
@HAMIDx9 sorry for the late response 
If you send a PR that would be best, have a hard time reproducing this

**Comment by HAMIDx9** [comment]
Hi, 
this is why i create an issue to be discussed.
Really i don't know why but sending to broadcast has been discussed before on stackoverflow. 
But this commit fix my long standing issue.
if any further info neede please let me know.

Thanks

**Comment by byt3bl33d3r** [comment]
@HAMIDx9  I can say for sure that there is no difference your method and the code that was already there: if you send the packets at L3 scapy will automatically append an Ether() layer to the ARP packets (I've confirmed this using wireshark)

So the fact that you're saying that it *only* works for you if you append that Ether() layer manually and send them at L2, is a bit perplexing: I cannot reproduce this in any way so don't really know what's going on.

That being said, I'm going to merge these changes along with some others in a few minutes, since I haven't noticed any differences (as expected, since they are the same) in functionality and effectiveness, so it might help other people who are experiencing this weird quirck

**Comment by HAMIDx9** [comment]
@byt3bl33d3r You are absolutely right, but i just saw 2 other closed issues which seem to be in the same way.
I also prepared `pip freeze` and double check the versions, and they seem to be OK.
IIRC i had some problem with scapy (current version), which ARP spoofing does not work correctly and it needed manually patching.

So i will continue review this problem to have a constant result.

Thank you again

**Comment by byt3bl33d3r** [comment]
@HAMIDx9 just pushed the changes in df608030f353ecee33736fc4ea0fb4e7de001412 ,let me know if this resolves the issue for you

Thanks again
