### ISSUE TITLE
cant see any urls after latest update

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#180]
did a completly clean install (of course the wiki instructions) after rm -fr MITMf
before this everything works except the unicode encoding in inject js stuff
now after starting i cant see any url accessed in mitmf terminal but the arp table on target seems to be poisoned

**Comment by byt3bl33d3r** [comment]
https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug

**Comment by byt3bl33d3r** [comment]
@WiredLife please read that link before submitting any more issues

**Comment by WiredLife** [comment]
so i hope its better
as you see
i browsing sites on multiple targets in the subnet but nothing shows up

**Comment by WiredLife** [comment]
https://github.com/byt3bl33d3r/MITMf/commit/e54b90aa7b36980b77c2198c0249648bdba06cba
