### ISSUE TITLE
Framework version on Kali Linux?

### ISSUE THREAD

**Issue by Duartebm** [byt3bl33d3r/MITMf#185]
Hi there.
I know Im running an outdated version of the framework, but thats as updated as it is in my Kali Linux 2, where I installed it by only typing 'apt-get install mitmf'. When is the newest version gonna be released in the repositories of Kali?

**Comment by bandwagonz** [comment]
If I'm not mistaken, the build version which Kali uses isn't something byt3 can control. The Kali devs would be the ones to include whatever build they feel is stable enough for their distro.

**Comment by byt3bl33d3r** [comment]
@Duartebm exactly what @bandwagonz said.. You'll need to file a bug report for them to update their repo version or you could just follow the installation instructions in the wiki

Closing
