### ISSUE TITLE
MITMF 

### ISSUE THREAD

**Issue by curtis5000** [byt3bl33d3r/MITMf#191]
hello everyone

I was hoping someone could help me solve a prob.

I was trying to use MITMF for the 1st time and i get the following error
=======================================
[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
|_ Inject v0.3
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online Traceback (most recent call last): 
File "./mitmf.py", line 180, in <module> from core.protocols.smb.SMBserver import SMBserver 
File "/usr/share/mitmf/core/protocols/smb/SMBserver.py", line 5, in <module> from impacket import version, smbserver, LOG 
---ImportError: cannot import name LOG ---
=======================================
i tried updating python and impacket, but i still get same result.
can you pls help with wat to do.
someone told me i need the following for MITMF
=======================================
you need for your mimtf 
git+git://github.com/kti/python-netfilterqueue
pyinotify
pycrypto
pyasn1
cryptography
Pillow
netaddr
scapy
dnslib
Twisted
lxml
pefile
ipy
user_agents
pyopenssl
service_identity
configobj
Flask
dnspython
beautifulsoup4
capstone
python-magic
msgpack-python
requests
pypcap
chardet
=======================================
what are the commands to install all those programs?

Thank you

**Comment by byt3bl33d3r** [comment]
@curtis5000 https://github.com/byt3bl33d3r/MITMf/wiki/Installation

**Comment by curtis5000** [comment]
I did all of that already, but still get the same result
