### ISSUE TITLE
Logjam implementation

### ISSUE THREAD

**Issue by hight0wer** [byt3bl33d3r/MITMf#194]
Maybe it's here already with a different name. Just for the case you didn't hear about it yet:
https://weakdh.org/

(Enhancement)

**Comment by byt3bl33d3r** [comment]
@hight0wer thanks for the suggeestion, but this attack doesn't provide immediate value to an attacker since it's just a crypto downgrade so don't really think it will happen. Also any TLS/SSL attacks are considered MITMf needs actual TLS/SSL support :P
