### ISSUE TITLE
How to use MITMf on HOST machine?

### ISSUE THREAD

**Issue by linvex** [byt3bl33d3r/MITMf#196]
It has this situation: I have a host machine and it enable DHCP service, and some client machine connect this machine(I am the router). 
I just want to hijack all the traffic and use all functions of MITMf but DON'T use ARP module.

when I use MITMf to hijack the traffic, the command "./mitmf.py -i eth1" didn't work, (eth1 is my intranet interface), I can't get any response and use any other functions. when I use "./mitmf.py -i eth1 --spoof --arp --gateway 10.10.10.1", i got all the subnet machine's traffic, the question is i don't want using ARP mode 'Cause I am the host and i needn't spoof myself.

Can somebody know how should i do?thanks!!

**Comment by byt3bl33d3r** [comment]
@linvex you should look into IPTables
