### ISSUE TITLE
AttributeError: 'DNSChef' object has no attribute 'loadRecords'

### ISSUE THREAD

**Issue by skiamakhe** [byt3bl33d3r/MITMf#197]
This is on a fully updated Kali 2.0 laptop, just installed the mitmf package and ran this command:

mitmf -i eth0 --spoof --arp --dns --gateway <gateway_IP> --target <target_IP>

I got this output:

[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
Traceback (most recent call last):
  File "./mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/usr/share/mitmf/plugins/Spoof.py", line 103, in initialize
    DNSChef.getInstance().loadRecords(self.dnscfg)
AttributeError: 'DNSChef' object has no attribute 'loadRecords'

**Comment by daw1012345** [comment]
Did you install MITMf using the kali repositories or using the tutorial on the MITMf wiki? By the Way, you forgot to include the output of "pip freeze".

**Comment by skiamakhe** [comment]
Didn't know to do that. I'll get that up when I get to work tomorrow. I installed it from the Kali repositories.

**Comment by daw1012345** [comment]
You should use the instructions from the wiki. The MITMf on kali repositories is deprecated. If you use the instructions from the wiki, you will get the newest version and it won't conflict with your kali installation because the wiki encourages you to use python virtualenv's.

**Comment by skiamakhe** [comment]
Ok. I'll give that a shot. Thanks.

**Comment by daw1012345** [comment]
No problem, happy to help :)

**Comment by skiamakhe** [comment]
Getting a different error now, likely not related to this, so I'll close this one and open a new issue.
