### ISSUE TITLE
KeyError: 'Responder'

### ISSUE THREAD

**Issue by skiamakhe** [byt3bl33d3r/MITMf#198]
Followed the instructions on the Wiki for installing mitmf on a fully patched Kali 2.0 laptop. Ran the following command and got the error below.

```
python /root/MITMf/mitmf.py -i eth0 --spoof --arp --dns --gateway [gateway_ip] --target [target_ip]

Traceback (most recent call last):
  File "/root/MITMf/mitmf.py", line 90, in <module>
    settings.Config.populate(options)
  File "/root/MITMf/core/responder/settings.py", line 72, in populate
    self.SSL_On_Off      = self.toBool(self.config['Responder']['HTTPS'])
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'Responder'
```
--log debug didn't add anything to /root/logs/mitmf.log, nor did it change the error output above. 

pip freeze output:
Warning: cannot find svn location for apsw==3.8.6-r1
BBQSQL==1.0
BeautifulSoup==3.2.1
BlindElephant==1.0
Cheetah==2.4.4
ConfigArgParse==0.9.3
Elixir==0.7.1
Flask==0.10.1
GeoIP==1.3.2
GitPython==0.3.2.RC1
IPy==0.81
Jinja2==2.7.3
M2Crypto==0.21.1
Magic-file-extensions==0.2
Mako==1.0.0
Markdown==2.5.1
MarkupSafe==0.23
MySQL-python==1.2.3
NetfilterQueue==0.6
NfSpy==1.0
PAM==0.4.2
Pillow==2.6.1
PyBluez==0.18
PyGithub==1.23.0
PyOpenGL==3.0.2
PySocks==1.5.0
PyX==0.12.1
PyYAML==3.11
Pygments==2.0.1
SOAPpy==0.12.22
SQLAlchemy==0.9.8
Twisted==14.0.2
Twisted-Conch==14.0.2
Twisted-Core==14.0.2
Twisted-Lore==14.0.2
Twisted-Mail==14.0.2
Twisted-Names==14.0.2
Twisted-News==14.0.2
Twisted-Runner==14.0.2
Twisted-Web==14.0.2
Twisted-Words==14.0.2
Werkzeug==0.9.6
XlsxWriter==0.5.2
Yapsy==1.10.423
adns-python==1.2.1
 FIXME: could not find svn URL in dependency_links for this package:
apsw==3.8.6-r1
argcomplete==0.8.1
argparse==1.2.1
async==0.6.1
beautifulsoup4==4.3.2
binwalk==2.0.0
blinker==1.3
capstone==3.0
certifi==2015.4.28
cffi==0.8.6
characteristic==0.1.0
chardet==2.3.0
chirp==0.4.0
clamd==1.0.1
cluster==1.1.1b3
colorama==0.3.2
configobj==5.0.6
configparser==3.3.0r2
cryptography==0.9.3
ctypeslib==0.5.6
d2to1==0.2.11
darts.util.lru==0.5
decorator==3.4.0
defusedxml==0.4.1
dicttoxml==1.6.6
dissy==9
distorm3==3
dnslib==0.9.4
dnspython==1.12.0
docutils==0.12
easygui==0.96
ecdsa==0.11
enum34==1.0.3
esmre==0.3.1
feedparser==5.1.3
flickrapi==1.2
funkload==1.16.1
fuse-python==0.2.1
futures==2.2.0
gevent==1.0.1
gitdb==0.5.4
greenlet==0.4.2
guess-language==0.2
halberd==0.2.4
hpack==1.1.0
html2text==2015.6.21
html5lib==0.999
httplib2==0.9
idna==2.0
impacket==0.9.13
ipaddress==1.0.14
itsdangerous==0.24
jsonpickle==0.8.0
jsonrpclib==0.1.3
keepnote==0.7.8
killerbee==1.0
lxml==3.4.0
matplotlib==1.4.2
mechanize==0.2.5
mercurial==3.1.2
metaconfig==0.1.4a1
mitmproxy==0.13
mock==1.0.1
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
netaddr==0.7.12
netlib==0.13.1
networkx==1.9
nltk==3.0.0
nose==1.3.4
numpy==1.8.2
oauth==1.0.1
openpyxl==1.7.0
paramiko==1.15.1
passlib==1.6.1
pbr==1.8.0
pcapy==0.10.8
pdfminer==20140328
pefile==1.2.9.1
pexpect==3.2
phply==0.9.1
ply==3.4
prettytable==0.7.2
psutil==2.1.1
psycopg2==2.5.4
pyOpenSSL==0.15.1
pyPdf==1.13
pyasn1==0.1.7
pyasn1-modules==0.0.5
pybloomfiltermmap==0.3.14
pycparser==2.10
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pycups==1.9.63
pycurl==7.19.5
pydns==2.3.6
pygobject==3.14.0
pygraphviz==1.3rc2
pyinotify==0.9.4
pymssql==1.0.2
pyparsing==2.0.3
pypcap==1.1.4
pyperclip==1.5.11
pyqtgraph==0.0.0
pyregfi==99.99.99.277
pyrit==0.4.0
pyrtlsdr==0.1.1
pyscard==1.6.14
pyserial==2.6
pysmbc==1.0.15.3
pysnmp==4.2.5
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
pysqlite==2.6.3
python-Levenshtein==0.11.2
python-apt==0.9.3.11
python-dateutil==2.2
python-debian==0.1.27
python-debianbts==1.11
python-magic==0.4.6
python-ntlm==1.0.1
pytidylib==0.2.1
pytz==2012c
pyusb==1.0.0a3
pyxdg==0.25
pyzmq==14.4.0
reportbug==6.6.3
requests==2.7.0
rfidiot==1.0
roman==2.0.0
ruamel.ordereddict==0.4.8
scapy==2.2.0
scipy==0.14.0
service-identity==1.0.0
simplejson==3.6.5
six==1.9.0
slowaes==0.1a1
smmap==0.8.2
stevedore==1.8.0
stopit==1.1.0
tblib==0.2.0
tornado==4.2
tweepy==2.3
uTidylib==0.2
ua-parser==0.4.1
urllib3==1.10.4
urwid==1.3.0
user-agents==1.0.1
virtualenv==13.1.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
volatility==2.4
vulndb==0.0.19
wapiti==2.3.0
webunit==1.3.10
wheel==0.24.0
wsgiref==0.1.2
wstools==0.4.3
wxPython==3.0.1.1
wxPython-common==3.0.1.1
xdot==0.5
xsser==1.6
yara-python==3.1
zenmap==6.49BETA4
zim==0.62
zope.interface==4.1.1

**Comment by daw1012345** [comment]
Are you sure that you are starting MITMf inside python virtualenv?

**Comment by daw1012345** [comment]
Besides, "Twisted" and other python packages on your system your system. You should run "pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U" to update all of the python packages, or "pip install -u [PACKAGE NAME]" to update a single python package.

**Comment by skiamakhe** [comment]
Ok, pip freeze --local gives a much different output than pip freeze by itself:

NetfilterQueue==0.6
dnslib==0.9.4
pbr==1.8.0
pypcap==1.1.4
python-magic==0.4.6
six==1.9.0
stevedore==1.8.0
ua-parser==0.4.1
user-agents==1.0.1
virtualenv==13.1.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
xsser==1.6

That's it.

I don't know about the python virtualenv. Researching how to check that...

**Comment by skiamakhe** [comment]
I'm not entirely sure what happened, but it is working now. Here are things that changed from my last post:

1. I tried the upgrade shell command daw1012345 listed, though everything came back as already up to date
2. I installed tor and changed iptables rules to funnel all traffic through tor to get around the fact that I couldn't do the pip install from behind my corporate firewall. (first time around I used my phone as a hotspot to do the pip install)
3. I repeated these commands from the installation:
```
cd MITMf && git submodule init && git submodule update --recursive
pip install -r requirements.txt
```
4. I removed the firewall rules so that I could access my corporate network normally again.
5. I rebooted the system for an unrelated reason
6. I tried running mitmf.py again with the same error.
7. I realized I wasn't in the MITMf directory, cd'ed into it, and then ran the command again, no error.

I'm sure that I tried the command from within the MITMf directory before as that's the natural progression of the installation instructions. But, it is working now. Who knows. Maybe my Windows workstation temporarily infected my Linux box with Microsoft Rot.

**Comment by skiamakhe** [comment]
I have another issue to ask about, but it doesn't really qualify as an "issue" per se. Is there a community support forum somewhere?

**Comment by byt3bl33d3r** [comment]
@skiamakhe Hi, If you have any questions you can email me directly at byt3bl33d3r@gmail.com

**Comment by llazzaro** [comment]
I had this issue.
To reproduce it, execute mitmf.py outside the MITMf directory.
