### ISSUE TITLE
Mitmf installation and running. 

### ISSUE THREAD

**Issue by dorongal1** [byt3bl33d3r/MITMf#208]
Hello, i'm pretty new at linux OS so i will be thankful your explanation will be like to a beginner.
So, I had the old ver of MITMF and it all worked pretty well.
But, i just updated MITMF and when im run it i get the following errors : 
"  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory
"
 Thank U !

**Comment by GeeksSpeak** [comment]
Hi,

Please use installation wiki at https://github.com/byt3bl33d3r/MITMf/wiki/Installation.
you should clone all submodules too.

Please close this issue as it's not.

**Comment by dorongal1** [comment]
"
    Edit your .bashrc or .zshrc file to source the virtualenvwrapper.sh script:

source /usr/bin/virtualenvwrapper.sh
    "

I dont really understand wich file to edit and where to add that source path.

can u guide me ?

**Comment by n1nj4sec** [comment]
why don't you search ".bashrc" on google, click on the first link and read ?

**Comment by dorongal1** [comment]
Belive me that i did it before i came here

**Comment by byt3bl33d3r** [comment]
@dorongal1 https://github.com/byt3bl33d3r/MITMf/wiki#some-assumptions
