### ISSUE TITLE
Cannot start mitmf.py/failed to load dynamic library

### ISSUE THREAD

**Issue by sandman6578** [byt3bl33d3r/MITMf#214]
Hello,

I´ve installed a completly fresh Debian 8.2.0 on an VMware Workstation.
My problem is...
I have installed all dependencies/requirements.
But when i start mitmf.py in a virtualenv i become this.
![unbenannt](https://cloud.githubusercontent.com/assets/10436946/10697112/8a033cda-79aa-11e5-9179-78bc83b300c6.PNG)

PIP freeze:
![unbenannt1](https://cloud.githubusercontent.com/assets/10436946/10697152/c834075a-79aa-11e5-9f27-121817c44b64.PNG)
Thanks in Advance

**Comment by byt3bl33d3r** [comment]
@sandman6578 Hi, you seem to be missing the Capstone library just do a ```apt-get install libcapstone2```

**Comment by sandman6578** [comment]
Question...
is this a failure in your Installation instructions
libcapstone3 did you mean libcapstone2??
Because libcapstone3 is in no Repo of Debian

**Comment by byt3bl33d3r** [comment]
libcapstone3 is in Kali's repos IIRC, you're correct that it isn't debian's repos but I'd expect people to be able to figure that out ;)

**Comment by sandman6578** [comment]
with which Distribution does MITMf works best?

**Comment by byt3bl33d3r** [comment]
@sandman6578 if I had to choose I would say Arch Linux

**Comment by sandman6578** [comment]
@byt3bl33d3r if i copy paste your first instruction for installing your frameowork on a fresh Kali distro i became this.

root@kali:~# apt-get install python-dev python-setuptools libpcap0.8-dev libnetfilter-queue-dev libssl-dev libjpeg-dev libxml2-dev libxslt1-dev libcapstone3 libcapstone-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Package libjpeg-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libxslt1-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libpcap0.8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpcap0.8

E: Package 'libpcap0.8-dev' has no installation candidate
E: Paket libnetfilter-queue-dev kann nicht gefunden werden.
E: Package 'libjpeg-dev' has no installation candidate
E: Package 'libxslt1-dev' has no installation candidate
E: Paket libcapstone-dev kann nicht gefunden werden.

Where did i find these?

because i wanna use Kali

**Comment by sandman6578** [comment]
ok mitmf works now for me.

but when i type in this command.
![command](https://cloud.githubusercontent.com/assets/10436946/10717260/cc1f3086-7b8c-11e5-9731-3489accf317b.PNG)

and on the victims computer i go to facebook.com its though nevertheless https

pip freeze:

![freeze](https://cloud.githubusercontent.com/assets/10436946/10717268/1e3549aa-7b8d-11e5-8dde-d64b3b6dab51.PNG)
![dns response](https://cloud.githubusercontent.com/assets/10436946/10717274/520aa0a4-7b8d-11e5-9cf9-d7c1582d8d8c.PNG)

**Comment by sandman6578** [comment]
@byt3bl33d3r

**Comment by byt3bl33d3r** [comment]
Its a partial bypass , it wont work on every website
