### ISSUE TITLE
MITMF problem while connecting msfrpc.

### ISSUE THREAD

**Issue by ortholinux** [byt3bl33d3r/MITMf#217]
Hello,
i used filepwn in mitmf, it first gave error somewhat like cannot connect to msfrpc as i had not started the msfrpcd and neither configured the mitmf.conf file, so i configured the file put a password and also started the msfrpcd with the interface ip the port and the password checked packets with the sniffer they were going very well on the right interface to the right port all seemed well but the mitmf gave me "connection reset by peer" error:

root@kali:~# mitmf -i eth0 --spoof --arp --gateway 192.168.1.1 --targets 192.168.1.7 --filepwn

[*] MITMf v0.9.7 online... initializing plugins
|_ FilePwn v0.3
|  |_ BDFProxy v0.3.2 online
[Msfrpc] Error connecting to Metasploit: ('Connection aborted.', error(104, 'Connection reset by peer'))

any help please?

**Comment by mw3demo** [comment]
msfconsole
    load msgrpc Pass=abc123

**Comment by byt3bl33d3r** [comment]
@ortholinux ^^
