### ISSUE TITLE
Cannot capture any HTTPS traffic

### ISSUE THREAD

**Issue by crack3r85** [byt3bl33d3r/MITMf#233]
Dear byt3bl33d3r,

I have just installed MITMf on KL 2.0 perfectly. But I have an issue that I cannot capture any HTTPS traffic when I use para --hsts while other traffics are ok. Do you have any suggest for this case or SslStrip is no longer working?

Many thanks!

**Comment by fnzv** [comment]
I'm interested also in this feature....i suppose that "partial HSTS bypass"  means only some browsers could work in this mitm?

**Comment by byt3bl33d3r** [comment]
@fnzv you would be correct sir/madam
