### ISSUE TITLE
MITMf Filepwn Error in some situation

### ISSUE THREAD

**Issue by DKingCN** [byt3bl33d3r/MITMf#236]
At first I do the followings to do Filepwn with bdfproxy
1.BDFproxy  configured as a transparent proxy (/etc/bdfproxy/bdfproxy.cfg). Listen to specified port 2233
2.Setup an AP and redirect traffic go through bdfproxy . Iptables are

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A PREROUTING -p udp -j DNAT --to $gatewayip
iptables -P FORWARD ACCEPT
iptables -A FORWARD --in-interface at0 -j ACCEPT
iptables -t nat -A PREROUTING -i at0 -p tcp --dport 80 -j DNAT --to ${ip}:${bdfproxy}
iptables -t nat -A POSTROUTING --out-interface $if -j MASQUERADE
it works good.Filepwn is well functioned.

But in MITMf -l mode , the proxy captured the traffic but failed to do the patch.
[ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 116, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/filepwn.py", line 614, in response
    content_header = response.headers['content-type']
  File "/usr/lib/python2.7/dist-packages/twisted/web/http_headers.py", line 50, in __getitem__
    raise KeyError(key)
KeyError: 'content-type'

No idea why.
Maybe the proxy type i guess?
maybe some kind of Improvement can be done
thank you.

**Comment by DKingCN** [comment]
I have been writing a script to combine some functions with airbase-ng,mitmf and iptables , to setup a ap
If mitmf dont work well in filepwn , I guess I can only use less functioned bdfproxy here…

**Comment by HAMIDx9** [comment]
Hi, Try catch approach should be done on [L#614](https://github.com/byt3bl33d3r/MITMf/blob/master/plugins/filepwn.py#L614) too. You can do it yourself now. I will try to send a pr as soon as possible. 

Also Please consider [Bug reporting style](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) for future activities.

Thanks.

**Comment by DKingCN** [comment]
yes.got it.
Thanks for your devotion.

**Comment by byt3bl33d3r** [comment]
@DKingCN awesome to see you figured this out!

**Comment by DKingCN** [comment]
Well , I have to say, the problem is actually not solved.

The sys environments are all good so no need to be pasted here. 
The description below is under traffic redirecting situation.

As @HAMIDx9  said , I tried to add `try: except:` to [filepwn.py #L614](https://github.com/byt3bl33d3r/MITMf/blob/master/plugins/filepwn.py#L614) of filepwn.py , although there were no more exceptions threw out, the FilePatching work was still not working, giving error msg of "Patching failed"
I also tried to give a default value to content-type in `except` line , which didn't work too.

Besides, I have made many comparisons between the two situations : 
1.browser proxy set to mitmf-listener
2.redirecting to listener(iptables redirects TCP:80 to mitmfproxy)	[see PCAP](107.170.228.218/method2.pcapng)

In my observation of the traffic , i can see no difference between the same request of an exe file. However, only the first succeed.

Please contact me if any more information are needed.

**Comment by DKingCN** [comment]
`pip freeze`

Warning: cannot find svn location for chirp===daily-20160110
BBQSQL==1.0
BeautifulSoup==3.2.1
BlindElephant==1.0
Cheetah==2.4.4
ConfigArgParse==0.10.0
DenyHosts==2.6
Elixir==0.7.1
Flask==0.10.1
FormEncode==1.2.6
GeoIP==1.3.2
GitPython==1.0.1
IPy==0.83
Jinja2==2.8
M2Crypto==0.22.6rc4
Magic-file-extensions==0.2
Mako==1.0.3
Markdown==2.6.5
MarkupSafe==0.23
NfSpy==1.0
PAM==0.4.2
Paste==1.7.5.1
PasteDeploy==1.5.2
PasteScript==1.7.5
Pillow==3.1.0
PyBluez==0.18
PyGithub==1.23.0
PyJWT==1.3.0
PyOpenGL==3.0.2
PyPDF2==1.25.1
PySocks==1.5.0
PyX==0.12.1
PyYAML==3.11
Pygments==2.1
SOAPpy==0.12.22
SQLAlchemy==1.0.11
Tempita==0.5.2
Twisted==15.5.0
Werkzeug==0.10.4
Whoosh==2.7.0
XlsxWriter==0.7.3
Yapsy==1.11.223
adns-python==1.2.1
alembic==0.8.2.dev0
anyjson==0.3.3
apsw==3.8.11.1.post1
argcomplete==0.8.1
argh==0.26.1
argparse==1.2.1
backports.ssl-match-hostname==3.4.0.2
basemap==1.0.7
beautifulsoup4==4.4.1
binwalk==2.1.1
blinker==1.3
boltons==15.1.1
capstone==3.0.4
certifi==2015.11.20
characteristic==14.3.0
chardet==2.3.0
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20160110
clamd==1.0.1
click==6.2
cluster==1.1.1b3
colorama==0.3.3
configobj==5.0.6
configparser==3.3.0.post2
construct==2.5.2
couchdbkit==0.6.5
creepy==1.2
cryptography==1.2.1
ctypeslib==0.5.6
cycler==0.9.0
d2to1==0.2.12
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.0.6
defusedxml==0.4.1
dicttoxml==1.6.6
dissy==9
distlib==0.2.1
distorm3==3.3.0
dnslib==0.9.6
dnspython==1.12.0
docutils==0.12
dominate==2.1.5
easygui==0.96
ecdsa==0.13
enum34==1.1.2
esmre==0.3.1
feedparser==5.1.3
flickrapi==2.1.2
funkload==1.16.1
fuse-python==0.2.1
futures==3.0.3
geoip2==2.2.0
geojson==1.3.1
gevent==1.0.1
gitdb==0.6.4
google-api-python-client==1.4.2
greenlet==0.4.9
guess-language-spirit==0.5.2
halberd==0.2.4
hpack==2.0.1
html2text==2016.1.8
html5lib==0.999
http-parser==0.8.3
httplib2==0.9.1
httpretty==0.8.6
icalendar==3.8
idna==2.0
impacket==0.9.13
ipaddr==2.1.11
ipaddress==1.0.16
ipython==2.4.1
itsdangerous==0.24
jdcal==1.0
jsonpickle==0.9.2
jsonrpclib==0.1.3
keepnote==0.7.8
killerbee==1.0
lxml==3.5.0
matplotlib==1.5.1rc1
maxminddb==1.2.0
mechanize==0.2.5
mercurial==3.5.2
metaconfig==0.1.4a1
mitmproxy==0.15
mockito==0.5.2
msgpack-python==0.4.6
mysqlclient==1.3.7
nassl==0.12
ndg-httpsclient==0.4.0
netaddr==0.7.18
netlib==0.15
nltk==3.1
numpy==1.10.4
oauth2client==1.4.12
oauthlib==1.0.3
olefile==0.42.1
openpyxl==2.3.0
paramiko==1.15.3
passlib==1.6.5
pathtools==0.1.2
pcapy==0.10.8
pdfminer==20140328
pefile==1.2.10.post139
pexpect==4.0.1
phply==0.9.1
ply==3.7
prettytable==0.7.2
psutil==3.4.1
psycopg2==2.6.1
ptyprocess==0.5
py==1.4.31
pyOpenSSL==0.15.1
pyPdf==1.13
pyasn1==0.1.9
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.14
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pycurl==7.21.5
pydns==2.3.6
pygobject==3.18.2
pyinotify==0.9.5
pylibemu==0.3.3
pyliblzma==0.5.3
pymssql==1.0.2
pyotp==2.0.1
pyparsing==2.0.3
pyperclip==1.5.11
pyqtgraph==0.9.10
pyregfi==99.99.99.277
pyrit==0.4.0
pyscard==1.9.1
pyserial==3.0.1
pysnmp==4.2.5
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
pysqlite==2.7.0
pytest==2.8.5
python-Levenshtein==0.12.0
python-apt==1.1.0b1
python-dateutil==2.4.2
python-debian==0.1.27
python-debianbts==2.6.0
python-editor==0.4
python-instagram==1.3.2
python-lzo==1.8
python-magic==0.4.11
python-ntlm==1.1.0
python-openid==2.2.5
pytidylib==0.2.1
pytz==2015.7
pyusb==1.0.0b2
pyxdg==0.25
reportbug==6.6.6
requests==2.9.1
requests-oauthlib==0.4.0
requests-toolbelt==0.5.1
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
rsa==3.2.3
ruamel.ordereddict==0.4.9
scapy==2.2.0
scgi==1.13
scipy==0.17.0
service-identity==14.0.0
shadowsocks==2.8.2
simplegeneric==0.8.1
simplejson==3.8.1
six==1.10.0
slowaes==0.1a1
smmap==0.9.0
smoke-zephyr==1.0.2
socketpool==0.5.3
stopit==1.1.0
tblib==1.2.0
termcolor==1.1.0
tornado==4.2.1
tweepy==3.3.0
tzlocal==1.2
uTidylib==0.2
ua-parser==0.7.0
uritemplate==0.6
urllib3==1.13.1
urwid==1.3.1
user-agents==1.0.1
vinetto==0.7b0
volatility==2.5
vulndb==0.0.19
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
webunit==1.3.10
wfuzz==0.0.0
wheel==0.26.0
wsgiref==0.1.2
wstools==0.4.3
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.5
xsser==1.6
yara-python==3.4.0
zenmap==7.1
zim==0.65
zope.interface==4.1.3
