### ISSUE TITLE
Getting this Error !!! help me out 

### ISSUE THREAD

**Issue by vinod3070** [byt3bl33d3r/MITMf#238]
███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
|  |_ ARPWatch online
Traceback (most recent call last):
  File "./mitmf.py", line 154, in <module>
    reactor.listenTCP(args.listen, strippingFactory)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 979, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:10000: [Errno 98] Address already in use.

**Comment by DKingCN** [comment]
`pgrep mitmf | xargs kill `

**Comment by vinod3070** [comment]
Not Working bro , still getting the same error !!

**Comment by HAMIDx9** [comment]
It seems you are not using the latest version. Please consider [Installation page](https://github.com/byt3bl33d3r/MITMf/wiki/Installation). Comment here if any problem then.

**Comment by vinod3070** [comment]
Running Python 2.7 , still the same error !! please help me out :(

**Comment by HAMIDx9** [comment]
Please verify you are using MITMf v0.9.8 'Dark Side' otherwise you should try installation page.

**Comment by vinod3070** [comment]
yes am using  MITMf v0.9.8 'Dark Side' , but why only me ??

**Comment by byt3bl33d3r** [comment]
@vinod3070  sooo pretty sure 0.97 != 0.98 just install the latest version and you should be golden.
(also obligatory youtube link for not reading the error message https://www.youtube.com/watch?v=vh3tuL_DVsE)

**Comment by bharavi15** [comment]
Try these commands.
`lsof -t -i:10000`
to get PID
Then, kill -9 <PID>
Worked for me
