### ISSUE TITLE
MITMF running but wont intercept anything

### ISSUE THREAD

**Issue by kofteror** [byt3bl33d3r/MITMf#239]
Hey there..
I'm running MITMF on a few  victim machine( windows 7 running chrome/firefox and my iphone 6 running safari)  
I type the comman command : python mitmf.py -i wlan0 --spoof --arp --hsts --target 192.168.1.10 --gateway 192.168.1.1 and it's started perfect and load all the stuff ... but it wont intercept anything not regular site request not https ( even when i'm adding --hsts plugin) .. any thought? Thanks
Kofteror

**Comment by HAMIDx9** [comment]
Hi,

What you mean by 
> but it wont intercept anything not regular site request not https 
?
Please be more specific and explain your issue more. Also note `hsts` stands for `partial hsts` and is not fully usable on hardened sites. but if it cannot log anything you should check arpspoofer whether it works or not.

**Comment by kofteror** [comment]
Hey ... I don't know.
Sometimes it's works and sometimes it's does not..
Do i missing anything?

**Comment by HAMIDx9** [comment]
On your Windows target run `arp -a` to find out whether arpspoofer works or not. And again please explain your problem in detail. since we don't know what `doesn't work` mean in your case.

**Comment by byt3bl33d3r** [comment]
@kofteror https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug
