### ISSUE TITLE
DNS PORT in use

### ISSUE THREAD

**Issue by lukiboy** [byt3bl33d3r/MITMf#240]
Hey guys,

when i try to start a mitmf attack, i get an error that the dns server is unable to start because port 53 is already in use. Can you help me please?

This is the error which mitmf gives out:

[DNS] Unable to start DNS server on port 53: port already in use

thanks

**Comment by HAMIDx9** [comment]
Hi, 

I can imagine some programs like `dnsmasq` are using this port. if you have netstat with following options, run `netstat -lnup` and you can see which program is using this port. but the best choice at the moment is changing DNS port in `config/mitmf.conf` to other free ports.

**Comment by lukiboy** [comment]
Thanks for your quick answer,

Can you give me an alternative to port 53? I don't know which ports are availiable...

**Comment by HAMIDx9** [comment]
try a free port like 5353 or ... on your device. `MITMf` takes care of that in its internal.

**Comment by byt3bl33d3r** [comment]
https://www.youtube.com/watch?v=vh3tuL_DVsE

**Comment by TurtleDev05** [comment]
Same problem please help me
