### ISSUE TITLE
Missing libmagic?

### ISSUE THREAD

**Issue by thedp** [byt3bl33d3r/MITMf#244]
I'm trying to install MITMf on Kali that's running on my old Android device: 
`Linux localhost 3.0.31-1211311 #3 SMP PREEMPT Thu Jun 13 14:34:54 EEST 2013 armv7l GNU/Linux`

However, I get this error:

```
(MITMf)android@localhost:~/MITMf$ ./mitmf.py --help
Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/home/android/MITMf/plugins/filepwn.py", line 70, in <module>
    import magic
  File "/home/android/.virtualenvs/MITMf/local/lib/python2.7/site-packages/magic.py", line 169, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

I tried to install `libmagic` but it seems to be already installed:
```
(MITMf)android@localhost:~/MITMf$ pip install libmagic
Requirement already satisfied (use --upgrade to upgrade): libmagic in /home/android/.virtualenvs/MITMf/lib/python2.7/site-packages
```

Any suggestions how to solve this issue?
Thanks.

**Comment by HAMIDx9** [comment]
Hi, 

`libmagic` is a wrapper for magic `C` library. so it should be able to find the proper magic library.

for now please install `python-magic` using pip:
`pip install python-magic`
and check if it helps.
also you can pass `-U` parameter to `pip` to force package upgrading.

**Comment by thedp** [comment]
python-magic is already installed.
Anything else?

**Comment by HAMIDx9** [comment]
based on following `magic.py` code : 
`dll = ctypes.util.find_library('magic') or ctypes.util.find_library('magic1') or ctypes.util.find_library('cygmagic-1')` something like `libmagic.so.1` should be loaded in a *nix environment. Use following command to find if there is any :
`find /usr/lib/ -iname "*magic*" ` 
and use `file` command to see if it is a proper `ARM` library. ( you can use other paths as well)

**Comment by thedp** [comment]
At first `find /usr/lib/ -iname "*magic*" ` didn't return any results.
I then notice `file` is missing so I've installed it `sudo apt-get install file`
And then `find /usr/lib/ -iname "*magic*" ` worked:
```
(MITMf)android@localhost:~/MITMf$ find /usr/lib/ -iname "*magic*"
/usr/lib/arm-linux-gnueabihf/libmagic.so.1
/usr/lib/arm-linux-gnueabihf/libmagic.so.1.0.0
```

However, now when I try to run `./mitmf --help` gives me this:
```
(MITMf)android@localhost:~/MITMf$ ./mitmf.py --help
Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/home/android/MITMf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
  File "/home/android/MITMf/libs/bdfactory/pebin.py", line 49, in <module>
    from intel.intelCore import intelCore
  File "/home/android/MITMf/libs/bdfactory/intel/intelCore.py", line 38, in <module>
    from capstone import *
  File "/home/android/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/__init__.py", line 286, in <module>
    ctypes.c_uint64, ctypes.c_size_t, ctypes.POINTER(ctypes.POINTER(_cs_insn)))
  File "/home/android/.virtualenvs/MITMf/local/lib/python2.7/site-packages/capstone/__init__.py", line 281, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libcapstone.so: undefined symbol: cs_disasm
```

So now I'm tracing back the whole installation process and notice that `libcapstone3` was not installed since it couldn't be found by `sudo apt-get install libcapstone3`.
I tried `sudo apt-get update` but still not found. 

What do you think?

Thanks.

**Comment by thedp** [comment]
At first find /usr/lib/ -iname "*magic*" didn't return any results.
I then notice file is missing so I've installed it sudo apt-get install file
And then find /usr/lib/ -iname "*magic*" worked:

(MITMf)android@localhost:~/MITMf$ find /usr/lib/ -iname "*magic*"
/usr/lib/arm-linux-gnueabihf/libmagic.so.1
/usr/lib/arm-linux-gnueabihf/libmagic.so.1.0.0
However, now when I try to run mitmf it gives me this:
```
(MITMf)android@localhost:~/MITMf$ ./mitmf.py --help

 __  __   ___   .--.          __  __   ___
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._|
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |
                       |  '.'                   | |
                       |   /                    | |
                       `'-'                     |_|

[-] The derp is strong with this one
```

What do you think?

Thanks.

**Comment by HAMIDx9** [comment]
`MITMf` requires root privilege to run properly. then try using Installation Wiki page to have all modules installed.

**Comment by HAMIDx9** [comment]
@byt3bl33d3r although most of the Gnu/Linux distros have `file` pre-installed. but It's a good move to add `file` to wiki packages installation.

**Comment by thedp** [comment]
sudo it is. I've reinstalled `pip install -r requirements.txt` under root this time and everything started to work like a charm :)

Thanks Hamid.

**Comment by byt3bl33d3r** [comment]
@HAMIDx9 Will do, thanks again @HAMIDx9
