### ISSUE TITLE
Mitmf newly installed works correctly after the first use returns this error

### ISSUE THREAD

**Issue by DevilDendy** [byt3bl33d3r/MITMf#245]
File "mitmf.py", line 138, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/root/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 25, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
 
I do not know what produces the error I installed everything correctly following the wiki
to use it every time I have to reinstall the program I installed all the dependencies of kali Linux 2.0 64-bit
the command I use is this
python mitmf.py -i wlan0 --spoof --arp --hsts --dns --gateway 192.168.1.1 --gatewaymac xx:xx:xx:xx:xx  --log-level debug

**Comment by HAMIDx9** [comment]
Hi,

Your `dnspython` version seems to be python3! try following command and make sure the version is 1.12.0:
```
pip freeze | grep dnspython
``` 

you can use 
```
pip install -U dnspython 
```
to upgrade the package.
Also try to force python version in executing mitmf to 2.7 and post the result.

**Comment by DevilDendy** [comment]
Tanks  HAMIDx9
but the problem not are dnspython
 the version is 1.2.0
root@kali:~# pip freeze | grep dnspython
dnspython==1.12.0
dnspython3==1.12.0

**Comment by HAMIDx9** [comment]
Your posted error comes from dnspython package. remove dnspython3 and reinstall dnspython(2.7) and try again.

**Comment by DevilDendy** [comment]
thank you so much HAMIDx9
 problem solved
