### ISSUE TITLE
ImportError: No module named pyinotify

### ISSUE THREAD

**Issue by itmakeyousmile** [byt3bl33d3r/MITMf#247]
Hello. i get this error when i try to run this command 
sudo python mitmf.py -i eth0 --target 192.168.1.58 --gateway 192.168.1.1 --hsts
i tried kali and ubuntu and i get the same error. the error is : 
Traceback (most recent call last):
  File "mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/home/mossy/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/home/mossy/MITMf/core/configwatcher.py", line 20, in <module>
    import pyinotify
ImportError: No module named pyinotify
![screenshot_10](https://cloud.githubusercontent.com/assets/16600504/12250997/203e1468-b880-11e5-8ed0-21e7b3b43b48.png)

**Comment by HAMIDx9** [comment]
Hi,

It seems you completely followed [installation page instructions](https://github.com/byt3bl33d3r/MITMf/wiki/Installation) but remember as long as you use `sudo` you no longer have an active `virtualenv`. So first use `sudo su` or `sudo -i`, ... and then try installation page again and use `MITMf` then.

**Comment by byt3bl33d3r** [comment]
@itmakeyousmile ok so your sorta have a point, try using ```sudo -E``` to preserve environment variables
