### ISSUE TITLE
Wrong parameters passed to pebin

### ISSUE THREAD

**Issue by DKingCN** [byt3bl33d3r/MITMf#248]
Consulting with libs.bdfacory.pebin,I made some conclusions here.

plugin.filepwn
XP_MODE
line 377/411    RUNAS_ADMIN should be CHECK_ADMIN
line 382/416    SUPPLIED_BINARY   [no such parameter]
line 417           XP_MODE                  [no such parameter]

To reproduce,try to download putty.exe

My solution is to comment these lines in filepwn.py.But maybe you got bigger plan here,yeah bro?

**Comment by DKingCN** [comment]
This bug together with my previous bugreport have been concluded in my pull request

**Comment by thedp** [comment]
I've adjusted my local copy of MITMf with your fix and it gives the following error:

`2016-01-17 00:26:10 [FilePwn] Exception in binaryGrinder 'CHECK_ADMIN'`

**Comment by DKingCN** [comment]
Yes ,maybe i made too many modification to my local copy and forgot some of them.
Finding where the mistake is.

**Comment by DKingCN** [comment]
OK,the problem is that I was using an old version of bdfactory in kali linux's repository , where i make a link bdfactory->backdoor-factory in kali.
The new version of bdfactory has parameters called RUNAS_ADMIN, so No need to change CHECK_ADMIN.
I will update the old pull request.Thank you for pointing out the mistake.

**Comment by DKingCN** [comment]
Sorry ,this issue is is totally a mistake.I will close it by myself.
And the pull request will be cancelled ,even tho it fix the #236 .

**Comment by thedp** [comment]
That's actually how I managed to adjust your fix and made the FilePwn work for the first time. So thanks bro :)
