### ISSUE TITLE
No module named bdfactory

### ISSUE THREAD

**Issue by Snipercatz** [byt3bl33d3r/MITMf#251]
I am encountering the following problem when attempting to run mitmf on my Kali Linux desktop.  Any assistance would be appreciated.  Thanks in advance.
![screenshot from 2016-01-13 11 03 48](https://cloud.githubusercontent.com/assets/8577656/12303109/d6f334d4-b9e5-11e5-9d88-84fb542f1ab9.png)

**Comment by HAMIDx9** [comment]
You should init some submodules and install reqs. Use [Installation page](https://github.com/byt3bl33d3r/MITMf/wiki/Installation).

**Comment by Snipercatz** [comment]
damn my bad....
