### ISSUE TITLE
Requirements installation failled on Kali2.0

### ISSUE THREAD

**Issue by choosetwo** [byt3bl33d3r/MITMf#255]
Hi, 
i follow these instructions :
apt-get install virtualenv virtualenvwrapper python-setuptools python-smbus python-pil
source /etc/bash_completion.d/virtualenvwrapper
mkvirtualenv MITMf -p /usr/bin/python2.7
git clone https://github.com/byt3bl33d3r/MITMf
cd MITMf && git submodule init && git submodule update --recursive
pip install -r requirements.txt
python mitmf.py --help

Who works very well until i get this :
(MITMf)root@kali:~/MITMf# pip install -r requirements.txt 
Downloading/unpacking git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-aow_US-build
  Running setup.py (path:/tmp/pip-aow_US-build/setup.py) egg_info for package from git+git://github.com/kti/python-netfilterqueue
    
Requirement already satisfied (use --upgrade to upgrade): pyinotify in /root/.virtualenvs/MITMf/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Downloading/unpacking pycrypto (from -r requirements.txt (line 3))
  Downloading pycrypto-2.6.1.tar.gz (446kB): 446kB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/pycrypto/setup.py) egg_info for package pycrypto
    
Downloading/unpacking pyasn1 (from -r requirements.txt (line 4))
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Downloading/unpacking Pillow (from -r requirements.txt (line 5))
  Downloading Pillow-3.1.0.tar.gz (9.9MB): 9.9MB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/Pillow/setup.py) egg_info for package Pillow
    
    warning: no previously-included files found matching '.editorconfig'
Downloading/unpacking netaddr (from -r requirements.txt (line 6))
  Downloading netaddr-0.7.18-py2.py3-none-any.whl (1.5MB): 1.5MB downloaded
Downloading/unpacking scapy (from -r requirements.txt (line 7))
  Downloading scapy-2.3.1.zip (1.1MB): 1.1MB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/scapy/setup.py) egg_info for package scapy
    
Downloading/unpacking dnslib (from -r requirements.txt (line 8))
  Downloading dnslib-0.9.6.tar.gz (60kB): 60kB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/dnslib/setup.py) egg_info for package dnslib
    
Downloading/unpacking Twisted (from -r requirements.txt (line 9))
  Downloading Twisted-15.5.0.tar.bz2 (3.1MB): 3.1MB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/Twisted/setup.py) egg_info for package Twisted
    
Downloading/unpacking lxml (from -r requirements.txt (line 10))
  Downloading lxml-3.5.0.tar.gz (3.8MB): 3.8MB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/lxml/setup.py) egg_info for package lxml
    Building lxml version 3.5.0.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    
    warning: no previously-included files found matching '*.py'
Downloading/unpacking pefile (from -r requirements.txt (line 11))
  Downloading pefile-1.2.10-114.tar.gz (49kB): 49kB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/pefile/setup.py) egg_info for package pefile
    
Downloading/unpacking ipy (from -r requirements.txt (line 12))
  Downloading IPy-0.83.tar.gz
  Running setup.py (path:/tmp/pip-build-fXHlx8/ipy/setup.py) egg_info for package ipy
    
Downloading/unpacking user-agents (from -r requirements.txt (line 13))
  Downloading user_agents-1.0.1-py2-none-any.whl
Downloading/unpacking pyopenssl (from -r requirements.txt (line 14))
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB): 102kB downloaded
Downloading/unpacking service-identity (from -r requirements.txt (line 15))
  Downloading service_identity-14.0.0-py2.py3-none-any.whl
Downloading/unpacking configobj (from -r requirements.txt (line 16))
  Downloading configobj-5.0.6.tar.gz
  Running setup.py (path:/tmp/pip-build-fXHlx8/configobj/setup.py) egg_info for package configobj
    
Downloading/unpacking Flask (from -r requirements.txt (line 17))
  Downloading Flask-0.10.1.tar.gz (544kB): 544kB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/Flask/setup.py) egg_info for package Flask
    
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking dnspython (from -r requirements.txt (line 18))
  Downloading dnspython-1.12.0.zip (230kB): 230kB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/dnspython/setup.py) egg_info for package dnspython
    
Downloading/unpacking beautifulsoup4 (from -r requirements.txt (line 19))
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB): 81kB downloaded
Downloading/unpacking capstone (from -r requirements.txt (line 20))
  Downloading capstone-3.0.4.tar.gz (3.2MB): 3.2MB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/capstone/setup.py) egg_info for package capstone
    
Downloading/unpacking python-magic (from -r requirements.txt (line 21))
  Downloading python-magic-0.4.10.tar.gz
  Running setup.py (path:/tmp/pip-build-fXHlx8/python-magic/setup.py) egg_info for package python-magic
    
    no previously-included directories found matching 'test'
Downloading/unpacking msgpack-python (from -r requirements.txt (line 22))
  Downloading msgpack-python-0.4.6.tar.gz (116kB): 116kB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/msgpack-python/setup.py) egg_info for package msgpack-python
    
Requirement already satisfied (use --upgrade to upgrade): requests in /root/.virtualenvs/MITMf/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Downloading/unpacking pypcap (from -r requirements.txt (line 24))
  Downloading pypcap-1.1.4.tar.gz (41kB): 41kB downloaded
  Running setup.py (path:/tmp/pip-build-fXHlx8/pypcap/setup.py) egg_info for package pypcap
    pcap.h not found
    Complete output from command python setup.py egg_info:
    pcap.h not found

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-fXHlx8/pypcap
Storing debug log for failure in /root/.pip/pip.log

I already tried lot of different way.
So am open :D 

thanks by advance

**Comment by HAMIDx9** [comment]
Hi, 

you should install dips correctly, precisely you should install libpcap0.8-dev and some other which you can see on [Installation Page](https://github.com/byt3bl33d3r/MITMf/wiki/Installation)

one shot try: 
```
apt-get install python-dev python-setuptools libpcap0.8-dev libnetfilter-queue-dev libssl-dev libjpeg-dev libxml2-dev libxslt1-dev libcapstone3 libcapstone-dev libffi-dev file
```

and then try install reqs again.

**Comment by choosetwo** [comment]
Hi, Thanks for your answer

Awesome that work !!
Thanks a lot guy !!

**Comment by choosetwo** [comment]
Hi again,
i know how to install it but i tried several thing with MIMTf but each time, my target don't have Internet after i run --hsts it's normal ? 
or i miss something ? 

Thank by advance.

**Comment by n0rd41** [comment]
> one shot try:
> 
> apt-get install python-dev python-setuptools libpcap0.8-dev libnetfilter-queue-dev libssl-dev libjpeg-dev > libxml2-dev libxslt1-dev libcapstone3 libcapstone-dev libffi-dev file
> and then try install reqs again.

This solved my issue! Thank you. Posting error again for more search popularity..

> python` setup.py egg_info" failed with error code 1 in /tmp/pip-build-PiplOg/pypcap/
