### ISSUE TITLE
installation problem ubuntu 

### ISSUE THREAD

**Issue by itmakeyousmile** [byt3bl33d3r/MITMf#256]
![screenshot_1](https://cloud.githubusercontent.com/assets/16600504/12538757/c674469e-c2ea-11e5-9de0-eb52d640cdda.png)
what i must to do?

**Comment by HAMIDx9** [comment]
It seems pip finds a wrong pcap header.  Move that kernel source or check your piblcap installation to get a right header.

**Comment by danetrain** [comment]
I'm also seeing this issue. @HAMIDx9 could you clarify what you mean here?

**Comment by HAMIDx9** [comment]
Look at the picture carefully. The header pip has found is kernel touchscreen config header. This is a false finding. Removing the kernel source or fixing header locations fixes the issue.
Also check https://github.com/dugsong/pypcap/issues/49
