### ISSUE TITLE
Requirements Issue

### ISSUE THREAD

**Issue by arbazhussain149** [byt3bl33d3r/MITMf#263]
root@kali:~# pip install -r requirements.txt 
Collecting git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-2L_dj4-build
Requirement already satisfied (use --upgrade to upgrade): pyinotify in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Collecting cryptography (from -r requirements.txt (line 5))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached cryptography-1.2.2.tar.gz
Collecting Pillow (from -r requirements.txt (line 6))
  Using cached Pillow-3.1.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): scapy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Collecting dnslib (from -r requirements.txt (line 9))
  Using cached dnslib-0.9.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Twisted in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): pefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): ipy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Collecting user-agents (from -r requirements.txt (line 14))
  Using cached user_agents-1.0.1-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in /usr/lib/pymodules/python2.7 (from -r requirements.txt (line 15))
Collecting service-identity (from -r requirements.txt (line 16))
  Using cached service_identity-14.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): configobj in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): Flask in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): dnspython in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Collecting capstone (from -r requirements.txt (line 21))
  Using cached capstone-3.0.4.tar.gz
Collecting python-magic (from -r requirements.txt (line 22))
  Using cached python-magic-0.4.10.tar.gz
Requirement already satisfied (use --upgrade to upgrade): msgpack-python in /usr/lib/pymodules/python2.7 (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 24))
Collecting pypcap (from -r requirements.txt (line 25))
  Using cached pypcap-1.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    pcap.h not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-51FpYF/pypcap

**Comment by daw1012345** [comment]
You do not have the libpcap-dev package. Install using apt-get install libpcap-dev or apt-get install libpcap0.8-dev depending on your system (Try the libcap-dev package first).
