### ISSUE TITLE
Error in jskeylogger

### ISSUE THREAD

**Issue by Jett21** [byt3bl33d3r/MITMf#270]
Hi byt3bl33d3r, 

I'm having problem on using MITMf. I'm having this error:

python mitmf.py -i eth0 --spoof --arp --gateway 192.168.15.1 --target 192.168.15.122 --jskeylogger
Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/MITMf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory

Can you please assist, with this. thanks

**Comment by HAMIDx9** [comment]
Hi, 
Use this [page](https://github.com/byt3bl33d3r/MITMf/wiki/Installation).

**Comment by Jett21** [comment]
hi i already follow that instruction, and im still having the same error. is there a video tutorial on how to install MITMf?

**Comment by mw3demo** [comment]
@Jett21 Suggest you download Kali Rolling, which OffSec is now is happy with stability wise. It comes with MITMf 0.9.8 

https://www.kali.org/news/kali-linux-rolling-edition-2016-1/
https://www.kali.org/downloads/

**Comment by Jett21** [comment]
this the version of my kali 

Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux

but there's no MITMf and i have to install it using the instruction in this site

https://github.com/byt3bl33d3r/MITMf/wiki/Installation

**Comment by Jett21** [comment]
Hi i everyone, I've already Fix the problem by reinstalling MITMf,and now i'ts working on my virtualbox **BUT NOT** on LAN. nothing's happening if I'm trying to use it on A CPU via LAN.please help me. Guys!

**Comment by byt3bl33d3r** [comment]
https://www.youtube.com/watch?v=8d4RtvMQp10
