### ISSUE TITLE
Kali Rolling NO MITMf

### ISSUE THREAD

**Issue by Jett21** [byt3bl33d3r/MITMf#271]
Hi byt3bl33d3r,

Can't find MITMf on kali rolling. Please Help

**Comment by douchecanoe** [comment]
@Jett21 How far into the [installation ](https://github.com/byt3bl33d3r/MITMf/wiki/Installation) did you get before it failed?

**Comment by Jett21** [comment]
i've finish the installation of kali rolling, but can't find MITMf.

**Comment by byt3bl33d3r** [comment]
@Jett21 I'm guessing you tried running ```apt-get install mitmf``` ? No clue if its still is the repos since I haven't touch kali's version in a while. In any case you should probably open an issue ticket at https://bugs.kali.org/
