### ISSUE TITLE
No input anymore

### ISSUE THREAD

**Issue by slkdmr** [byt3bl33d3r/MITMf#284]
I was using mitmf for arpspoofing but one day I dont know what happened, mitmf stopped giving me output. I checked out arp packets with wireshark, they were there. I tried everything, ips are correct, the sites that im opening are not http/https and even sometimes not www. What could be changed? Thanks. (You can want me to post any document here.)

**Comment by byt3bl33d3r** [comment]
Closing since you didn't follow the guidelines for submitting a bug report. Please see the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) on how to properly report a bug.
