### ISSUE TITLE
inject plugin "request headers" issue

### ISSUE THREAD

**Issue by arslevsh** [byt3bl33d3r/MITMf#287]
After release Twisted-16.0.0 (15.03.2016) inject plugin doesn't work properly.

If you just installed mitmf, or upgraded twisted, you'll face: 
ClientRequest object has no attribute 'headers' 
bug while running inject plugin. 

To fix this issue until new release mitmf run "pip uninstal twisted" and then install Twisted-15.5.0 manualy (http://twistedmatrix.com/Releases/Twisted/15.5/)

**Comment by SiNaPsEr0x** [comment]
thanks working for me !

**Comment by henriquecrw** [comment]
How do i install it in a debian? Getting stuck here;

I did the following:
`apt-get remove python-twisted -y
`
Untill here fine, but I'm not finding a way install it! 

I downloaded Twisted-15.5.0.tar.bz2, extracted it and now not finding a way to install! 

`tar xvf Twisted-15.5.0.tar.bz2'
