### ISSUE TITLE
How does filepwn implement dns poison?

### ISSUE THREAD

**Issue by githubname1** [byt3bl33d3r/MITMf#288]
Hello. While running the following command in Kali `mitmf -i eth0 --arp --spoof --gateway 192.168.1.1 --target 192.168.1.4 --filepwn` i have noticed that in latest chrome, when i typed `google.gr` the result was an http version of google. (Although that did not work in Facebook or Linked in websites opened by victim). How does filepwn implement the above feature?

**Comment by byt3bl33d3r** [comment]
If you opened google in a modern version of chrome, in theory you should have gotten redirected to an https page because of HSTS. The Filepwn plugin has nothing to do with that, since it's servers a completely different purpose.
