### ISSUE TITLE
Error with pyinotify in python2.7 MITMf

### ISSUE THREAD

**Issue by Garriga** [byt3bl33d3r/MITMf#290]
When I execute in terminal 'python2.7 mitmf.py', it returns me this:
_Traceback (most recent call last):
  File "mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/home/mester/Hacking/MITM/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/home/mester/Hacking/MITM/MITMf/core/configwatcher.py", line 20, in <module>
    import pyinotify
  File "build/bdist.linux-x86_64/egg/pyinotify.py", line 53, in <module>
pyinotify.UnsupportedPythonVersionError: Python 2.7.11 (default, Mar  3 2016, 11:00:04) 
[GCC 5.3.0] is unsupported, requires at least Python 3.0_

And, if I execute 'python3 mitmf.py', it returns me:

_File "mitmf.py", line 38
    print get_banner()
                   ^
SyntaxError: invalid syntax_

In my Kali partition MITMf works great, but in my Arch Linux partition returns me this errors. I have installed pyinotify but only it's valid for python3 or higher.

Thanks.

**Comment by Irvel** [comment]
python3 mitmf.p will not work because MITMf works with Python 2.7

Try doing a `pip install --upgrade  --force-reinstall pyinotify` as pyinotify works just fine 0.9.6 in Python 2.7.11

**Comment by Garriga** [comment]
Okay, thanks, works great!
