### ISSUE TITLE
127.0.0.1 [DNS] Could not proxy request: timed out

### ISSUE THREAD

**Issue by clebersleite** [byt3bl33d3r/MITMf#295]
Ok simple, if I use:
mitmf.py -i  wlan0 --arp --spoof --hsts --gateway 192.168.1.1

It work Fine!

but when I set the target:
mitmf.py -i  wlan0 --arp --spoof --hsts --gateway 192.168.1.1 --target 192.168.1.39

My network go down....help?

If anyone need a log tell me about.

**Comment by Britskiy** [comment]
Sorry to intervene not on the substance, but may be you'll show me. You write that you have a command 
`mitmf.py -i wlan0 --arp --spoof --hsts --gateway 192.168.1.1`
works, but I have the same command in the browser shows the authentication dialog and is no longer tracking anything.

**Comment by clebersleite** [comment]
authentication? it does not appears here =/

**Comment by Britskiy** [comment]
http.py , line 270 
`log.info("{} [HTTP] Sending NTLM authentication request".format(client))`

i see it in console when i connect to server.

**Comment by rainbowjose** [comment]
Got the exactly same problem!

**Comment by clebersleite** [comment]
It help you?
https://github.com/byt3bl33d3r/MITMf/issues/264

**Comment by clebersleite** [comment]
Check if you don't have any http daemon before start mitmf, it apears when the mitmf can't bind 80 tcp port.

check with: netstat -anp | grep :80 | grep LISTEN

**Comment by rainbowjose** [comment]
I don't have. Only if im start sniffing.

**Comment by clebersleite** [comment]
Skype? nothing into 80?

**Comment by rainbowjose** [comment]
Exactly nothing

**Comment by clebersleite** [comment]
Stranger, I don't know. I read the code and it try do bind 80 TCP otherwise call NTLM. 

Sorry my english hehe

**Comment by Britskiy** [comment]
`netstat -anp | grep :80 | grep LISTEN` - EMPTY
Do you know what causes NTLM?

[#264](https://github.com/byt3bl33d3r/MITMf/issues/264) - I run `iptables flush` and allow all permission, still nothing. Or I not correctly understood the advice given to that problem?

**Comment by clebersleite** [comment]
Are you behind a Windows Domain?

**Comment by Britskiy** [comment]
I run mitmf in linux) and test it in linux, windows and android - same NTLM

**Comment by byt3bl33d3r** [comment]
This gets the dafuq label cause you're all talking about diffrent things and it doesn't make any sense.
@clebersleite follow the guidelines on the [wiki](https://github.com/byt3bl33d3r/MITMf/wiki/Installation) for reporting a bug, I'm going to need a lot more information to be able to even attempt to fix this. Closing in the meantime.
