### ISSUE TITLE
[ProxyPlugins] Exception occurred in hooked function

### ISSUE THREAD

**Issue by Tarikxmx** [byt3bl33d3r/MITMf#296]
[ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 116, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'

**Comment by arslevsh** [comment]
Hi! Look at issue https://github.com/byt3bl33d3r/MITMf/issues/287
It helped me

**Comment by Tarikxmx** [comment]
thanks arslevsh "pip uninstal twisted" and then "pip install twisted==15.5.0" solved my problem
