### ISSUE TITLE
Ferret-NG  --load-cookies error

### ISSUE THREAD

**Issue by DKingCN** [byt3bl33d3r/MITMf#297]
sys: Kali Sana amd64
pkg: twisted 15.5.0

`mitmf --ferretng --port 10010 --load-cookies "/usr/share/mitmf/logs/ferret-ng/cookies-XXX.log" -i wlan0  --log debug`

OUTPUT
2016-04-03 01:24:59 [Ferret-NG] [ClientRequest] Resolving host: XXX
2016-04-03 01:24:59 [Ferret-NG] [ClientRequest] Resolved host successfully: XXX -> 119.XX.217.109
2016-04-03 01:24:59 [Ferret-NG] [ClientRequest] Zapped encoding
2016-04-03 01:24:59 [Ferret-NG] [ClientRequest] Host resolution error: [Failure instance: Traceback: <type 'exceptions.TypeError'>: string indices must be integers, not str
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:588:_runCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:254:_checkTimeout
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:393:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:501:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:588:_runCallbacks
/usr/share/mitmf/core/ferretng/ClientRequest.py:99:handleHostResolvedSuccess
/usr/share/mitmf/core/ferretng/ClientRequest.py:76:cleanHeaders

ClientRequest.py
line#77
`for entry in self.urlMonitor.cookies[self.urlMonitor.hijack_client]:`

In my examination I found that `self.urlMonitor.cookies` was a string where it should be a dict, however I can't convert it from string to dict (eval() doesn't work)
the examinations are driving me crazy. Have a look at this:

I insert some sentences before L#77
               `for entry in self.urlMonitor.cookies[self.urlMonitor.hijack_client]:`
so it became:
                aaa=self.urlMonitor.cookies
                print type(aaa)
                print aaa
                aaa=eval(aaa)
                print type(aaa)
                print aaa
                for entry in aaa[self.urlMonitor.hijack_client]:

THE OUTPUT:

<type 'str'>
"{cookie_log_dict_content}"

 <type 'str'>
{cookie_log_dict_content}
2016-04-03 02:14:24 [Ferret-NG] [ClientRequest] Host resolution error: [Failure instance: Traceback: <type 'exceptions.TypeError'>: string indices must be integers, not str

%@#%@&#%*)(@
fk  me.

looking forward to your help.

**Comment by byt3bl33d3r** [comment]
Can you attach the file with the cookies you're loading? also I'm the output of pip freeze and debug output would be very helpful

**Comment by morningmoni** [comment]
The problem is 
```python
if options.cookie_file:
            self.tree_info.append('Loading cookies from log file')
            try:
                with open(options.cookie_file, 'r') as cookie_file:
                    self.cookie_file = json.dumps(cookie_file.read())
                    URLMonitor.getInstance().cookies = self.cookie_file
                    cookie_file.close()
```
After json.dumps() on a Ferret-NG log file, type(self.cookie_file) is actually str NOT dict. So the above error was encountered.

And I'm also confused about the usage of Ferret-NG.
The following is only executed when visiting localhost:10010 and headers is sth like {'host': 'localhost:10010', 'accept-language': 'en-US,en;q=0.5', 'connection': 'keep-alive', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0'}.
then what's the point of headers['host'] == entry['host']?
And what's the meaning of self.urlMonitor.hijack_client? In my case, it's an IP in LAN and hence surely isn't in the cookie_dict.
```python
        if 'host' in headers:
            try:
                for entry in self.urlMonitor.cookies[self.urlMonitor.hijack_client]:
                    if headers['host'] == entry['host']:
                        log.info("Hijacking session for host: {}".format(headers['host']))
                        headers['cookie'] = entry['cookie']
```

Thanks!
