### ISSUE TITLE
MITMf fails to run, gives error

### ISSUE THREAD

**Issue by shadowblade7536** [byt3bl33d3r/MITMf#303]
▄▄▄▄███▄▄▄▄    ▄█      ███       ▄▄▄▄███▄▄▄▄      ▄████████ 
 ▄██▀▀▀███▀▀▀██▄ ███  ▀█████████▄ ▄██▀▀▀███▀▀▀██▄   ███    ███ 
 ███   ███   ███ ███▌    ▀███▀▀██ ███   ███   ███   ███    █▀  
 ███   ███   ███ ███▌     ███   ▀ ███   ███   ███  ▄███▄▄▄     
 ███   ███   ███ ███▌     ███     ███   ███   ███ ▀▀███▀▀▀     
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
  ▀█   ███   █▀  █▀      ▄████▀    ▀█   ███   █▀    ███        

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Spoof v0.6
|  |_ DNS spoofing enabled
|  |_ ARP spoofing enabled
Traceback (most recent call last):
  File "mitmf.py", line 138, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/home/lucidbytes/Desktop/hacking/wifi/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/home/lucidbytes/Desktop/hacking/wifi/MITMf/core/sslstrip/ClientRequest.py", line 25, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax

I tried everything, from uninstalling dnspython3 to forcing python version 2.7, but nothing works.

**Comment by shadowblade7536** [comment]
I fixed it, and here is how I did it.

Go and manually delete the entire /dns/ folder inside /usr/local/python2.7/dist-packages/

Then manually download dnspython for python(2.7) from here http://www.dnspython.org/kits/1.12.0/
and install it.

This worked for me, but if it still didnt work, follow the steps here #245

**Comment by byt3bl33d3r** [comment]
Glad you figured it out. Cheers
