### ISSUE TITLE
WiFi Pineapple MK V MITMf Infusion

### ISSUE THREAD

**Issue by mw3demo** [byt3bl33d3r/MITMf#31]
Hey @byt3bl33d3r 

Excellent project, love watching the rapid development, (Added your commit page to my RSS reader due to your rapid updates over the past month! :+1: ) I was wondering if there is any interest getting this running on the WiFi Pineapple MK V? These two would really work great with each other, with dip switches triggering various MITMf setups to start on boot, or via it's web interface and the Pineapple capturing clients via it's PineAP attack suite. Best of software and hardware MITM/

A quick bit of background my part as a user: The project is run by a small team of developers, one software (Seb), and Darren plus the rest of the team at hak5. Then there are a couple of infusion devs, who mainly put a front end function to packages available such as ettercap/sslstrip. I feel it's a great piece of hardware, its dev focus is improving the firmware in capturing clients and usability. 

What it is still lacking however, is a great toolkit, one stop shop, once users are connected. MITMf could merge a bunch of the previous infusions usability and then add a bunch more, with a great web interface toggling all the functions, even over 3g via it's mobile web interface. You are also super active adapting to the latest talks which is great!

Another infusion creator used his computer for the heavy lifting, running his scripts on kali connected via ICS to the pineapple: https://code.google.com/p/jasagerpwn-reborn/
He had some interesting payloads that you might be interested as well, but mainly to show another method of interacting with the pineapple. They are working on an API for the web interface, as you can see from the link below. However there is only so much I think the 1 dev of the project (Seb) can do and focus on.

Resources:
List of current infusions: https://wifipineapple.com/?infusions 
Changelog: https://wifipineapple.com/?changelog
Website: https://wifipineapple.com
Forums: https://forums.hak5.org
Web Interface API: http://wiki.wifipineapple.com/index.php/Webinterface_API
PineAP (It's main attack to get clients) dev vid and good overall overview of the project: https://www.youtube.com/watch?v=40Igim3upL0

Specs below, runs on custom OpenWRT firmware (http://wiki.wifipineapple.com/index.php/Build_guide). 

    CPU: 400 MHz MIPS Atheros AR9331 SoC.
    Memory: 16 MB ROM, 64 MB DDR2 RAM
    Disk: Micro SD support up to 32 GB, FAT or EXT, 2 GB Included
    Mode Select: 5 DIP Switches - 2 System, 3 User configurable
    Wireless: Atheros AR9331 IEEE 802.11 b/g/n + Realtek RTL8187 IEEE 802.11 b/g
    Ports: (2) SMA Antenna, 10/100 Ethernet, USB 2.0, Micro SD, TTL Serial, Expansion Bus
(Note: Alot of people add a 3rd wifi/3g dongle in the usb port for net access, leaving the two antennas free for PineAP. You run all infusions on the br-lan interface via the web infusions. 

Let me know if this is of any interest and I'd be happy to assist in any way I can, but fully understand if it isn't, as this is bit unique and may take alot of time.

**Comment by byt3bl33d3r** [comment]
@mw3demo just a quick update, I contacted Seb multiple times and he seemed interested but I haven't heard back from him in a couple of months, I'll close this in the meantime and re-open it if things change.

**Comment by mw3demo** [comment]
@byt3bl33d3r  Hey there! Hope you have been well, and many thanks for the update. No problem, I know they had a "Hack across Europe" thing going on over February, should be back by now. They appear to be most active on twitter, might be worth dropping a them a quick tweet:

https://twitter.com/sebkinne
https://twitter.com/hak5darren

**Comment by byt3bl33d3r** [comment]
@mw3demo I think I already sent a tweet to Darren regarding this... But I'll try again later on today

**Comment by mw3demo** [comment]
@byt3bl33d3r Alright great. I completely forgot to open that suggestion ticket I mentioned earlier, and have done now:

https://www.wifipineapple.com/index.php?portal&bugs&action=view&id=291

**Comment by mw3demo** [comment]
@byt3bl33d3r Sensepost, and Hak5 showing you the love on the same day! :+1: Congrats man! Also hope you had a great time over at BHA in Singapore! :+1:

**Comment by byt3bl33d3r** [comment]
@mw3demo thanks man! def great to see some feedback! Had a blast at BH Asia! :D

**Comment by xtr4nge** [comment]
Hi guys,
MITMf has been included in FruityWifi.

http://www.fruitywifi.com
https://github.com/xtr4nge/FruityWifi/

regards

**Comment by vapor99** [comment]
Hmmm.. Interesting one.  Luv the Hak5 guys (and my Mark Vs).  Maybe a mini-mitmf would work.  lol
