### ISSUE TITLE
Proxy timed out - changing nameservers doesnt help

### ISSUE THREAD

**Issue by K4CZP3R** [byt3bl33d3r/MITMf#311]
Hi, i readed issue about proxy timed out. Ive get nameservers from etc/resolv.conf and copied it to mitmf.conf. but I still getting proxy timed out some are with localhost and some with targets

**Comment by byt3bl33d3r** [comment]
Closing since you didn't follow the guidelines for submitting a bug report. Please see the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) on how to properly report a bug.
