### ISSUE TITLE
loosing connexion after the first querie.

### ISSUE THREAD

**Issue by themasquedpear** [byt3bl33d3r/MITMf#312]
Hello,

I have a problem with MITMf.

When i start an attack, the first querie in the victim browser work fine.
But when i click on another link or if i reload the page, then it doesn't work anymore. There is no more internet connection on the victim device. and the terminal of MITMf don't show any new line. i must stop the attack and disconnect/reconnect the victim to the network in order to recover internet connexion.

Can you help me please?

**Comment by byt3bl33d3r** [comment]
https://www.youtube.com/watch?v=JYJEFE8PcTk

**Comment by byt3bl33d3r** [comment]
@
Closing since you didn't follow the guidelines for submitting a bug report. Please see the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) on how to properly report a bug.
