### ISSUE TITLE
error 23 open too much file

### ISSUE THREAD

**Issue by thanh125643** [byt3bl33d3r/MITMf#315]
when i use it for i alone time it just like this 
[ARPpoisoner] error 23 open too much file

**Comment by byt3bl33d3r** [comment]
Just fyi, I'm leaving this open just for shits in giggles

**Comment by byt3bl33d3r** [comment]
Decided to close this since everytime I see this it makes me want to drink

**Comment by PenilePain** [comment]
Is it to make you a... pain on your penis?
