### ISSUE TITLE
MITMf does not work on iPhone

### ISSUE THREAD

**Issue by bu7maid** [byt3bl33d3r/MITMf#317]
I am using MITMf on Kali Linux 2016.1 and tried it on different devices.
I have tried it on MacBook and it seems to work but not on every website such as instagram. But when I tried it on an iPhone, it started but nothing happened or appeared on the screen.

**Comment by bu7maid** [comment]
Does this apply to all other smart phones?

**Comment by jakuta-tech** [comment]
I know this is going to be sent to the "MOAR information" bin but just clarify.  Yes it does work fine on iPhone as well as Android and windows devices, HSTS and site specifics aside.

**Comment by shadowblade7536** [comment]
If talking about the instagram app, then it will never work since it uses strict HTTPS. If you are talking about the website, it should work if the browser doesnt have an HSTS PreLoad list inside it.

**Comment by byt3bl33d3r** [comment]
Think you should try and understand what MITMf, SSLStrip, HSTS and certificate pinning are.

**Comment by HuskerC** [comment]
Unfortunatelly I'm having the same issue.
Im able to spoof safari http traffic with arpspoof and wireshark/tshark/ngrep for my iPhone, but absolutely nothing on with mitmf. 
I'm talking about pure http Pages. For macos, Linux and windows mitmf spoofing works as expected. For iOS, no success.
