### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by shadowblade7536** [byt3bl33d3r/MITMf#318]
This really isnt an issue, but ive recently acquired lots of free time due to collapsed lung, and since im gonna be free for a week, I was wondering, do you need any help with anything?

Im mostly a newbie programmer when it comes to python, but still, time is of the essence!

**Comment by byt3bl33d3r** [comment]
@shadowblade7536 all help is appreciated, I'm currently pretty busy between work plus other projects hence why this hasn't been updated in a while.
