### ISSUE TITLE
Mitm failed due to arp request detection by IDS on DSL & ADSL router . 

### ISSUE THREAD

**Issue by sidjad** [byt3bl33d3r/MITMf#321]
I am using mitmf in kali 2016.1 unfortunately it was failed due to router detect arp , dns spoofing . even though nmap scan not respond very well , is any way to poison network  ?

**Comment by byt3bl33d3r** [comment]
I don't think you fully understand what MITMf does, NMap does something completely different. It's an apples and mango kind of diffrent.
