### ISSUE TITLE
IS MITMF's HSTS bypass still working on latest browsers?

### ISSUE THREAD

**Issue by aslitsecurity** [byt3bl33d3r/MITMf#329]
I tried MITMF on firefox 46 and mitmf was working fine on all websites including facebook, gmail, outlook etc. But then I updated the browers to 47.0.1 the latest and after that if I open any website like facebook.com its redirected to https://facebook.com and mitmf don't seems working. I even tried clearing cookies and all history but still no success. Can you please confirm if HSTS bypass still works on latest chrome and firefox?

**Comment by daw1012345** [comment]
The way by which HSTS bypass works should still be viable and work. I think the issue you're having is that your targets have cached the IP of the websites you're testing the HSTS bypass on. Another issue you could be having is that you are not setting the attack up right. Try using Wireshark and check if your machine is ARP poisoning the victims correctly. Before you do anything, you should first understand how it works. You would be able to troubleshoot the issue yourself. Read up on how the HSTS bypass works :) Also, when submitting a question or a bug report, make sure to refer to the "Submitting a bug report" part of the wiki.
