### ISSUE TITLE
Error calling NetCreds function

### ISSUE THREAD

**Issue by dnsena** [byt3bl33d3r/MITMf#334]
Hi,

I get this sysout when execute mimtf script:

> Traceback (most recent call last):
>   File "mitmf.py", line 97, in <module>
>     Netcreds().start(options.interface, options.ip)
> TypeError: 'module' object is not callable

The problem seems the "start" definition after class definition, on NetCreds script, but I don't understand where is it.

Thanks,

**Comment by byt3bl33d3r** [comment]
can you give me the full terminal output pls?
Thanks

**Comment by ozz86** [comment]
root@kali:~# mitmf --arp --spoof -i wlan0 --gateway 192.168.2.1
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

[*] MITMf v0.9.8 - 'The Dark Side'
Traceback (most recent call last):
  File "./mitmf.py", line 97, in <module>
    NetCreds().start(options.interface, options.ip)
TypeError: start() takes exactly 4 arguments (3 given)

**Comment by ozz86** [comment]
its a virtual machine for usb wifi, in kali linux rollin

**Comment by ozz86** [comment]
I fixed the error Im remplace the /usr/share/mitmf/core/NetCred.py for ultimate version in the Git good luck
