### ISSUE TITLE
arp error

### ISSUE THREAD

**Issue by chintan121** [byt3bl33d3r/MITMf#337]
root@kali:~/MITMf# python mitmf.py -i wlan1 --spoof --arp --gateway 192.168.100.1 --targets 192.168.100.177 --imgrand --img-dir /home/kali/Desktop/img

@@@@@@@@@@   @@@  @@@@@@@  @@@@@@@@@@   @@@@@@@@  
@@@@@@@@@@@  @@@  @@@@@@@  @@@@@@@@@@@  @@@@@@@@  
@@! @@! @@!  @@!    @@!    @@! @@! @@!  @@!  
!@! !@! !@!  !@!    !@!    !@! !@! !@!  !@!  
@!! !!@ @!@  !!@    @!!    @!! !!@ @!@  @!!!:!  
!@!   ! !@!  !!!    !!!    !@!   ! !@!  !!!!!:  
!!:     !!:  !!:    !!:    !!:     !!:  !!:  
:!:     :!:  :!:    :!:    :!:     :!:  :!:  
:::     ::    ::     ::    :::     ::    ::  
 :      :    :       :      :      :     :        

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ ImageRandomizer v0.1
|_ Spoof v0.6
|  |_ ARP spoofing enabled
Traceback (most recent call last):
  File "mitmf.py", line 138, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/root/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 37, in <module>
    from ServerConnection import ServerConnection
  File "/root/MITMf/core/sslstrip/ServerConnection.py", line 28, in <module>
    from user_agents import parse
ImportError: No module named user_agents

**Comment by byt3bl33d3r** [comment]
You didn't follow the install instructions...
