### ISSUE TITLE
Error? Please help!

### ISSUE THREAD

**Issue by Rieddav** [byt3bl33d3r/MITMf#338]
So im getting this error?

Command:
python mitmf.py -i wlan0 --spoof --arp --gateway 192.168.1.245 --target 192.168.1.137 --jskeylogger

Error:
Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/MITMf/plugins/filepwn.py", line 70, in <module>
    import magic
ImportError: No module named magic

**Comment by rajmani1995** [comment]
Have you installed all requirements ?
```bash
cd MITMf
pip install -r requirements.txt
```
**import magic** comes under python package python-magic
```
pip install python-magic
```
For detailed installation process, follow [INSTALL WIKI](https://github.com/byt3bl33d3r/MITMf/wiki/Installation)
NOTE: run all command with root permission only

**Comment by byt3bl33d3r** [comment]
@rajmani1995 thanks!
@Rieddav you didn't follow the install instructions. Take a look at the readme.
