### ISSUE TITLE
" --html-file " Not Working

### ISSUE THREAD

**Issue by MITMf** [byt3bl33d3r/MITMf#34]
every time i use --html-file it says ERNO no such file or directory

i have specified the full path 
ive tried everything it does not work

try it yourself

**Comment by byt3bl33d3r** [comment]
@MITMf lol can you give me the full traceback please!

**Comment by LOOLOOOL** [comment]
i just made an account to report issue yesterday and i forgot the user and pass lol

**Comment by LOOLOOOL** [comment]
i dont know what full  tracback is?

**Comment by LOOLOOOL** [comment]
how did you use it 
tell me the command you typed and it worked

**Comment by LOOLOOOL** [comment]
i am running latest version

**Comment by byt3bl33d3r** [comment]
@LOOLOOOL you should use a password manager..... by traceback i mean the full error that was shown in the terminal

**Comment by ForgotAgian** [comment]
mitmf.py: error: argument --html-file: can't open '1.html': [Errno 2] No such file or directory: '1.html'

**Comment by ForgotAgian** [comment]
i have also specified the full path it says same error

**Comment by byt3bl33d3r** [comment]
hmm your html file is called 1.html? just to make sure can you please give me the full command string you used...
thanks

**Comment by LOOLOOOL** [comment]
ok just got back from first day in year three

**Comment by LOOLOOOL** [comment]
this is the command 

cd Desktop /#  mitmf --spoof --arp --iface wlan0 --target 192.168.1.9 --gateway 192.168.1.1 --html-file 1

cd Desktop /#  mitmf --spoof --arp --iface wlan0 --target 192.168.1.9 --gateway 192.168.1.1 --html-file 1

and then i tried with "1.html" i got same error

**Comment by byt3bl33d3r** [comment]
everything on my end checks out.. try naming the file to something like ```inject.html``` and try again. This seems to be a problem with your system configuration. I'll close this in the meantime, let me know how it goes
