### ISSUE TITLE
pypcap not found during installing requirements.txt

### ISSUE THREAD

**Issue by theparadoxer02** [byt3bl33d3r/MITMf#340]
the following error is coming when entering the command for installing requirements.txt in kali2.0
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m4BJRo/pypcap/`

**Comment by rajmani1995** [comment]
verify libpcap-dev is installed or not 

install on debian system
```
   apt-get install libpcap-dev
```

**Comment by theparadoxer02** [comment]
done ! but w should add it the docs!
