### ISSUE TITLE
Network gets disconnected after running examples

### ISSUE THREAD

**Issue by rajmani1995** [byt3bl33d3r/MITMf#341]
After running command

```
python mitmf.py -i enp1s0 --spoof --arp -k --hsts --gateway 192.168.1.1
```

Console Message:

```
[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
Error starting HTTP server: [Errno 98] Address already in use
|_ HTTP server online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
2016-09-22 22:56:38 [ARPpoisoner] Restoring subnet connection with 2 packets

[DNS] Unable to start DNS server on port 53: port already in use
```

I killed dnsmasq process (using port 53). again ran same examples still getting same error !

Main issue is why network gets disconnected everytime means I can't even ping a local subnet IP address.
reloading network interface doesn't solve this issue.

Only after restarting the system network works.

**Comment by HAMIDx9** [comment]
In my opinion there's lack of useful information in your issue.

what you mean by network gets disconnected? client or MITMf box?
do you check arp table of target to see whether arpspoofer is working or not?
on network dc behavior check your target arp table and try to ping gateway and post the result.

NOTE1: remember --hsts without --dns is useless.

**Comment by byt3bl33d3r** [comment]
@rajmani1995 normally dnsmasq is a service that needs to be stopped so killing the process won't work. I'm assuming that's whats going on here.

**Comment by byt3bl33d3r** [comment]
And I agree with @HAMIDx9  that you definitely need to provide more information for me to help. See the reporting a bug section in the wiki.
