### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by horllste** [byt3bl33d3r/MITMf#350]
Collecting pypcap (from -r requirements.txt (line 25))
  Using cached pypcap-1.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    pcap.h not found

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QKNlgO/pypcap/

so, when i run python mitmf.py --help, i  got

Traceback (most recent call last):
  File "./mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/root/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/root/MITMf/core/configwatcher.py", line 20, in <module>
    import pyinotify
ImportError: No module named pyinotify

**Comment by horllste** [comment]
i manage to get past that error by installing some packages, now am stuck here

   generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:433:30: fatal error: openssl/opensslv.h: No such file or directory
     #include <openssl/opensslv.h>
                                  ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/.virtualenvs/MITMf/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kKbEpo/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PbSqqz-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/MITMf/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-kKbEpo/cryptography/

**Comment by horllste** [comment]
--single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'netfilterqueue' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-EkQe1J/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c netfilterqueue.c -o build/temp.linux-x86_64-2.7/netfilterqueue.o
    netfilterqueue.c:268:42: fatal error: libnfnetlink/linux_nfnetlink.h: No such file or directory
     #include "libnfnetlink/linux_nfnetlink.h"
                                              ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Can't rollback NetfilterQueue, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-0g2tsB-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_nb9lp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-0g2tsB-build/

**Comment by byt3bl33d3r** [comment]
You didn't follow the install instructions

**Comment by maryamtooty** [comment]
Got the same error and exactly fllow instructions..
