### ISSUE TITLE
400 machines in the local area network has been being given

### ISSUE THREAD

**Issue by jxfzzyq** [byt3bl33d3r/MITMf#351]
400 machines in the local area network has been being given, that is the same for a machine, is not the software can not run in the big line network
![640-960 365300fb4667d6e94dfe7859747f19d948b9f8a4_lfyc_40_lfyc2_t f8fc5e](https://cloud.githubusercontent.com/assets/17216985/19420586/ed07c2b0-9420-11e6-9620-c2029962e9a9.png)
![640-960 e786c8559d66ffe834d7177ae2f2f82463278ce4_lfyc_40_lfyc2_t efb42d](https://cloud.githubusercontent.com/assets/17216985/19420590/f5bb3d4c-9420-11e6-8f0f-8481e16af821.png)

**Comment by n0rp3d** [comment]
you're a retard, srsly

**Comment by jlxip** [comment]
@n0rp3d I agree
