### ISSUE TITLE
CAN'T UPGRADE MITMF KALI LINUX NETHUNTER

### ISSUE THREAD

**Issue by MrRushh** [byt3bl33d3r/MITMf#353]
Hi, I have mitmf v0.9.7 and i want to upgrade it to v0.9.8

I ran this(i don't know if it's correct):

_root@kali:~# apt-get upgrade mitmf_

and i got this output: 

_Reading package lists... Done                               Building dependency tree
Reading state information... Done
Calculating upgrade... Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.                              The following information may help to resolve the situation:
The following packages have unmet dependencies:
file : Depends: libmagic1 (= 1:5.22+15-2) but 1:5.28-4 is to be installed
E: Broken packages_

can someone help me?

**Comment by HAMIDx9** [comment]
Hi, 
Follow the [Installation Page](https://github.com/byt3bl33d3r/MITMf/wiki/Installation).
