### ISSUE TITLE
Screen Capture

### ISSUE THREAD

**Issue by Step123** [byt3bl33d3r/MITMf#36]
Now Wouldn't That Be Awesome ?

**Comment by byt3bl33d3r** [comment]
@Step123 damn that is a good idea ! will definitely  be a future plugin! thanks!

**Comment by Step123** [comment]
Thanks!

**Comment by Step123** [comment]
Is There Anyway You Can Man In The Middle If Someone Is Using A VPN 

Sorry Im Noob XD

**Comment by johnbarca** [comment]
is this out??

**Comment by Step123** [comment]
Is this plugin available yet :)

**Comment by byt3bl33d3r** [comment]
@Step123 @johnbarca nope.. been very busy lately will probably start taking care of this next week

**Comment by Step123** [comment]
how can w eupdate to 0.9

**Comment by byt3bl33d3r** [comment]
After doing some research turns out that this is more complicated than I previously thought, so I'm putting it on the back burner for now

**Comment by byt3bl33d3r** [comment]
Gotcha! http://www.xss-payloads.com/payloads/scripts/canvasscreenshot.js.txt

**Comment by byt3bl33d3r** [comment]
there seems to be a bug in the code.. The plugins ready to go, just waiting for their fix :+1:

**Comment by byt3bl33d3r** [comment]
Adding the delayed label again, got their code to run without errors but doesn't seem to be working at all

**Comment by byt3bl33d3r** [comment]
see commit ff39a302f92b799c56bb6017c3de9a69433dbeb0, got another script working , there is just a strange bug when decoding the PNG images

**Comment by byt3bl33d3r** [comment]
IT'S ALIVE! finally got it to work! \o/

**Comment by byt3bl33d3r** [comment]
Done on commit b9371f7cdcb179aa7d38d6395688906a186d6360!
