### ISSUE TITLE
Traceback - import errors?  while running in Ubuntu 16.04 [SOLVED]

### ISSUE THREAD

**Issue by Kakauphony** [byt3bl33d3r/MITMf#364]
After a fresh installation (replaced OS) I checked to see if the install went smoothly and I got these errors:

sudo python mitmf.py 

Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/home/kakauphony/sectools/MITMf/plugins/screenshotter.py", line 27, in <module>
    from plugins.inject import Inject
  File "/home/kakauphony/sectools/MITMf/plugins/inject.py", line 24, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by Ritiek** [comment]
@Kakauphony Looks like you do not have BeautifulSoup installed.
Run the following command to install it:
`sudo pip install BeautifulSoup4`

**Comment by Kakauphony** [comment]
Yessir I did follow the complete directions listed here and i did include the requirements.  

I installed BS and all seems to be working now, thank you.

**Comment by Kakauphony** [comment]
actually,  it's a problem on your end, not mine...so telling me to read the fucking manual is completely misguided, fix your shit.

**Comment by Kakauphony** [comment]
it's actually a problem on your end, not mine...so telling me to read the fucking manual is completely misguided.

**Comment by Kakauphony** [comment]
i'm sorry, but since you're telling me to read the fucking manual, perhaps you can pinpoint the part where it says i must separately install BS

**Comment by byt3bl33d3r** [comment]
the labels are meant to be a joke, wouldn't take it do seriously.
Unless something goes wrong when you run ```pip install -r requirements.txt```, you don't need to install beautifulsoup separately since it's listed as a dep in that file [here](https://github.com/byt3bl33d3r/MITMf/blob/master/requirements.txt#L20).

Cheers
