### ISSUE TITLE
No data capture or showing on screen (after mitmf started)

### ISSUE THREAD

**Issue by tehseensagar** [byt3bl33d3r/MITMf#367]
I'm unable to see any data passing through I ran follwoing command

mitmf --arp --spoof --target 192.168.1.7 --gateway 192.168.1.1 --hsts --dns -i wlan0

` ââââ
â
ââââ ââââ
â
â
ââââââ ââââ
â
ââââ ââââââ
âââââââ ââââââââ âââ âââââââââ ââââââ â
âââ âââââââââ ââââ âââââ âââââââââ â
âââ âââ âââââ ââââ â âââ âââ ââââ â
ââââ ââââââââ ââââ â ââââ ââââââââ
â ââ â âââ â ââ â ââ â â â â
â â â â â â â â â â
â â â â â â â â â
â â â

[*] MITMf v0.9.8 - 'The Dark Side'
|_ SSLstrip+ v0.4
| |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
| |_ DNS spoofing enabled
| |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online

    Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
    |_ HTTP server online
    |_ DNSChef v0.4 online
    |_ SMB server online
    `

Then I opened diferent URL on my mobile incuding HTTP and HTTPS nothing show on console?

**Comment by Ritiek** [comment]
@tehseensagar It should display something in the console.. You might want to cross-check the gateway using `route -n`:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         <b>192.168.82.1</b    0.0.0.0         UG    202    0        0 eth0
10.8.0.0        10.8.0.2        255.255.255.0   UG    0      0        0 tun0
10.8.0.2        0.0.0.0         255.255.255.255 UH    0      0        0 tun0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.82.0    0.0.0.0         255.255.255.0   U     202    0        0 eth0
```

Also try removing a specific target so that your command looks like `mitmf --arp --spoof --gateway 192.168.1.1 --hsts --dns -i wlan0`. This should log traffic from every device..

**Comment by Ritiek** [comment]
@tehseensagar It should display something in the console.. You might want to cross-check the gateway using `route -n`:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         <b>192.168.82.1</b>    0.0.0.0         UG    202    0        0 eth0
10.8.0.0        10.8.0.2        255.255.255.0   UG    0      0        0 tun0
10.8.0.2        0.0.0.0         255.255.255.255 UH    0      0        0 tun0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.82.0    0.0.0.0         255.255.255.0   U     202    0        0 eth0
```

Also try removing a specific target so that your command looks like `mitmf --arp --spoof --gateway 192.168.1.1 --hsts --dns -i wlan0`. This should log traffic from every device..

**Comment by tehseensagar** [comment]
@Ritiek thanks for your kind response, Well brother Ive tried it with only --gateway option I didnt see it getting any HTTPS site like I;ve tried facebook.com on my tab it didnt work out below it the  IP of my tab.

`2017-01-10 21:11:45 192.168.1.9 [DNS] Could not proxy request: timed out`

Indeed it does work out with ebay.com , Have you tried it with facebook,gmail,twitter,hotmail sites.

Regards
Tehseen Sagar

**Comment by Ritiek** [comment]
@tehseensagar Good to know that it is working now.
Intercepting https traffic depends on the browser being used to access websites.

This guy from stackoverflow may explain better than me:

> For sites like google and facebook several browser have preloaded HSTS (enforce HTTPS) and HPKP (certificate/public key pinning) settings. This means that the browser knows that these sites should be reachable by https only and how the certificate should look like. And this means that stripping SSL and the HSTS header (i.e. your --hsts option) will not work against these sites. It will only work against sites where the browser does not know (yet) that HTTPS is mandatory.

What you would need is to do real SSL man in the middle where you have a HTTPS connection from browser to your man in the middle proxy and from the proxy to the real server. In this case the HTTPS connection to the client is signed by certificates created by the proxy and the relevant proxy CA needs to be explicitly setup as trusted inside the browser/OS.

But from a look at mitmf I don't see that it offers an option for doing real SSL man in the middle, it can only do SSL stripping (i.e. downgrade to plain HTTP) which does not help in case of preloaded HSTS/HPKP. Thus you would need to use other tools like mitmproxy.

http://security.stackexchange.com/questions/123911/replacing-images-on-https-sites-with-mitmf

**Comment by byt3bl33d3r** [comment]
See my response in #381
