### ISSUE TITLE
Feature Request for jskeylogger

### ISSUE THREAD

**Issue by Zaxscdvf** [byt3bl33d3r/MITMf#37]
ok i haven't tested it yet so not sure if it already does this but for the jskeylogger can it also obtain victims info like browser,os,time zone,tabs open etc. also another addition would be even after closing the browser it will save itself in cache only to load itself next time you open the browser. and by the way great project.

**Comment by byt3bl33d3r** [comment]
to do this you would have to create a custom template for the app cache poisoning plugin so its basically already implemented, for os and browser detection just use the browserprofiler plugin

**Comment by Zaxscdvf** [comment]
oh... ok thanks.

**Comment by byt3bl33d3r** [comment]
@Zaxscdvf  np! have any suggestions or questions just drop me an email!
