### ISSUE TITLE
MIMTf just displays MIMTf in diffrent fonts and exits

### ISSUE THREAD

**Issue by Parshuram2** [byt3bl33d3r/MITMf#371]
Well, The title says it pretty much. I am running Kali.20 from a Live USB. No issues with installation came, everything installed including the pip installs (dnslib,watchdog etc). First time run said..it was caching some fonts. Now all it does is show MIMTf written in different fonts  and exits to the directory.
command ran ./mimtf.py -i wlan0 --spoof --hsts --arp --dns --gateway 192.168.1.1
even tried just ./mimtf.py -i wlan0 --gateway 192.168.1.1
same result.
please help.
Thanks.

**Comment by byt3bl33d3r** [comment]
See my response in #381
