### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by chris2lamb** [byt3bl33d3r/MITMf#372]
HI all,
I had already installed without any problem mitmf as described in the instructions. After a crach of my live usb, I am reinstalling it but have this following problem after the command "pip install -r requirements.txt"
Collecting pypcap (from -r requirements.txt (line 25))
  Using cached pypcap-1.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    pcap.h not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d6riLT/pypcap/

Here is the result of "pip freeze":
Warning: cannot find svn location for chirp===daily-20170124
adns-python==1.2.1
AdvancedHTTPServer==2.0.5
alembic==0.8.8.dev0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
attrs==16.3.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.5.3
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
brotlipy==0.6.0
capstone==3.0.4
certifi==2016.2.28
chardet==2.3.0
Cheetah==2.4.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20170124
click==6.6
colorama==0.3.7
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.3.0.post2
constantly==15.1.0
construct==2.5.2
couchdbkit==0.6.5
cryptography==1.7.1
cssutils==1.0
cycler==0.10.0
dap==2.2.6.7
decorator==4.0.11
dicttoxml==1.7.4
dissy==9
distorm3==3.3.4
dnspython==1.15.0
docutils==0.13.1
easygui==0.96
Elixir==0.7.1
enum34==1.1.6
feedparser==5.1.3
Flask==0.12
FormEncode==1.3.0
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.15.2
futures==3.0.5
GeoIP==1.3.2
geoip2==2.4.2
geojson==1.3.1
gevent==1.1.2
gpg==1.8.0
greenlet==0.4.11
h2==2.4.1
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999999999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
icalendar==3.8
idna==2.2
impacket==0.9.15
incremental==16.10.1
ipaddress==1.0.17
IPy==0.83
ipython==5.1.0
ipython-genutils==0.1.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.8
jsbeautifier==1.6.4
jsonpickle==0.9.3
jsonrpclib==0.1.3
keepnote==0.7.8
keyring==10.1
keyrings.alt==1.3
killerbee==1.0
lxml==3.7.1
M2Crypto==0.24.0
Mako==1.0.6
MarkupSafe==0.23
matplotlib==2.0.0
maxminddb==1.2.2
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.18.2
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.7
nassl==0.12
netaddr==0.7.18
NfSpy==1.0
numpy==1.12.0
olefile==0.42.1
openpyxl==2.3.0
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.0.post20161128115349
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathlib2==2.1.0
pathtools==0.1.2
pbr==1.10.0
pcapy==0.10.8
pefile==2016.3.28
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
pluginbase==0.4
prettytable==0.7.2
prompt-toolkit==1.0.9
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycurl==7.43.0
pydns==2.3.6
pyenchant==1.6.7
Pygments==2.2.0
pygobject==3.22.0
pygtkspellcheck==4.0.5
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.4.0
pymssql==1.0.2
pyOpenSSL==16.2.0
pyotp==2.2.1
pyparsing==2.1.10
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.5.1
pyscard==1.9.4
pyserial==3.2.1
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pysqlite==2.7.0
pytest==3.0.5
python-dateutil==2.5.3
python-editor==0.4
python-Levenshtein==0.12.0
python-openid==2.2.5
python-pam==1.8.2
pytz==2016.7
pyusb==1.0.0b2
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
requests==2.12.4
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
scapy===unknown.version
scgi==1.13
SecretStorage==2.3.1
service-identity==16.0.0
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smoke-zephyr==1.0.2
socketpool==0.5.3
SQLAlchemy==1.0.15
stevedore==1.20.0
subprocess32==3.2.7
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
tornado==4.4.2
traitlets==4.3.1
Twisted==16.6.0
typing==3.5.2.2
tzlocal==1.3
urllib3==1.19.1
urwid==1.3.1
uTidylib==0.3
vinetto==0.7b0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
volatility==2.6
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webencodings==0.5
webunit==1.3.10
Werkzeug==0.11.15
wfuzz==0.0.0
Whoosh==2.7.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.5.0
zenmap==7.40
zim==0.65
zope.interface==4.3.2

The command "./mitmf.py --help --log debug" reports:
Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/MITMf/plugins/filepwn.py", line 70, in <module>
    import magic
ImportError: No module named magic

root@kali:~/MITMf# uname -a
Linux kali 4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux

I hope that all the needed informations are there !

Thanks for the help

Chris

**Comment by Ritiek** [comment]
Take a look at #338

**Comment by chris2lamb** [comment]
Thanks for the help
I got the following errors after `sudo pip install -r requirements.txt`
Running setup.py install for NetfilterQueue ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-m4E11q-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0tVFi1-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'netfilterqueue' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c netfilterqueue.c -o build/temp.linux-x86_64-2.7/netfilterqueue.o
    netfilterqueue.c:437:42: fatal error: libnfnetlink/linux_nfnetlink.h: No such file or directory
     #include "libnfnetlink/linux_nfnetlink.h"
                                              ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-m4E11q-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0tVFi1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-m4E11q-build/

However, mitmf seems to start properly, at least with the --help option. I didn't test it extensively...

**Comment by Ritiek** [comment]
`linux_nfnet_laink.h` header is missing too

`sudo apt-get install libnetfilter-queue-dev`

Keep looking up on google for what lib to install to fix the missing header file until there are no more errors.

**Comment by chris2lamb** [comment]
Thanks, I was suspecting it but not sure enough to install that package

What is very strange for me is that I performed exactly the installation with the same wiki instructions 1 month ago without any trouble?
