### ISSUE TITLE
Some problems about installing mitmf on raspberry pi

### ISSUE THREAD

**Issue by p611148aadsl** [byt3bl33d3r/MITMf#384]
I want to know how to install mitmf on raspberry pi?
I heard you installed it on raspberry pi successfully.

**Comment by Ritiek** [comment]
I have it installed on my Raspberry Pi and it works good. What error do you face?

**Comment by p611148aadsl** [comment]
sudo python mitmf.py --hsts -i eth0 --arp --spoof --gateway 192.168.1.1 --target 192.168.1.167
Traceback (most recent call last):
  File "mitmf.py", line 139, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/home/pi/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/home/pi/MITMf/core/sslstrip/ClientRequest.py", line 31, in <module>
    from twisted.internet import ssl
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL

But I found OpenSSL in site-package
(mitmf) pi@raspberrypi:~/MITMf $ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import SSL
>>> 
why??

**Comment by p611148aadsl** [comment]
![qq 20170331152544](https://cloud.githubusercontent.com/assets/11703999/24540733/1a95247e-1627-11e7-8ecd-86990ffd058f.png)

**Comment by byt3bl33d3r** [comment]
@p611148aadsl When you run sudo your environment variables are not transferred over (which are needed for the virtualenv to work). Running ```sudo -E <command>``` should work.
