### ISSUE TITLE
Interface wlan0 does not have an assigned IP address

### ISSUE THREAD

**Issue by NikolasTheBro** [byt3bl33d3r/MITMf#391]
root@Nikolas:~/MITMf# python mitmf.py -i wlan0 --spoof --arp --target 192.168.1.2 --gateway 192.168.1.1
Interface wlan0 does not have an assigned IP address

Getting this error, just installed mitmf
Don't know what to do :(
Please help

**Comment by Ritiek** [comment]
@NikolasTheBro Why did you close this?
