### ISSUE TITLE
MITMF does not do anything need help

### ISSUE THREAD

**Issue by antonely93** [byt3bl33d3r/MITMf#392]
hello,

today i install mitmf via apt-get install mitmf wich is successful
now i launch this: mitmf -i eth0 --spoof --arp --gateway 192.168.1.254 --target 192.168.1.72
And it stuck on this:

███╗ ███╗██╗████████╗███╗ ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║ ██║ ██╔████╔██║█████╗
██║╚██╔╝██║██║ ██║ ██║╚██╔╝██║██╔══╝
██║ ╚═╝ ██║██║ ██║ ██║ ╚═╝ ██║██║
╚═╝ ╚═╝╚═╝ ╚═╝ ╚═╝ ╚═╝╚═╝
[*] MITMf v0.9.8 - 'The Dark Side'
|_ ARP spoofing enabled
| _ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspake online
| |_ SSLstrip+ by Leonardo Nve running
|
|_ Net-Creds v1.0 online
|_MITMf-API online
* Running on http://127.0.0.1:9999/
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

Nothing appear just stuck on this message!

Please how to fix??

**Comment by byt3bl33d3r** [comment]
Closing since you didn't follow the guidelines for submitting a bug report. Please see the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) on how to properly report a bug.
