### ISSUE TITLE
no module named bdfactory

### ISSUE THREAD

**Issue by pieterhouwen** [byt3bl33d3r/MITMf#415]
When running I get the following output, what am I missing?
' 
root@supersecretkali:/opt/Sniffing-Spoofing/mitmf# ./mitmf.py 
Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/opt/Sniffing-Spoofing/mitmf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory
'

**Comment by ritiek** [comment]
Did you follow the [installation instructions](https://github.com/byt3bl33d3r/MITMf/wiki/Installation)? Basically you need to run `git submodule init && git submodule update --recursive` in root directory of `MITMf` repo.

**Comment by pieterhouwen** [comment]
Sweet, that fixed it, I was using an automated script for installation, will contact the guy who wrote that. Thank you very much!

**Comment by root16482** [comment]
What do you mean by the root directory of MITMf repo? Im running parrot os and MITMf comes preinstalled, but when i try to run it it gives me the same error mention above :( Would really appreciate any kind of help!

**Comment by Tayyab1101** [comment]
I was facing the same problem. I used the command "apt-get install mitmf" and it installed automatically. No any problem of bdfactory or any other module!
