### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by Deathlive** [byt3bl33d3r/MITMf#417]
http://prntscr.com/g5vd9a

How to fix?

**Comment by minsectek** [comment]
Remove everything in requirements.txt.
Then, `apt-get install mitmf`
If apt-get doesn't find it, edit `/etc/apt/sources.list` and add `deb http://http.kali.org/kali kali-rolling main contrib non-free` to the bottom of the list.

**Comment by Deathlive** [comment]
@minsectek 
Excuse me but I have a Termux, not Kali.
I just want to know, what the error?
Is it necessary to create this command?  `mkvirtualenv MITMf -p /usr/bin/python2.7`

**Comment by minsectek** [comment]
@Deathlive It's not finding a symbol that it needs in some other module or object. Termux [https://termux.com/package-management.html](comes with apt), it will not matter if you're running Kali or not - as long as you have apt or apt-get, you can use that repo in your sources.list and it will work.

`apt install mitmf`
