### ISSUE TITLE
kali nethunter - can't open file 'mitmf.py'

### ISSUE THREAD

**Issue by xylitol111** [byt3bl33d3r/MITMf#42]
I have a Nexus 7 2013 running Android 4.4.4 with Kali NetHunter 1.10. Everything is freshly installed.
When I launch MITMf it prompts me for the Interface, Gateway, and Target IP. It then asks if I want to run beef-xss, which it answers for me and tries to start it. It shows an error that says "/usr/bin/kalimenu: line 469: cd: /opt/MITMf: No such file or directory."

Then it shows another line that says, "python: can't open file 'mitmf.py': [Errno 2] No such file or directory."

Any ideas?

I did an apt-get remove and apt-get install mitmf and it made no difference.

**Comment by byt3bl33d3r** [comment]
@xylitol111 you should probably open an issue in the kali-nethuner repo, judging by the error though its probable that the path in the kalimenu.sh script is wrong.
