### ISSUE TITLE
MITMf broken by most recent update via update.sh

### ISSUE THREAD

**Issue by thesle3p** [byt3bl33d3r/MITMf#43]
Hi, I just wanna start by saying how much I love this tool, but I noticed that when I run the update script on stock Kali I get the following error:

sudo ./mitmf.py -h
Traceback (most recent call last):
  File "./mitmf.py", line 23, in <module>
    from plugins import *
  File "MITMf/plugins/FilePwn.py", line 52, in <module>
    from libs.bdfactory import pebin
  File "MITMf/libs/bdfactory/pebin.py", line 43, in <module>
    from winapi import winapi
ImportError: No module named winapi
 
I also noticed that by reinstalling the MITMf debian package from Kali fixes this but the issue presents it's self again after running the update script.

**Comment by byt3bl33d3r** [comment]
@thesle3p the update script is intended for non-kali distros, if your running kali you should only update via ```apt-get```

**Comment by secretsquirrel** [comment]
BDF is had an update to patch that bug, should work now.

**Comment by byt3bl33d3r** [comment]
@secretsquirrel good to know ! thanks
