### ISSUE TITLE
MITM TLS Downgrade

### ISSUE THREAD

**Issue by golind** [byt3bl33d3r/MITMf#46]
As seen below.

http://www.praetorian.com/blog/man-in-the-middle-tls-ssl-protocol-downgrade-attack

**Comment by byt3bl33d3r** [comment]
@golind awesome, thanks for this! will look into it

**Comment by byt3bl33d3r** [comment]
@golind all your previous opened issues just popped back up! lol what's going on with your account?

**Comment by RedTiger72** [comment]
HI byt3bl33d3r
I want to install on Kali MITMf v0.9.5, I tried it with the command "apt-get install mitmf" unfortunately install version 0.9.1 by downloading this "mitmf_0.9.1-0kali3_all.deb" from "http://www6.frugalware.org / mirrors / linux / kali / kali / pool / main / m / mitmf / "
-------------------------------------------------------------------------------------------------------------------------------
root@kali:~# apt-get install mitmf
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti saranno inoltre installati:
  backdoor-factory libcapstone3 python-capstone
I seguenti pacchetti NUOVI saranno installati:
  backdoor-factory libcapstone3 mitmf python-capstone
0 aggiornati, 4 installati, 0 da rimuovere e 0 non aggiornati.
È necessario scaricare 0 B/1507 kB di archivi.
Dopo quest'operazione, verranno occupati 6248 kB di spazio su disco.
Continuare [S/n]? s
ATTENZIONE: i seguenti pacchetti non possono essere autenticati.
  libcapstone3 python-capstone backdoor-factory mitmf
Installare questi pacchetti senza verificarli [s/N]? s
Selezionato il pacchetto libcapstone3 non precedentemente selezionato.
(Lettura del database... 348622 file e directory attualmente installati.)
Estrazione di libcapstone3 (da .../libcapstone3_3.0-0kali1_amd64.deb)...
Selezionato il pacchetto python-capstone non precedentemente selezionato.
Estrazione di python-capstone (da .../python-capstone_3.0-0kali1_amd64.deb)...
Selezionato il pacchetto backdoor-factory non precedentemente selezionato.
Estrazione di backdoor-factory (da .../backdoor-factory_2.4.1-0kali2_all.deb)...
Selezionato il pacchetto mitmf non precedentemente selezionato.
Estrazione di mitmf (da .../mitmf_0.9.1-0kali3_all.deb)...
Configurazione di libcapstone3 (3.0-0kali1)...
Configurazione di python-capstone (3.0-0kali1)...
Configurazione di backdoor-factory (2.4.1-0kali2)...
Configurazione di mitmf (0.9.1-0kali3)...
-------------------------------------------------------------------------------------------------------------------------------
I apologize for my ignorance and bad english, are not yet very practical Kali, you can help me solve the problem, big thanks !

**Comment by byt3bl33d3r** [comment]
Hi,
If you have questions regarding the framework please email me and don't
post issues on github.

Kali linux currently has version 0.9.1 in their repositories , if you want
to get the latest version clone the repository on github.


2015-03-11 12:06 GMT+01:00 RedTiger72 <notifications@github.com>:

**Comment by byt3bl33d3r** [comment]
@golind Don't think I will be implementing crypto downgrade attacks since they don't provide immediate value... closing

**Comment by golind** [comment]
No worries! I have some more free time to do things now so I hope you don't mind if I end up bombarding you with more stuff!

**Comment by byt3bl33d3r** [comment]
@golind np, bomb away :P

**Comment by golind** [comment]
You may or may not have receieved an email from me. Please check spam folder. Thanks!
