### ISSUE TITLE
"pip install -r requirements.txt" issue

### ISSUE THREAD

**Issue by nicholasb2101** [byt3bl33d3r/MITMf#461]
"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gJpVkx/pypcap/" error received after installing -r requirements.txt

**Comment by ntcong** [comment]
You need to install libpcap-dev, pypcap's installation process does not make this clear

**Comment by nicholasb2101** [comment]
Thank you for your help ntcong!
