### ISSUE TITLE
Getting a Callback Failure

### ISSUE THREAD

**Issue by RaggedBlade** [byt3bl33d3r/MITMf#51]
```
2015-03-05 15:22:01 192.168.1.113 Sending Request: ads.mp.mydas.mobi
callback failure !
Traceback (most recent call last):
  File "/usr/share/mitmf/plugins/Spoof.py", line 273, in nfqueue_callback
    self.modify_dns(payload, pkt, v)
  File "/usr/share/mitmf/plugins/Spoof.py", line 299, in modify_dns
    spoofed_pkt[DNS].an = DNSRR(rrname=pkt[DNS].qd.qname, ttl=1800, rdata=ip[0]); del ip[0] #have to do this first to initialize the an field
TypeError: 'str' object doesn't support item deletion
2015-03-05 15:22:16 192.168.1.125 Sending Request: configuration.apple.com
```

Any idea what to do? I haven't edited any of the files.

This is the command string:

mitmf -i wlan0 --spoof --arp --dns --hsts --gateway 192.168.1.1

**Comment by byt3bl33d3r** [comment]
@RaggedBlade if your trying to use the hsts bypass plugin the correct syntax is 
```mitmf -i wlan0 --hsts --spoof --arp --gateway 192.168.1.1```

**Comment by ManiMuridi** [comment]
I'm getting a similar issue from "/usr/share/mitmf/plugins/Spoof.py":
   ```'python
    callback failure !
    Traceback (most recent call last):
       File "/usr/share/mitmf/plugins/Spoof.py", line 264, in nfqueue_callback
         data = payload.get_data()
       AttributeError:  'int' object has no attribute 'get_data'

**Comment by byt3bl33d3r** [comment]
@ManiMuridi Update to the latest version to resolve this error

**Comment by ManiMuridi** [comment]
I did apt-get remove mitmf and then apt-get install mitmf and it's still the same...wouldn't that make it get the latest version?

**Comment by byt3bl33d3r** [comment]
@ManiMuridi nope. It will just re-install the version that's currently in the repos.
If you want the latest version follow the instructions in the readme, or wait for the Kali devs to update the version in the repos.

**Comment by ManiMuridi** [comment]
@byt3bl33d3r Thanks for your help. I resolved this by installing the latest version. Quick question, Does the hsts bypass not work on google chrome and firefox? I'm getting the Post data but it's still encrypted...

**Comment by byt3bl33d3r** [comment]
@ManiMuridi it works fine on Firefox and IE. On Chrome it depends on the website.

**Comment by frankie2** [comment]
How do I run mitmf if i have installed it manually from https://github.com/byt3bl33d3r/MITMf ?
