### ISSUE TITLE
Problem with the +hsts while doing the MITM attack

### ISSUE THREAD

**Issue by madmantm** [byt3bl33d3r/MITMf#53]
Hello byt3bl33d3r, 

I keep getting these errors, while doing the MITM attack.
```
2015-03-12 19:01:56 192.168.1.117 Resolving somesite.domain.com for HSTS bypass (DNS)
Exception occurred while modifying DNS: 'netfilterqueue.Packet' object has no attribute 'set_payload'
```
i tried sudo ./mitmf.py -i eth0 --spoof --arp --hsts --gateway 192.168.1.1 --target 192.168.1.117
and i tried sudo ./mitmf.py -i eth0 --spoof --arp --hsts --dns --gateway 192.168.1.1 --target 192.168.1.117

Everything worked before the update.

Thanks a bunch!

**Comment by byt3bl33d3r** [comment]
Hi, 
That error occurs because you installed v0.3 of the NetfilterQueue lib.. please refer to the README to get the correct version.

Also fixed a bug regarding the hsts plugin just a couple of hours ago, so make sure you do a git pull..

**Comment by madmantm** [comment]
Thanks And my apologies for the confusion on my end ;)

Marc-Andre Meloche
