### ISSUE TITLE
missing pcap

### ISSUE THREAD

**Issue by karabekian** [byt3bl33d3r/MITMf#54]
I've got this error:
root@karabekian:~/mitmf# python mitmf.py -i wlan0
Traceback (most recent call last):
  File "mitmf.py", line 17, in <module>
    from plugins import *
  File "/root/mitmf/plugins/Sniffer.py", line 12, in <module>
    import pcap
ImportError: No module named pcap

I use the latest MITMf on Kali, updated, upgraded, with libpcap & python-pcapy.

**Comment by byt3bl33d3r** [comment]
currently Kali doesn't have the latest version in their repos, so this is normal. I'll post a comment here when the kali dev updates the package.

**Comment by karabekian** [comment]
So sorry, I was equivocal.
I don't use Kali package (0.9.1), I installed the latest MITMf from here :)

**Comment by G9Kokos** [comment]
Just do apt-get install python-pypcap
