### ISSUE TITLE
ImportError: No module named netfilterqueue 

### ISSUE THREAD

**Issue by haxor87** [byt3bl33d3r/MITMf#55]
http://kepfeltoltes.hu/150322/K_perny_k_p___2015-03-22_16__20__55_www.kepfeltoltes.hu_.png

**Comment by byt3bl33d3r** [comment]
Please refer to the README to install the correct version of NetfilterQueue

**Comment by haxor87** [comment]
Another problem 
 
http://goo.gl/A9GwVq

**Comment by byt3bl33d3r** [comment]
run the setup.sh script
