### ISSUE TITLE
jskeylogger doesn't handle unicode chars

### ISSUE THREAD

**Issue by ext1** [byt3bl33d3r/MITMf#56]
jskeylogger - Injects a javascript keylogger into clients webpages

i have a real problem, jskeylogger can't write Russian words, how can i fix this, can you help me ?)

**Comment by ext1** [comment]
and one more question, can i write in config file 

#for mail.ru
	mail.ru = mails.ru
	*.mail.ru = *.mails.ru
        www.mail.ru = www.mails.ru

like in ettercap ?

**Comment by byt3bl33d3r** [comment]
@ext1 sorry for the delay. Other lang support isn't really a priority at the moment, if I have some spare time I'll get around to it... If you want to submit a PR though i'll gladly accept it :)

**Comment by byt3bl33d3r** [comment]
@ext1 this should be fixed now thanks to @HAMIDx9  :D

**Comment by ext1** [comment]
Thx !!
