### ISSUE TITLE
no sniff result after --arp  mobile(android)

### ISSUE THREAD

**Issue by gh0st5750** [byt3bl33d3r/MITMf#57]
using --spoof --arp targeted on mobile, it fails and no sniff(--sniff) result obtained.
The network traffic going in/out from mobile devices also got terminated.

**Comment by byt3bl33d3r** [comment]
Can you please tell me what OS your using and the full command string please

PS for future reference please read the section in the readme before sunmitting issues https://github.com/byt3bl33d3r/MITMf#submitting-issues

**Comment by gh0st5750** [comment]
im using Kali linux 3.18.0-kali3-amd64 running on 64 bit VMWare virtual
machine. 

this is the command string that i used:

python mitmf.py --spoof --arp -a -i eth0 --gateway 192.168.1.1 --target
192.168.1.116 --sniffer


My target is Android 4.3 and im testing it via wireless LAN network. After
running this command, target unable to access the internet.

**Comment by byt3bl33d3r** [comment]
what MITMf version are you using? 

also don't know what that ```-a``` is doing in there... the command string should be
```python mitmf.py --spoof --arp -i eth0 --gateway 192.168.1.1 --target
192.168.1.116 --sniffer```

**Comment by gh0st5750** [comment]
tested without --a also produce same result. Im using MITMf version 0.9.5. Im trying to sniff any http/https activity using --sniffer.

**Comment by byt3bl33d3r** [comment]
Try updating to the latest version, just tried it and everything seems to be working fine.. If you tell me what kind of credentials your trying to sniff it might narrow it down for me.

In the meantime I'll close the issue.

**Comment by activenew** [comment]
I Have same issue , there is any solution for this problem?
