### ISSUE TITLE
Update config file options on the fly

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/MITMf#58]

**Comment by byt3bl33d3r** [comment]
Implemented! (see 663f38e732ee1681b226d48fddec922cb6b3d1c3), just have to modify the plugins to support it.

**Comment by mw3demo** [comment]
Sweet! :+1:

**Comment by byt3bl33d3r** [comment]
All done in 70ec5a2bbcb1269389123b58366bb702a2df2265
