### ISSUE TITLE
Captive Portal

### ISSUE THREAD

**Issue by Zaratros** [byt3bl33d3r/MITMf#61]
Hello !

I want to know please if it's possible to create a captive portal and redirect traffic to an ip for example the same way as LANs.py does ? I'm sorry if it's already included, but I could'nt find it.

**Comment by byt3bl33d3r** [comment]
@Zaratros I'm pretty sure LANs.py doesn't set up a captive portal.. you mean arp spoofing by any chance?

**Comment by Zaratros** [comment]
Yes that's what I meant

**Comment by byt3bl33d3r** [comment]
@Zaratros yep already has it , take a look at the spoof plugin
