### ISSUE TITLE
SMBtrap plugin

### ISSUE THREAD

**Issue by vay3t** [byt3bl33d3r/MITMf#62]
is helpful to have a plugin mitmf smb attack.

reference:
https://cdn2.hubspot.net/hubfs/270968/SPEAR/RedirectToSMB_public_whitepaper.pdf

**Comment by byt3bl33d3r** [comment]
Yep, already working on it! thanks

**Comment by byt3bl33d3r** [comment]
Done in 840e202e5bd31e918c5eab3d6114be6071112171, just need to merge to master once the webserver implementation is complete
