### ISSUE TITLE
mitmf available on gentoo

### ISSUE THREAD

**Issue by mudler** [byt3bl33d3r/MITMf#69]
Hi,
I just wanted to notify that i made an ebuild for gentoo to support mitmf, i'm one of the mantainers of spike (a pentesting distribution based on sabayon) and now it's going to be shipped on the distro as well. The ebuild is available [here](https://github.com/Spike-Pentesting/spike-overlay/tree/master/net-misc/mitmf). 
Thanks for the great tool and keep up the good work! :+1:

**Comment by byt3bl33d3r** [comment]
Awesome! :+1: 

Grazie mille ! :)

**Comment by dgikiller** [comment]
Hi, during the usage of this tool it gaves me this stack trace:
``` 
/usr/share/mitmf/mitmf.py 
Traceback (most recent call last):
  File "/usr/share/mitmf/mitmf.py", line 37, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/Responder.py", line 26, in <module>
    from libs.responder.Responder import ResponderMITMf
  File "/usr/share/mitmf/libs/responder/Responder.py", line 54, in <module>
    fileHandler = logging.FileHandler("./logs/responder/Responder-Session.log")
  File "/usr/lib64/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/skullbocks/logs/responder/Responder-Session.log'
```
Could be possible to check if those directory exists or create something like a relative path to launch program from anywhere in the os?
However It's a great tool! :+1: 

Un saluto.

**Comment by byt3bl33d3r** [comment]
@dgikiller shouldn't be that hard to do! will def add fix this in the next update! thanks
