### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by FurqanHanif** [byt3bl33d3r/MITMf#74]
Getting this fatal error when run the setup.sh
using Linux Mint 17.
fatal: Not a git repository (or any of the parent directories): .git

**Comment by byt3bl33d3r** [comment]
@FurqanHanif are you running the script from inside the cloned repo? 
In any case, this isn't really an issue so i'll close it for now...
Have any questions or problems just drop me an email

**Comment by masterkorp** [comment]
@byt3bl33d3r Do you ever considered opening a mailing list or similar for these types of questions ?

[Google groups](https://groups.google.com/forum/#!overview) seems the option for a hosted solution that was a decent web interface, and [mailman 3.0](http://lwn.net/Articles/638090/) is supposed to be a decent self hosted alternative.

**Comment by byt3bl33d3r** [comment]
@masterkorp I don't think it's really necessary.. IMHO irc + github + google + Email is more than enough to figure out any questions you could possibly have
