### ISSUE TITLE
cannot read traffic post

### ISSUE THREAD

**Issue by tipoe** [byt3bl33d3r/MITMf#77]
Hi,
please help me, i try to use mitmf to get post data from https page, but it come to unreadable character.
this it the screen capture 

https://drive.google.com/file/d/0B_FAnmXbk8BvTWhyZjFDR2NDTVhuYS05MWNEZksxTHI4VzJz/view?usp=sharing
 
https://drive.google.com/file/d/0B_FAnmXbk8BveVctZDBLLUVZdVo2dzZrNXRfdHB4WGx1akNj/view?usp=sharing

can you help me what i must to do

**Comment by byt3bl33d3r** [comment]
aaaaaaaand closing...
