### ISSUE TITLE
SSLSTRIP & DNS2PROXY  URL PATH PROBLEM

### ISSUE THREAD

**Issue by konlyk** [byt3bl33d3r/MITMf#82]
Hi , 

I run the command 'python mitmf.py --hsts --spoof --arp --gateway 192.168.13.155 --target 192.168.13.187' in the Kali linux OS. While the site is normally stripped to wwww.google.com an google crash error occurs saying that
 " the requested url /?gfe_rd=cr&ei=gAFaVZzRK8iq8weJiYCYDA&gws_rd=ssl doesn't exist in the server".  I tried to debug both sslstrip and dns2proxy to find the problem but i couldn't find something.

**Comment by byt3bl33d3r** [comment]
@konlyk what mitmf version are you using?

**Comment by byt3bl33d3r** [comment]
@konlyk oops didn't mean to close it

**Comment by konlyk** [comment]
it's ok, i use version 0.9.6 (the latest in the master branch)

**Comment by byt3bl33d3r** [comment]
@konlyk just tried it and it seems to be working fine , are you connecting directly to the proxy?

**Comment by byt3bl33d3r** [comment]
scratch that , just re-read your first comment i'll give it a try with arp spoofing

**Comment by konlyk** [comment]
@byt3bl33d3r  I don't know if it will be of any help but i am uploading two screenshot , one of the problem and one of the mitmf console log. 
![screen shot 2015-05-18 at 7 18 00 pm copy](https://cloud.githubusercontent.com/assets/9538918/7685414/cce4d1b6-fd96-11e4-89c6-f1c7cae59bd1.png)
![Uploading Screen Shot 2015-05-18 at 7.18.17 PM.png…]()

**Comment by byt3bl33d3r** [comment]
@konlyk I think I might have found the problem, and it's a pretty stupid mistake on my part too.. will push a fix later on today

**Comment by konlyk** [comment]
@byt3bl33d3r  Thank you, for the immediate response!

**Comment by byt3bl33d3r** [comment]
@konlyk this should be fixed in 0.9.7
