### ISSUE TITLE
Bug in BeefAutoRun.py when using --beefauto

### ISSUE THREAD

**Issue by mw3demo** [byt3bl33d3r/MITMf#88]
> |_ BeEFAutorun v0.3
> Traceback (most recent call last):
>  File "./mitmf.py", line 136, in <module>
>    p.initialize(args)
>  File "/root/MITMf/plugins/BeefAutorun.py", line 46, in initialize
>    self.tree_output.append("Mode: {}".format(self.config['BeEFAutorun']['mode']))
> AttributeError: 'BeefAutorun' object has no attribute 'tree_output'

On line 46, I edited "self.tree_output.append" to "self.tree_info.append" to reflect your usage in other parts of your code and it appears to have fixed my problem, but I haven't had a chance to test it properly. My eyes refuse to stay open any longer although I want to play around with your latest sweet updates! :sleeping:  :+1:

**Comment by byt3bl33d3r** [comment]
good catch ! fixed in 8b915064c14d8d36b064d5916d8aa769fa84dbb2! Get some sleep :P
