### ISSUE TITLE
Bug in BeefAutorun

### ISSUE THREAD

**Issue by Nyzo** [byt3bl33d3r/MITMf#90]
Rename BeefAPI in beefapi (without capital letters), otherwise this error:
```sh
Traceback (most recent call last):
  File "mitmf.py", line 32, in <module>
    from plugins import *
  File "/etc/MITMf/plugins/BeefAutorun.py", line 26, in <module>
    from core.beefapi import BeefAPI
ImportError: cannot import name BeefAPI
```

**Comment by byt3bl33d3r** [comment]
@Nyzo hi, naming a class with capital letters is perfectly ok in python.
Having said that, don't really know why your getting this error, you probably modified by accident the name of the class.
I suggest you do a ```git reset --hard``` or clone the repo again
