### ISSUE TITLE
How to configure msfrpc

### ISSUE THREAD

**Issue by DrDinosaur** [byt3bl33d3r/MITMf#95]
I keep getting this error: [Msfrpc] Error connecting to Metasploit: ('Connection aborted.', error(111, 'Connection refused'))

What do I need to do to get this working? I've started the service, but it doesn't seem to like it.

**Comment by OctAg0nO** [comment]
Start metasploit, run this command.
load msgrpc ServerHost=127.0.0.1 Pass=abc123

**Comment by byt3bl33d3r** [comment]
@DrDinosaur if you look in the config file (```mitmf.conf```) you will see a section related to Metasploit's MSFrpc server (https://github.com/byt3bl33d3r/MITMf/blob/master/config/mitmf.conf#L20), you can configure username, pass and IP there. 

From the error you gave though is does seem like you didn't start up the RPC server, you can use the command @OctAg0nO gave to do so.

**Comment by DrDinosaur** [comment]
Amazing, it worked perfectly. Thanks :)

**Comment by byt3bl33d3r** [comment]
@DrDinosaur np

**Comment by DrDinosaur** [comment]
Maybe I'm just dumb, but it would seem nice to include that command somewhere.

**Comment by byt3bl33d3r** [comment]
@DrDinosaur if you take a look at some of the quick explanations here http://sign0f4.blogspot.it/, the command is included. I agree that it should def be included in the docs once I start to write them
