### ISSUE TITLE
AttributeError: 'DNSChef' object has no attribute 'loadRecords'

### ISSUE THREAD

**Issue by OctAg0nO** [byt3bl33d3r/MITMf#96]
python mitmf.py -i eth0 --arp --spoof --dns --gateway 10.0.0.1

[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
Traceback (most recent call last):
  File "mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/root/MITMf/plugins/Spoof.py", line 103, in initialize
    DNSChef.getInstance().loadRecords(self.dnscfg)
AttributeError: 'DNSChef' object has no attribute 'loadRecords'

**Comment by byt3bl33d3r** [comment]
@OctAg0nO thanks for catching this! should be fixed now!
