### ISSUE TITLE
TypeError: DNS() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by OctAg0nO** [byt3bl33d3r/MITMf#98]
python mitmf.py  -i wlan0 --arp --spoof --hsts --gateway 10.0.0.1

[*] MITMf v0.9.7 online... initializing plugins
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
Traceback (most recent call last):
  File "mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/root/MITMf/plugins/SSLstrip+.py", line 44, in initialize
    IpTables.getInstance().DNS(ip_address, self.config['MITMf']['DNS']['port'])
TypeError: DNS() takes exactly 2 arguments (3 given)

**Comment by byt3bl33d3r** [comment]
fixed in 87cb98b6acdaca006dd7623b5a32590ab03954f7

**Comment by byt3bl33d3r** [comment]
@OctAg0nO thanks
