### ISSUE TITLE
HSTS Bypass DNS not working

### ISSUE THREAD

**Issue by DrDinosaur** [byt3bl33d3r/MITMf#99]
So when I enter "www.facebook.com," I get this:
http://gyazo.com/48cf1bd3972ccd52a3eacdd4840e0461 
The page is obviously messed up. When I click the "Facebook logo" link, I get this:
http://gyazo.com/59ff269dc405911cd3299f9d9f5c2448
So "social.facebook.com" goes nowhere.

**Comment by byt3bl33d3r** [comment]
@DrDinosaur you running the latest version of the framework?

**Comment by byt3bl33d3r** [comment]
@DrDinosaur this is a very old bug that was fixed a while ago, i'll close the issue for now , feel free to comment below

**Comment by DrDinosaur** [comment]
I just pulled it off Github a day or so ago.

**Comment by byt3bl33d3r** [comment]
@DrDinosaur just tried it on IE via arp-spoofing and everything seems to be working can you give me the os and IE version you used?

**Comment by DrDinosaur** [comment]
Just tried again- same error. 
IE: 11.0.9600.17801
11.0.19 
(from About Internet Explorer)
OS: Windows 7 SP1

This was the command I used: 
./mitmf.py -i eth0 --spoof --arp -p -f --hsts --gateway 192.168.2.1 --targets 192.168.2.104

Do I need DNS? If so, that gives the following error:
|_ Spoof v0.6
Traceback (most recent call last):
  File "./mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/root/Scripts/MITMf/plugins/Spoof.py", line 103, in initialize
    DNSChef.getInstance().loadRecords(self.dnscfg)
AttributeError: 'DNSChef' object has no attribute 'loadRecords'

**Comment by byt3bl33d3r** [comment]
@DrDinosaur that bug was fixed in #96 do a git pull to get the changes

**Comment by byt3bl33d3r** [comment]
@DrDinosaur I'll try again on a windows 7 box tmw, was using IE on win 8

**Comment by DrDinosaur** [comment]
Yep, it seems to work now. The Facebook page looks dated though. 

I tried another HSTS site, edmodo.com. At first, it didn't work. It went to the secure site. 

I went into the config file so www.edmodo.com would be edu.edmodo.com. Then it worked perfectly. 

Can we do this automatically so we don't have to manually add each site?

**Comment by byt3bl33d3r** [comment]
@DrDinosaur it already does it automatically (e.g. ```www.edmondo.com``` should be redirected to ```wwww.edmondo.com```), sometimes though specifying an entry in the config file works better for some websites, so it's very trial and error.

**Comment by DrDinosaur** [comment]
Might it have to do with this: https://hstspreload.appspot.com/
